[
  {
    confirmed      => 54406,
    country_region => "Mainland China",
    deaths         => 1457,
    last_update    => "2020-02-14T23:33:02",
    province_state => "Hubei",
    recovered      => 4774,
  },
  {
    confirmed      => 1261,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-14T12:53:02",
    province_state => "Guangdong",
    recovered      => 362,
  },
  {
    confirmed      => 1184,
    country_region => "Mainland China",
    deaths         => 11,
    last_update    => "2020-02-14T12:53:02",
    province_state => "Henan",
    recovered      => 357,
  },
  {
    confirmed      => 1155,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-14T14:13:15",
    province_state => "Zhejiang",
    recovered      => 403,
  },
  {
    confirmed      => 988,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-14T09:23:04",
    province_state => "Hunan",
    recovered      => 364,
  },
  {
    confirmed      => 934,
    country_region => "Mainland China",
    deaths         => 6,
    last_update    => "2020-02-14T12:53:02",
    province_state => "Anhui",
    recovered      => 193,
  },
  {
    confirmed      => 900,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-14T01:13:06",
    province_state => "Jiangxi",
    recovered      => 187,
  },
  {
    confirmed      => 593,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-14T10:03:03",
    province_state => "Jiangsu",
    recovered      => 157,
  },
  {
    confirmed      => 537,
    country_region => "Mainland China",
    deaths         => 5,
    last_update    => "2020-02-14T23:33:02",
    province_state => "Chongqing",
    recovered      => 152,
  },
  {
    confirmed      => 523,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-14T11:13:22",
    province_state => "Shandong",
    recovered      => 136,
  },
  {
    confirmed      => 463,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-14T11:13:22",
    province_state => "Sichuan",
    recovered      => 114,
  },
  {
    confirmed      => 419,
    country_region => "Mainland China",
    deaths         => 11,
    last_update    => "2020-02-14T13:23:07",
    province_state => "Heilongjiang",
    recovered      => 47,
  },
  {
    confirmed      => 372,
    country_region => "Mainland China",
    deaths         => 3,
    last_update    => "2020-02-14T06:33:02",
    province_state => "Beijing",
    recovered      => 80,
  },
  {
    confirmed      => 318,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-14T04:13:11",
    province_state => "Shanghai",
    recovered      => 90,
  },
  {
    confirmed      => 283,
    country_region => "Mainland China",
    deaths         => 3,
    last_update    => "2020-02-14T11:13:22",
    province_state => "Hebei",
    recovered      => 87,
  },
  {
    confirmed      => 281,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-14T11:13:22",
    province_state => "Fujian",
    recovered      => 63,
  },
  {
    confirmed      => 230,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-14T12:53:02",
    province_state => "Shaanxi",
    recovered      => 54,
  },
  {
    confirmed      => 226,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-14T15:23:02",
    province_state => "Guangxi",
    recovered      => 36,
  },
  {
    confirmed      => 218,
    country_region => "Others",
    deaths         => 0,
    last_update    => "2020-02-14T00:13:23",
    province_state => "Diamond Princess cruise ship",
    recovered      => 0,
  },
  {
    confirmed      => 162,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-14T12:53:02",
    province_state => "Yunnan",
    recovered      => 36,
  },
  {
    confirmed      => 159,
    country_region => "Mainland China",
    deaths         => 4,
    last_update    => "2020-02-14T15:23:02",
    province_state => "Hainan",
    recovered      => 43,
  },
  {
    confirmed      => 140,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-14T01:53:02",
    province_state => "Guizhou",
    recovered      => 28,
  },
  {
    confirmed      => 127,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-14T23:23:04",
    province_state => "Shanxi",
    recovered      => 38,
  },
  {
    confirmed      => 120,
    country_region => "Mainland China",
    deaths         => 3,
    last_update    => "2020-02-14T11:13:22",
    province_state => "Tianjin",
    recovered      => 31,
  },
  {
    confirmed      => 119,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-14T15:23:02",
    province_state => "Liaoning",
    recovered      => 29,
  },
  {
    confirmed      => 90,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-13T15:53:03",
    province_state => "Gansu",
    recovered      => 39,
  },
  {
    confirmed      => 86,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-14T00:43:02",
    province_state => "Jilin",
    recovered      => 25,
  },
  {
    confirmed      => 67,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-14T01:43:02",
    province_state => "Ningxia",
    recovered      => 24,
  },
  {
    confirmed      => 67,
    country_region => "Singapore",
    deaths         => 0,
    last_update    => "2020-02-14T12:43:02",
    province_state => "",
    recovered      => 17,
  },
  {
    confirmed      => 65,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-14T02:03:08",
    province_state => "Inner Mongolia",
    recovered      => 6,
  },
  {
    confirmed      => 65,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-14T01:13:06",
    province_state => "Xinjiang",
    recovered      => 6,
  },
  {
    confirmed      => 56,
    country_region => "Hong Kong",
    deaths         => 1,
    last_update    => "2020-02-14T09:03:12",
    province_state => "Hong Kong",
    recovered      => 1,
  },
  {
    confirmed      => 33,
    country_region => "Thailand",
    deaths         => 0,
    last_update    => "2020-02-13T17:53:03",
    province_state => "",
    recovered      => 12,
  },
  {
    confirmed      => 29,
    country_region => "Japan",
    deaths         => 1,
    last_update    => "2020-02-14T03:53:02",
    province_state => "",
    recovered      => 9,
  },
  {
    confirmed      => 28,
    country_region => "South Korea",
    deaths         => 0,
    last_update    => "2020-02-12T14:43:03",
    province_state => "",
    recovered      => 7,
  },
  {
    confirmed      => 19,
    country_region => "Malaysia",
    deaths         => 0,
    last_update    => "2020-02-13T10:53:02",
    province_state => "",
    recovered      => 3,
  },
  {
    confirmed      => 18,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-13T08:43:08",
    province_state => "Qinghai",
    recovered      => 11,
  },
  {
    confirmed      => 18,
    country_region => "Taiwan",
    deaths         => 0,
    last_update    => "2020-02-14T02:13:06",
    province_state => "Taiwan",
    recovered      => 2,
  },
  {
    confirmed      => 16,
    country_region => "Germany",
    deaths         => 0,
    last_update    => "2020-02-13T15:13:11",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 16,
    country_region => "Vietnam",
    deaths         => 0,
    last_update    => "2020-02-13T06:33:02",
    province_state => "",
    recovered      => 7,
  },
  {
    confirmed      => 11,
    country_region => "France",
    deaths         => 0,
    last_update    => "2020-02-12T18:53:02",
    province_state => "",
    recovered      => 2,
  },
  {
    confirmed      => 10,
    country_region => "Macau",
    deaths         => 0,
    last_update    => "2020-02-13T14:13:06",
    province_state => "Macau",
    recovered      => 3,
  },
  {
    confirmed      => 9,
    country_region => "UK",
    deaths         => 0,
    last_update    => "2020-02-12T19:03:06",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 8,
    country_region => "United Arab Emirates",
    deaths         => 0,
    last_update    => "2020-02-12T00:33:02",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 5,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-09T19:33:02",
    province_state => "Queensland",
    recovered      => 0,
  },
  {
    confirmed      => 4,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-13T17:53:03",
    province_state => "New South Wales",
    recovered      => 4,
  },
  {
    confirmed      => 4,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-13T17:53:03",
    province_state => "Victoria",
    recovered      => 4,
  },
  {
    confirmed      => 4,
    country_region => "Canada",
    deaths         => 0,
    last_update    => "2020-02-07T05:43:03",
    province_state => "British Columbia",
    recovered      => 0,
  },
  {
    confirmed      => 3,
    country_region => "India",
    deaths         => 0,
    last_update    => "2020-02-13T18:53:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 3,
    country_region => "Italy",
    deaths         => 0,
    last_update    => "2020-02-07T17:53:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 3,
    country_region => "Philippines",
    deaths         => 1,
    last_update    => "2020-02-12T07:43:02",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 2,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-02T22:33:07",
    province_state => "South Australia",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "Canada",
    deaths         => 0,
    last_update    => "2020-02-04T00:13:06",
    province_state => "Toronto, ON",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "Russia",
    deaths         => 0,
    last_update    => "2020-02-12T14:43:03",
    province_state => "",
    recovered      => 2,
  },
  {
    confirmed      => 2,
    country_region => "Spain",
    deaths         => 0,
    last_update    => "2020-02-09T20:33:03",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-09T19:03:03",
    province_state => "Chicago, IL",
    recovered      => 2,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-03T03:53:02",
    province_state => "San Benito, CA",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-13T03:13:08",
    province_state => "San Diego County, CA",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-03T00:43:02",
    province_state => "Santa Clara, CA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Belgium",
    deaths         => 0,
    last_update    => "2020-02-04T15:43:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Cambodia",
    deaths         => 0,
    last_update    => "2020-02-12T07:43:02",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Canada",
    deaths         => 0,
    last_update    => "2020-02-12T18:53:03",
    province_state => "London, ON",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Egypt",
    deaths         => 0,
    last_update    => "2020-02-14T23:53:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Finland",
    deaths         => 0,
    last_update    => "2020-02-12T00:03:12",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-12T06:43:02",
    province_state => "Tibet",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Nepal",
    deaths         => 0,
    last_update    => "2020-02-12T14:43:03",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Sri Lanka",
    deaths         => 0,
    last_update    => "2020-02-08T03:43:03",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Sweden",
    deaths         => 0,
    last_update    => "2020-02-01T02:13:26",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:43:03",
    province_state => "Boston, MA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:53:03",
    province_state => "Los Angeles, CA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-05T21:53:02",
    province_state => "Madison, WI",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:53:03",
    province_state => "Orange, CA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-13T18:53:02",
    province_state => "San Antonio, TX",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-09T07:03:04",
    province_state => "Seattle, WA",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:43:03",
    province_state => "Tempe, AZ",
    recovered      => 0,
  },
]