[
  {
    confirmed      => 19665,
    country_region => "Mainland China",
    deaths         => 549,
    last_update    => "2020-02-05T23:13:12",
    province_state => "Hubei",
    recovered      => 633,
  },
  {
    confirmed      => 895,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-05T13:23:04",
    province_state => "Guangdong",
    recovered      => 49,
  },
  {
    confirmed      => 895,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-05T15:13:02",
    province_state => "Zhejiang",
    recovered      => 78,
  },
  {
    confirmed      => 764,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-05T15:03:02",
    province_state => "Henan",
    recovered      => 47,
  },
  {
    confirmed      => 661,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-05T15:23:02",
    province_state => "Hunan",
    recovered      => 54,
  },
  {
    confirmed      => 548,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-05T01:33:07",
    province_state => "Jiangxi",
    recovered      => 27,
  },
  {
    confirmed      => 530,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-05T13:43:02",
    province_state => "Anhui",
    recovered      => 23,
  },
  {
    confirmed      => 389,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-05T23:43:02",
    province_state => "Chongqing",
    recovered      => 15,
  },
  {
    confirmed      => 341,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-05T12:43:02",
    province_state => "Jiangsu",
    recovered      => 23,
  },
  {
    confirmed      => 307,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-05T10:13:13",
    province_state => "Shandong",
    recovered      => 15,
  },
  {
    confirmed      => 301,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-05T10:13:13",
    province_state => "Sichuan",
    recovered      => 24,
  },
  {
    confirmed      => 253,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-05T05:43:02",
    province_state => "Beijing",
    recovered      => 24,
  },
  {
    confirmed      => 243,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-05T06:23:04",
    province_state => "Shanghai",
    recovered      => 15,
  },
  {
    confirmed      => 205,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-05T12:33:01",
    province_state => "Fujian",
    recovered      => 11,
  },
  {
    confirmed      => 190,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-05T12:13:04",
    province_state => "Heilongjiang",
    recovered      => 7,
  },
  {
    confirmed      => 165,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-05T08:43:01",
    province_state => "Shaanxi",
    recovered      => 6,
  },
  {
    confirmed      => 150,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-05T12:03:08",
    province_state => "Guangxi",
    recovered      => 13,
  },
  {
    confirmed      => 135,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-05T11:23:18",
    province_state => "Hebei",
    recovered      => 6,
  },
  {
    confirmed      => 128,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-05T23:33:02",
    province_state => "Yunnan",
    recovered      => 5,
  },
  {
    confirmed      => 99,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-05T16:43:04",
    province_state => "Hainan",
    recovered      => 5,
  },
  {
    confirmed      => 89,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-05T15:23:02",
    province_state => "Liaoning",
    recovered      => 4,
  },
  {
    confirmed      => 81,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-05T15:23:02",
    province_state => "Shanxi",
    recovered      => 5,
  },
  {
    confirmed      => 69,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-05T03:43:02",
    province_state => "Tianjin",
    recovered      => 2,
  },
  {
    confirmed      => 64,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-05T12:33:02",
    province_state => "Guizhou",
    recovered      => 9,
  },
  {
    confirmed      => 62,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-05T16:23:06",
    province_state => "Gansu",
    recovered      => 6,
  },
  {
    confirmed      => 54,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-05T11:03:16",
    province_state => "Jilin",
    recovered      => 2,
  },
  {
    confirmed      => 42,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-05T08:53:02",
    province_state => "Inner Mongolia",
    recovered      => 3,
  },
  {
    confirmed      => 34,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-04T02:13:18",
    province_state => "Ningxia",
    recovered      => 1,
  },
  {
    confirmed      => 32,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-05T02:03:13",
    province_state => "Xinjiang",
    recovered      => 0,
  },
  {
    confirmed      => 28,
    country_region => "Singapore",
    deaths         => 0,
    last_update    => "2020-02-05T16:33:03",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 25,
    country_region => "Thailand",
    deaths         => 0,
    last_update    => "2020-02-04T15:33:03",
    province_state => "",
    recovered      => 5,
  },
  {
    confirmed      => 22,
    country_region => "Japan",
    deaths         => 0,
    last_update    => "2020-02-04T16:43:03",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 21,
    country_region => "Hong Kong",
    deaths         => 1,
    last_update    => "2020-02-05T13:13:10",
    province_state => "Hong Kong",
    recovered      => 0,
  },
  {
    confirmed      => 19,
    country_region => "South Korea",
    deaths         => 0,
    last_update    => "2020-02-05T15:33:01",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 17,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-05T03:13:05",
    province_state => "Qinghai",
    recovered      => 3,
  },
  {
    confirmed      => 12,
    country_region => "Germany",
    deaths         => 0,
    last_update    => "2020-02-03T20:53:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 12,
    country_region => "Malaysia",
    deaths         => 0,
    last_update    => "2020-02-05T15:43:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 11,
    country_region => "Taiwan",
    deaths         => 0,
    last_update    => "2020-02-04T14:53:02",
    province_state => "Taiwan",
    recovered      => 0,
  },
  {
    confirmed      => 10,
    country_region => "Macau",
    deaths         => 0,
    last_update    => "2020-02-04T04:43:02",
    province_state => "Macau",
    recovered      => 0,
  },
  {
    confirmed      => 8,
    country_region => "Vietnam",
    deaths         => 0,
    last_update    => "2020-02-03T21:43:02",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 6,
    country_region => "France",
    deaths         => 0,
    last_update    => "2020-02-01T01:52:40",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 5,
    country_region => "United Arab Emirates",
    deaths         => 0,
    last_update    => "2020-02-02T05:43:01",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 4,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-01T18:12:49",
    province_state => "New South Wales",
    recovered      => 2,
  },
  {
    confirmed      => 4,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-01T18:12:49",
    province_state => "Victoria",
    recovered      => 0,
  },
  {
    confirmed      => 3,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-04T16:53:03",
    province_state => "Queensland",
    recovered      => 0,
  },
  {
    confirmed      => 3,
    country_region => "India",
    deaths         => 0,
    last_update    => "2020-02-03T21:43:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-02T22:33:07",
    province_state => "South Australia",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "Canada",
    deaths         => 0,
    last_update    => "2020-02-05T17:33:03",
    province_state => "British Columbia",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "Canada",
    deaths         => 0,
    last_update    => "2020-02-04T00:13:06",
    province_state => "Toronto, ON",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "Italy",
    deaths         => 0,
    last_update    => "2020-01-31T08:15:53",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "Philippines",
    deaths         => 1,
    last_update    => "2020-02-02T03:33:07",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "Russia",
    deaths         => 0,
    last_update    => "2020-01-31T16:13:45",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "UK",
    deaths         => 0,
    last_update    => "2020-02-01T01:52:40",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:43:03",
    province_state => "Chicago, IL",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-03T03:53:02",
    province_state => "San Benito, CA",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-03T00:43:02",
    province_state => "Santa Clara, CA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Belgium",
    deaths         => 0,
    last_update    => "2020-02-04T15:43:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Cambodia",
    deaths         => 0,
    last_update    => "2020-01-31T08:15:53",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Canada",
    deaths         => 0,
    last_update    => "2020-02-04T00:03:11",
    province_state => "London, ON",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Finland",
    deaths         => 0,
    last_update    => "2020-01-31T08:15:53",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-01T01:52:40",
    province_state => "Tibet",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Nepal",
    deaths         => 0,
    last_update    => "2020-01-31T08:15:53",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Spain",
    deaths         => 0,
    last_update    => "2020-02-01T23:43:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Sri Lanka",
    deaths         => 0,
    last_update    => "2020-01-31T08:15:53",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Sweden",
    deaths         => 0,
    last_update    => "2020-02-01T02:13:26",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:43:03",
    province_state => "Boston, MA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:53:03",
    province_state => "Los Angeles, CA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-05T21:53:02",
    province_state => "Madison, WI",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:53:03",
    province_state => "Orange, CA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:43:03",
    province_state => "Seattle, WA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:43:03",
    province_state => "Tempe, AZ",
    recovered      => 0,
  },
]