[
  {
    confirmed      => 64287,
    country_region => "Mainland China",
    deaths         => 2495,
    last_update    => "2020-02-24T11:13:09",
    province_state => "Hubei",
    recovered      => 16748,
  },
  {
    confirmed      => 1345,
    country_region => "Mainland China",
    deaths         => 6,
    last_update    => "2020-02-24T10:23:02",
    province_state => "Guangdong",
    recovered      => 786,
  },
  {
    confirmed      => 1271,
    country_region => "Mainland China",
    deaths         => 19,
    last_update    => "2020-02-24T13:23:05",
    province_state => "Henan",
    recovered      => 943,
  },
  {
    confirmed      => 1205,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-24T09:43:02",
    province_state => "Zhejiang",
    recovered      => 782,
  },
  {
    confirmed      => 1016,
    country_region => "Mainland China",
    deaths         => 4,
    last_update    => "2020-02-24T14:13:11",
    province_state => "Hunan",
    recovered      => 731,
  },
  {
    confirmed      => 989,
    country_region => "Mainland China",
    deaths         => 6,
    last_update    => "2020-02-24T09:43:02",
    province_state => "Anhui",
    recovered      => 663,
  },
  {
    confirmed      => 934,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-24T01:23:09",
    province_state => "Jiangxi",
    recovered      => 645,
  },
  {
    confirmed      => 833,
    country_region => "South Korea",
    deaths         => 8,
    last_update    => "2020-02-24T11:13:10",
    province_state => "",
    recovered      => 18,
  },
  {
    confirmed      => 755,
    country_region => "Mainland China",
    deaths         => 5,
    last_update    => "2020-02-24T10:23:02",
    province_state => "Shandong",
    recovered      => 343,
  },
  {
    confirmed      => 691,
    country_region => "Others",
    deaths         => 3,
    last_update    => "2020-02-23T22:33:03",
    province_state => "Diamond Princess cruise ship",
    recovered      => 0,
  },
  {
    confirmed      => 631,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-24T14:53:02",
    province_state => "Jiangsu",
    recovered      => 452,
  },
  {
    confirmed      => 576,
    country_region => "Mainland China",
    deaths         => 6,
    last_update    => "2020-02-24T23:23:01",
    province_state => "Chongqing",
    recovered      => 349,
  },
  {
    confirmed      => 527,
    country_region => "Mainland China",
    deaths         => 3,
    last_update    => "2020-02-24T14:13:11",
    province_state => "Sichuan",
    recovered      => 276,
  },
  {
    confirmed      => 480,
    country_region => "Mainland China",
    deaths         => 12,
    last_update    => "2020-02-24T14:53:02",
    province_state => "Heilongjiang",
    recovered      => 227,
  },
  {
    confirmed      => 399,
    country_region => "Mainland China",
    deaths         => 4,
    last_update    => "2020-02-24T00:53:02",
    province_state => "Beijing",
    recovered      => 198,
  },
  {
    confirmed      => 335,
    country_region => "Mainland China",
    deaths         => 3,
    last_update    => "2020-02-24T07:03:06",
    province_state => "Shanghai",
    recovered      => 261,
  },
  {
    confirmed      => 311,
    country_region => "Mainland China",
    deaths         => 6,
    last_update    => "2020-02-24T14:13:11",
    province_state => "Hebei",
    recovered      => 234,
  },
  {
    confirmed      => 293,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-24T10:23:02",
    province_state => "Fujian",
    recovered      => 183,
  },
  {
    confirmed      => 251,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-24T06:53:02",
    province_state => "Guangxi",
    recovered      => 112,
  },
  {
    confirmed      => 245,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-24T14:53:02",
    province_state => "Shaanxi",
    recovered      => 173,
  },
  {
    confirmed      => 229,
    country_region => "Italy",
    deaths         => 7,
    last_update    => "2020-02-24T23:43:01",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 174,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-24T23:13:02",
    province_state => "Yunnan",
    recovered      => 124,
  },
  {
    confirmed      => 168,
    country_region => "Mainland China",
    deaths         => 5,
    last_update    => "2020-02-24T14:53:02",
    province_state => "Hainan",
    recovered      => 116,
  },
  {
    confirmed      => 159,
    country_region => "Japan",
    deaths         => 1,
    last_update    => "2020-02-24T14:23:03",
    province_state => "",
    recovered      => 22,
  },
  {
    confirmed      => 146,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-23T12:43:02",
    province_state => "Guizhou",
    recovered      => 102,
  },
  {
    confirmed      => 135,
    country_region => "Mainland China",
    deaths         => 3,
    last_update    => "2020-02-24T15:03:05",
    province_state => "Tianjin",
    recovered      => 87,
  },
  {
    confirmed      => 133,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-24T23:13:02",
    province_state => "Shanxi",
    recovered      => 94,
  },
  {
    confirmed      => 121,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-24T06:53:02",
    province_state => "Liaoning",
    recovered      => 80,
  },
  {
    confirmed      => 93,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-24T09:43:02",
    province_state => "Jilin",
    recovered      => 60,
  },
  {
    confirmed      => 91,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-24T15:13:07",
    province_state => "Gansu",
    recovered      => 80,
  },
  {
    confirmed      => 89,
    country_region => "Singapore",
    deaths         => 0,
    last_update    => "2020-02-23T15:13:15",
    province_state => "",
    recovered      => 51,
  },
  {
    confirmed      => 79,
    country_region => "Hong Kong",
    deaths         => 2,
    last_update    => "2020-02-24T11:23:06",
    province_state => "Hong Kong",
    recovered      => 19,
  },
  {
    confirmed      => 76,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-24T15:03:05",
    province_state => "Xinjiang",
    recovered      => 30,
  },
  {
    confirmed      => 75,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-24T15:03:05",
    province_state => "Inner Mongolia",
    recovered      => 34,
  },
  {
    confirmed      => 71,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-24T06:53:02",
    province_state => "Ningxia",
    recovered      => 58,
  },
  {
    confirmed      => 61,
    country_region => "Iran",
    deaths         => 12,
    last_update    => "2020-02-24T11:13:10",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 36,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-24T23:33:02",
    province_state => "Unassigned Location (From Diamond Princess)",
    recovered      => 0,
  },
  {
    confirmed      => 35,
    country_region => "Thailand",
    deaths         => 0,
    last_update    => "2020-02-23T15:03:05",
    province_state => "",
    recovered      => 21,
  },
  {
    confirmed      => 30,
    country_region => "Taiwan",
    deaths         => 1,
    last_update    => "2020-02-24T10:13:28",
    province_state => "Taiwan",
    recovered      => 5,
  },
  {
    confirmed      => 22,
    country_region => "Malaysia",
    deaths         => 0,
    last_update    => "2020-02-24T11:53:02",
    province_state => "",
    recovered      => 18,
  },
  {
    confirmed      => 18,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-21T04:43:02",
    province_state => "Qinghai",
    recovered      => 18,
  },
  {
    confirmed      => 16,
    country_region => "Germany",
    deaths         => 0,
    last_update    => "2020-02-21T23:03:13",
    province_state => "",
    recovered      => 14,
  },
  {
    confirmed      => 16,
    country_region => "Vietnam",
    deaths         => 0,
    last_update    => "2020-02-21T06:03:04",
    province_state => "",
    recovered      => 14,
  },
  {
    confirmed      => 13,
    country_region => "UK",
    deaths         => 0,
    last_update    => "2020-02-24T08:33:02",
    province_state => "",
    recovered      => 8,
  },
  {
    confirmed      => 13,
    country_region => "United Arab Emirates",
    deaths         => 0,
    last_update    => "2020-02-22T14:53:02",
    province_state => "",
    recovered      => 4,
  },
  {
    confirmed      => 12,
    country_region => "France",
    deaths         => 1,
    last_update    => "2020-02-15T20:53:02",
    province_state => "",
    recovered      => 4,
  },
  {
    confirmed      => 10,
    country_region => "Macau",
    deaths         => 0,
    last_update    => "2020-02-20T02:13:19",
    province_state => "Macau",
    recovered      => 6,
  },
  {
    confirmed      => 7,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-22T17:03:05",
    province_state => "From Diamond Princess",
    recovered      => 0,
  },
  {
    confirmed      => 6,
    country_region => "Canada",
    deaths         => 0,
    last_update    => "2020-02-21T05:23:04",
    province_state => "British Columbia",
    recovered      => 0,
  },
  {
    confirmed      => 5,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-21T05:43:02",
    province_state => "Queensland",
    recovered      => 1,
  },
  {
    confirmed      => 4,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-13T17:53:03",
    province_state => "New South Wales",
    recovered      => 4,
  },
  {
    confirmed      => 4,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-13T17:53:03",
    province_state => "Victoria",
    recovered      => 4,
  },
  {
    confirmed      => 3,
    country_region => "Canada",
    deaths         => 0,
    last_update    => "2020-02-24T14:43:03",
    province_state => "Toronto, ON",
    recovered      => 2,
  },
  {
    confirmed      => 3,
    country_region => "India",
    deaths         => 0,
    last_update    => "2020-02-16T07:43:02",
    province_state => "",
    recovered      => 3,
  },
  {
    confirmed      => 3,
    country_region => "Philippines",
    deaths         => 1,
    last_update    => "2020-02-12T07:43:02",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 2,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-17T08:13:09",
    province_state => "South Australia",
    recovered      => 2,
  },
  {
    confirmed      => 2,
    country_region => "Oman",
    deaths         => 0,
    last_update    => "2020-02-24T23:43:01",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "Russia",
    deaths         => 0,
    last_update    => "2020-02-12T14:43:03",
    province_state => "",
    recovered      => 2,
  },
  {
    confirmed      => 2,
    country_region => "Spain",
    deaths         => 0,
    last_update    => "2020-02-15T17:23:04",
    province_state => "",
    recovered      => 2,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-09T19:03:03",
    province_state => "Chicago, IL",
    recovered      => 2,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-03T03:53:02",
    province_state => "San Benito, CA",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-21T05:43:02",
    province_state => "San Diego County, CA",
    recovered      => 1,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-21T05:23:04",
    province_state => "Santa Clara, CA",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Afghanistan",
    deaths         => 0,
    last_update    => "2020-02-24T23:33:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Bahrain",
    deaths         => 0,
    last_update    => "2020-02-24T23:33:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Belgium",
    deaths         => 0,
    last_update    => "2020-02-17T04:23:06",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Cambodia",
    deaths         => 0,
    last_update    => "2020-02-12T07:43:02",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Canada",
    deaths         => 0,
    last_update    => "2020-02-12T18:53:03",
    province_state => "London, ON",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Egypt",
    deaths         => 0,
    last_update    => "2020-02-21T18:53:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Finland",
    deaths         => 0,
    last_update    => "2020-02-12T00:03:12",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Iraq",
    deaths         => 0,
    last_update    => "2020-02-24T23:33:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Israel",
    deaths         => 0,
    last_update    => "2020-02-22T20:53:02",
    province_state => "From Diamond Princess",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Kuwait",
    deaths         => 0,
    last_update    => "2020-02-24T23:33:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Lebanon",
    deaths         => 0,
    last_update    => "2020-02-22T20:53:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-12T06:43:02",
    province_state => "Tibet",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Nepal",
    deaths         => 0,
    last_update    => "2020-02-12T14:43:03",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Sri Lanka",
    deaths         => 0,
    last_update    => "2020-02-08T03:43:03",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Sweden",
    deaths         => 0,
    last_update    => "2020-02-01T02:13:26",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:43:03",
    province_state => "Boston, MA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-21T05:13:09",
    province_state => "Humboldt County, CA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:53:03",
    province_state => "Los Angeles, CA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-05T21:53:02",
    province_state => "Madison, WI",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:53:03",
    province_state => "Orange, CA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-21T23:13:16",
    province_state => "Sacramento County, CA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-13T18:53:02",
    province_state => "San Antonio, TX",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-09T07:03:04",
    province_state => "Seattle, WA",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:43:03",
    province_state => "Tempe, AZ",
    recovered      => 0,
  },
  {
    confirmed      => 0,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-24T23:33:02",
    province_state => "Lackland, TX (From Diamond Princess)",
    recovered      => 0,
  },
  {
    confirmed      => 0,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-24T23:33:02",
    province_state => "Omaha, NE (From Diamond Princess)",
    recovered      => 0,
  },
  {
    confirmed      => 0,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-24T23:33:02",
    province_state => "Travis, CA (From Diamond Princess)",
    recovered      => 0,
  },
]