[
  {
    confirmed      => 62031,
    country_region => "Mainland China",
    deaths         => 2029,
    last_update    => "2020-02-19T23:23:02",
    province_state => "Hubei",
    recovered      => 10337,
  },
  {
    confirmed      => 1331,
    country_region => "Mainland China",
    deaths         => 5,
    last_update    => "2020-02-19T10:23:02",
    province_state => "Guangdong",
    recovered      => 606,
  },
  {
    confirmed      => 1262,
    country_region => "Mainland China",
    deaths         => 19,
    last_update    => "2020-02-19T12:13:08",
    province_state => "Henan",
    recovered      => 573,
  },
  {
    confirmed      => 1174,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-19T11:33:02",
    province_state => "Zhejiang",
    recovered      => 604,
  },
  {
    confirmed      => 1008,
    country_region => "Mainland China",
    deaths         => 4,
    last_update    => "2020-02-19T11:33:02",
    province_state => "Hunan",
    recovered      => 561,
  },
  {
    confirmed      => 986,
    country_region => "Mainland China",
    deaths         => 6,
    last_update    => "2020-02-19T14:13:03",
    province_state => "Anhui",
    recovered      => 413,
  },
  {
    confirmed      => 934,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-19T01:23:07",
    province_state => "Jiangxi",
    recovered      => 362,
  },
  {
    confirmed      => 631,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-19T12:13:08",
    province_state => "Jiangsu",
    recovered      => 318,
  },
  {
    confirmed      => 621,
    country_region => "Others",
    deaths         => 0,
    last_update    => "2020-02-19T20:33:02",
    province_state => "Diamond Princess cruise ship",
    recovered      => 1,
  },
  {
    confirmed      => 560,
    country_region => "Mainland China",
    deaths         => 5,
    last_update    => "2020-02-19T23:23:02",
    province_state => "Chongqing",
    recovered      => 274,
  },
  {
    confirmed      => 544,
    country_region => "Mainland China",
    deaths         => 3,
    last_update    => "2020-02-19T12:03:07",
    province_state => "Shandong",
    recovered      => 231,
  },
  {
    confirmed      => 514,
    country_region => "Mainland China",
    deaths         => 3,
    last_update    => "2020-02-19T13:53:02",
    province_state => "Sichuan",
    recovered      => 188,
  },
  {
    confirmed      => 470,
    country_region => "Mainland China",
    deaths         => 12,
    last_update    => "2020-02-19T11:03:08",
    province_state => "Heilongjiang",
    recovered      => 120,
  },
  {
    confirmed      => 393,
    country_region => "Mainland China",
    deaths         => 4,
    last_update    => "2020-02-19T04:53:02",
    province_state => "Beijing",
    recovered      => 145,
  },
  {
    confirmed      => 333,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-19T04:43:02",
    province_state => "Shanghai",
    recovered      => 186,
  },
  {
    confirmed      => 306,
    country_region => "Mainland China",
    deaths         => 4,
    last_update    => "2020-02-19T13:23:02",
    province_state => "Hebei",
    recovered      => 152,
  },
  {
    confirmed      => 293,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-19T11:53:02",
    province_state => "Fujian",
    recovered      => 112,
  },
  {
    confirmed      => 244,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-19T09:13:12",
    province_state => "Guangxi",
    recovered      => 86,
  },
  {
    confirmed      => 242,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-19T10:23:02",
    province_state => "Shaanxi",
    recovered      => 102,
  },
  {
    confirmed      => 172,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-19T23:33:02",
    province_state => "Yunnan",
    recovered      => 60,
  },
  {
    confirmed      => 168,
    country_region => "Mainland China",
    deaths         => 4,
    last_update    => "2020-02-19T23:43:02",
    province_state => "Hainan",
    recovered      => 84,
  },
  {
    confirmed      => 146,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-19T10:53:02",
    province_state => "Guizhou",
    recovered      => 70,
  },
  {
    confirmed      => 131,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-19T23:53:02",
    province_state => "Shanxi",
    recovered      => 68,
  },
  {
    confirmed      => 130,
    country_region => "Mainland China",
    deaths         => 3,
    last_update    => "2020-02-19T13:03:03",
    province_state => "Tianjin",
    recovered      => 54,
  },
  {
    confirmed      => 121,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-19T01:23:07",
    province_state => "Liaoning",
    recovered      => 55,
  },
  {
    confirmed      => 91,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-19T13:53:02",
    province_state => "Gansu",
    recovered      => 65,
  },
  {
    confirmed      => 90,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-19T06:03:08",
    province_state => "Jilin",
    recovered      => 37,
  },
  {
    confirmed      => 84,
    country_region => "Japan",
    deaths         => 1,
    last_update    => "2020-02-19T20:33:02",
    province_state => "",
    recovered      => 18,
  },
  {
    confirmed      => 84,
    country_region => "Singapore",
    deaths         => 0,
    last_update    => "2020-02-19T22:13:08",
    province_state => "",
    recovered      => 34,
  },
  {
    confirmed      => 76,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-19T07:03:07",
    province_state => "Xinjiang",
    recovered      => 20,
  },
  {
    confirmed      => 75,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-19T11:03:08",
    province_state => "Inner Mongolia",
    recovered      => 10,
  },
  {
    confirmed      => 71,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-19T01:53:02",
    province_state => "Ningxia",
    recovered      => 42,
  },
  {
    confirmed      => 63,
    country_region => "Hong Kong",
    deaths         => 2,
    last_update    => "2020-02-19T12:13:08",
    province_state => "Hong Kong",
    recovered      => 5,
  },
  {
    confirmed      => 35,
    country_region => "Thailand",
    deaths         => 0,
    last_update    => "2020-02-17T07:33:02",
    province_state => "",
    recovered      => 15,
  },
  {
    confirmed      => 31,
    country_region => "South Korea",
    deaths         => 0,
    last_update    => "2020-02-18T03:43:02",
    province_state => "",
    recovered      => 12,
  },
  {
    confirmed      => 23,
    country_region => "Taiwan",
    deaths         => 1,
    last_update    => "2020-02-19T07:53:02",
    province_state => "Taiwan",
    recovered      => 2,
  },
  {
    confirmed      => 22,
    country_region => "Malaysia",
    deaths         => 0,
    last_update    => "2020-02-19T09:33:03",
    province_state => "",
    recovered      => 15,
  },
  {
    confirmed      => 18,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-19T04:53:02",
    province_state => "Qinghai",
    recovered      => 16,
  },
  {
    confirmed      => 16,
    country_region => "Germany",
    deaths         => 0,
    last_update    => "2020-02-18T17:03:03",
    province_state => "",
    recovered      => 12,
  },
  {
    confirmed      => 16,
    country_region => "Vietnam",
    deaths         => 0,
    last_update    => "2020-02-13T06:33:02",
    province_state => "",
    recovered      => 7,
  },
  {
    confirmed      => 12,
    country_region => "France",
    deaths         => 1,
    last_update    => "2020-02-15T20:53:02",
    province_state => "",
    recovered      => 4,
  },
  {
    confirmed      => 10,
    country_region => "Macau",
    deaths         => 0,
    last_update    => "2020-02-16T12:03:06",
    province_state => "Macau",
    recovered      => 5,
  },
  {
    confirmed      => 9,
    country_region => "UK",
    deaths         => 0,
    last_update    => "2020-02-16T16:23:06",
    province_state => "",
    recovered      => 8,
  },
  {
    confirmed      => 9,
    country_region => "United Arab Emirates",
    deaths         => 0,
    last_update    => "2020-02-16T20:43:02",
    province_state => "",
    recovered      => 4,
  },
  {
    confirmed      => 5,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-09T19:33:02",
    province_state => "Queensland",
    recovered      => 0,
  },
  {
    confirmed      => 5,
    country_region => "Canada",
    deaths         => 0,
    last_update    => "2020-02-17T08:03:07",
    province_state => "British Columbia",
    recovered      => 0,
  },
  {
    confirmed      => 4,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-13T17:53:03",
    province_state => "New South Wales",
    recovered      => 4,
  },
  {
    confirmed      => 4,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-13T17:53:03",
    province_state => "Victoria",
    recovered      => 4,
  },
  {
    confirmed      => 3,
    country_region => "India",
    deaths         => 0,
    last_update    => "2020-02-16T07:43:02",
    province_state => "",
    recovered      => 3,
  },
  {
    confirmed      => 3,
    country_region => "Italy",
    deaths         => 0,
    last_update    => "2020-02-07T17:53:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 3,
    country_region => "Philippines",
    deaths         => 1,
    last_update    => "2020-02-12T07:43:02",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 2,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-17T08:13:09",
    province_state => "South Australia",
    recovered      => 2,
  },
  {
    confirmed      => 2,
    country_region => "Canada",
    deaths         => 0,
    last_update    => "2020-02-04T00:13:06",
    province_state => "Toronto, ON",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "Iran",
    deaths         => 2,
    last_update    => "2020-02-19T23:43:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "Russia",
    deaths         => 0,
    last_update    => "2020-02-12T14:43:03",
    province_state => "",
    recovered      => 2,
  },
  {
    confirmed      => 2,
    country_region => "Spain",
    deaths         => 0,
    last_update    => "2020-02-15T17:23:04",
    province_state => "",
    recovered      => 2,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-09T19:03:03",
    province_state => "Chicago, IL",
    recovered      => 2,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-03T03:53:02",
    province_state => "San Benito, CA",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-13T03:13:08",
    province_state => "San Diego County, CA",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-03T00:43:02",
    province_state => "Santa Clara, CA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Belgium",
    deaths         => 0,
    last_update    => "2020-02-17T04:23:06",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Cambodia",
    deaths         => 0,
    last_update    => "2020-02-12T07:43:02",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Canada",
    deaths         => 0,
    last_update    => "2020-02-12T18:53:03",
    province_state => "London, ON",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Egypt",
    deaths         => 0,
    last_update    => "2020-02-14T23:53:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Finland",
    deaths         => 0,
    last_update    => "2020-02-12T00:03:12",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-12T06:43:02",
    province_state => "Tibet",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Nepal",
    deaths         => 0,
    last_update    => "2020-02-12T14:43:03",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Sri Lanka",
    deaths         => 0,
    last_update    => "2020-02-08T03:43:03",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Sweden",
    deaths         => 0,
    last_update    => "2020-02-01T02:13:26",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:43:03",
    province_state => "Boston, MA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:53:03",
    province_state => "Los Angeles, CA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-05T21:53:02",
    province_state => "Madison, WI",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:53:03",
    province_state => "Orange, CA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-13T18:53:02",
    province_state => "San Antonio, TX",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-09T07:03:04",
    province_state => "Seattle, WA",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:43:03",
    province_state => "Tempe, AZ",
    recovered      => 0,
  },
]