[
  {
    confirmed      => 16678,
    country_region => "Mainland China",
    deaths         => 479,
    last_update    => "2020-02-04T23:43:01",
    province_state => "Hubei",
    recovered      => 522,
  },
  {
    confirmed      => 829,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-04T13:03:07",
    province_state => "Zhejiang",
    recovered      => 62,
  },
  {
    confirmed      => 813,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-04T13:03:07",
    province_state => "Guangdong",
    recovered      => 30,
  },
  {
    confirmed      => 675,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-04T11:53:02",
    province_state => "Henan",
    recovered      => 27,
  },
  {
    confirmed      => 593,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-04T14:03:03",
    province_state => "Hunan",
    recovered      => 31,
  },
  {
    confirmed      => 480,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-04T05:33:01",
    province_state => "Anhui",
    recovered      => 20,
  },
  {
    confirmed      => 476,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-04T14:43:02",
    province_state => "Jiangxi",
    recovered      => 20,
  },
  {
    confirmed      => 366,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-04T23:43:01",
    province_state => "Chongqing",
    recovered      => 9,
  },
  {
    confirmed      => 308,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-04T11:53:02",
    province_state => "Jiangsu",
    recovered      => 12,
  },
  {
    confirmed      => 282,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-04T01:43:02",
    province_state => "Sichuan",
    recovered      => 14,
  },
  {
    confirmed      => 275,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-04T12:03:04",
    province_state => "Shandong",
    recovered      => 11,
  },
  {
    confirmed      => 228,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-04T08:33:01",
    province_state => "Beijing",
    recovered      => 23,
  },
  {
    confirmed      => 219,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-04T06:33:02",
    province_state => "Shanghai",
    recovered      => 12,
  },
  {
    confirmed      => 194,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-04T12:13:11",
    province_state => "Fujian",
    recovered      => 3,
  },
  {
    confirmed      => 155,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-04T07:43:01",
    province_state => "Heilongjiang",
    recovered      => 4,
  },
  {
    confirmed      => 142,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-04T12:33:02",
    province_state => "Shaanxi",
    recovered      => 2,
  },
  {
    confirmed      => 139,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-04T05:53:01",
    province_state => "Guangxi",
    recovered      => 10,
  },
  {
    confirmed      => 126,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-04T08:53:01",
    province_state => "Hebei",
    recovered      => 4,
  },
  {
    confirmed      => 122,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-04T23:23:02",
    province_state => "Yunnan",
    recovered      => 5,
  },
  {
    confirmed      => 81,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-04T14:13:08",
    province_state => "Liaoning",
    recovered      => 2,
  },
  {
    confirmed      => 81,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-04T23:23:02",
    province_state => "Shanxi",
    recovered      => 4,
  },
  {
    confirmed      => 80,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-04T11:33:03",
    province_state => "Hainan",
    recovered      => 5,
  },
  {
    confirmed      => 67,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-04T13:33:02",
    province_state => "Tianjin",
    recovered      => 2,
  },
  {
    confirmed      => 58,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-04T10:43:02",
    province_state => "Guizhou",
    recovered      => 2,
  },
  {
    confirmed      => 57,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-04T15:43:02",
    province_state => "Gansu",
    recovered      => 4,
  },
  {
    confirmed      => 42,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-04T00:23:05",
    province_state => "Jilin",
    recovered      => 1,
  },
  {
    confirmed      => 35,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-04T03:03:07",
    province_state => "Inner Mongolia",
    recovered      => 1,
  },
  {
    confirmed      => 34,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-04T02:13:18",
    province_state => "Ningxia",
    recovered      => 1,
  },
  {
    confirmed      => 29,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-04T01:33:01",
    province_state => "Xinjiang",
    recovered      => 0,
  },
  {
    confirmed      => 25,
    country_region => "Thailand",
    deaths         => 0,
    last_update    => "2020-02-04T15:33:03",
    province_state => "",
    recovered      => 5,
  },
  {
    confirmed      => 24,
    country_region => "Singapore",
    deaths         => 0,
    last_update    => "2020-02-04T15:33:03",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 22,
    country_region => "Japan",
    deaths         => 0,
    last_update    => "2020-02-04T16:43:03",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 17,
    country_region => "Hong Kong",
    deaths         => 1,
    last_update    => "2020-02-04T09:03:02",
    province_state => "Hong Kong",
    recovered      => 0,
  },
  {
    confirmed      => 16,
    country_region => "South Korea",
    deaths         => 0,
    last_update    => "2020-02-04T15:33:03",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 15,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-04T01:33:01",
    province_state => "Qinghai",
    recovered      => 0,
  },
  {
    confirmed      => 12,
    country_region => "Germany",
    deaths         => 0,
    last_update    => "2020-02-03T20:53:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 11,
    country_region => "Taiwan",
    deaths         => 0,
    last_update    => "2020-02-04T14:53:02",
    province_state => "Taiwan",
    recovered      => 0,
  },
  {
    confirmed      => 10,
    country_region => "Macau",
    deaths         => 0,
    last_update    => "2020-02-04T04:43:02",
    province_state => "Macau",
    recovered      => 0,
  },
  {
    confirmed      => 10,
    country_region => "Malaysia",
    deaths         => 0,
    last_update    => "2020-02-04T07:33:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 8,
    country_region => "Vietnam",
    deaths         => 0,
    last_update    => "2020-02-03T21:43:02",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 6,
    country_region => "France",
    deaths         => 0,
    last_update    => "2020-02-01T01:52:40",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 5,
    country_region => "United Arab Emirates",
    deaths         => 0,
    last_update    => "2020-02-02T05:43:01",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 4,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-01T18:12:49",
    province_state => "New South Wales",
    recovered      => 2,
  },
  {
    confirmed      => 4,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-01T18:12:49",
    province_state => "Victoria",
    recovered      => 0,
  },
  {
    confirmed      => 3,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-04T16:53:03",
    province_state => "Queensland",
    recovered      => 0,
  },
  {
    confirmed      => 3,
    country_region => "India",
    deaths         => 0,
    last_update    => "2020-02-03T21:43:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-02T22:33:07",
    province_state => "South Australia",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "Canada",
    deaths         => 0,
    last_update    => "2020-02-04T00:13:06",
    province_state => "Toronto, ON",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "Italy",
    deaths         => 0,
    last_update    => "2020-01-31T08:15:53",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "Philippines",
    deaths         => 1,
    last_update    => "2020-02-02T03:33:07",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "Russia",
    deaths         => 0,
    last_update    => "2020-01-31T16:13:45",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "UK",
    deaths         => 0,
    last_update    => "2020-02-01T01:52:40",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:43:03",
    province_state => "Chicago, IL",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-03T03:53:02",
    province_state => "San Benito, CA",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-03T00:43:02",
    province_state => "Santa Clara, CA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Belgium",
    deaths         => 0,
    last_update    => "2020-02-04T15:43:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Cambodia",
    deaths         => 0,
    last_update    => "2020-01-31T08:15:53",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Canada",
    deaths         => 0,
    last_update    => "2020-02-01T18:12:49",
    province_state => "British Columbia",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Canada",
    deaths         => 0,
    last_update    => "2020-02-04T00:03:11",
    province_state => "London, ON",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Finland",
    deaths         => 0,
    last_update    => "2020-01-31T08:15:53",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-01T01:52:40",
    province_state => "Tibet",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Nepal",
    deaths         => 0,
    last_update    => "2020-01-31T08:15:53",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Spain",
    deaths         => 0,
    last_update    => "2020-02-01T23:43:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Sri Lanka",
    deaths         => 0,
    last_update    => "2020-01-31T08:15:53",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Sweden",
    deaths         => 0,
    last_update    => "2020-02-01T02:13:26",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:43:03",
    province_state => "Boston, MA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:53:03",
    province_state => "Los Angeles, CA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:53:03",
    province_state => "Orange, CA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:43:03",
    province_state => "Seattle, WA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:43:03",
    province_state => "Tempe, AZ",
    recovered      => 0,
  },
]