[
  {
    confirmed      => 58182,
    country_region => "Mainland China",
    deaths         => 1696,
    last_update    => "2020-02-16T23:53:01",
    province_state => "Hubei",
    recovered      => 6639,
  },
  {
    confirmed      => 1316,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-16T12:03:06",
    province_state => "Guangdong",
    recovered      => 465,
  },
  {
    confirmed      => 1231,
    country_region => "Mainland China",
    deaths         => 13,
    last_update    => "2020-02-16T13:53:03",
    province_state => "Henan",
    recovered      => 440,
  },
  {
    confirmed      => 1167,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-16T09:33:02",
    province_state => "Zhejiang",
    recovered      => 456,
  },
  {
    confirmed      => 1004,
    country_region => "Mainland China",
    deaths         => 3,
    last_update    => "2020-02-16T13:13:04",
    province_state => "Hunan",
    recovered      => 464,
  },
  {
    confirmed      => 962,
    country_region => "Mainland China",
    deaths         => 6,
    last_update    => "2020-02-16T08:33:02",
    province_state => "Anhui",
    recovered      => 255,
  },
  {
    confirmed      => 925,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-16T10:03:06",
    province_state => "Jiangxi",
    recovered      => 240,
  },
  {
    confirmed      => 617,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-16T09:33:02",
    province_state => "Jiangsu",
    recovered      => 218,
  },
  {
    confirmed      => 551,
    country_region => "Mainland China",
    deaths         => 5,
    last_update    => "2020-02-16T23:53:01",
    province_state => "Chongqing",
    recovered      => 207,
  },
  {
    confirmed      => 537,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-16T12:03:06",
    province_state => "Shandong",
    recovered      => 173,
  },
  {
    confirmed      => 481,
    country_region => "Mainland China",
    deaths         => 3,
    last_update    => "2020-02-16T10:03:06",
    province_state => "Sichuan",
    recovered      => 131,
  },
  {
    confirmed      => 445,
    country_region => "Mainland China",
    deaths         => 11,
    last_update    => "2020-02-16T13:53:03",
    province_state => "Heilongjiang",
    recovered      => 79,
  },
  {
    confirmed      => 380,
    country_region => "Mainland China",
    deaths         => 4,
    last_update    => "2020-02-16T10:03:06",
    province_state => "Beijing",
    recovered      => 108,
  },
  {
    confirmed      => 355,
    country_region => "Others",
    deaths         => 0,
    last_update    => "2020-02-16T03:43:02",
    province_state => "Diamond Princess cruise ship",
    recovered      => 0,
  },
  {
    confirmed      => 328,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-16T02:53:02",
    province_state => "Shanghai",
    recovered      => 140,
  },
  {
    confirmed      => 300,
    country_region => "Mainland China",
    deaths         => 3,
    last_update    => "2020-02-16T12:03:06",
    province_state => "Hebei",
    recovered      => 105,
  },
  {
    confirmed      => 287,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-16T12:03:06",
    province_state => "Fujian",
    recovered      => 82,
  },
  {
    confirmed      => 237,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-16T12:03:06",
    province_state => "Guangxi",
    recovered      => 49,
  },
  {
    confirmed      => 236,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-16T13:53:03",
    province_state => "Shaanxi",
    recovered      => 71,
  },
  {
    confirmed      => 171,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-16T09:53:01",
    province_state => "Yunnan",
    recovered      => 42,
  },
  {
    confirmed      => 162,
    country_region => "Mainland China",
    deaths         => 4,
    last_update    => "2020-02-16T12:03:06",
    province_state => "Hainan",
    recovered      => 52,
  },
  {
    confirmed      => 144,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-16T09:13:09",
    province_state => "Guizhou",
    recovered      => 46,
  },
  {
    confirmed      => 129,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-16T23:53:01",
    province_state => "Shanxi",
    recovered      => 50,
  },
  {
    confirmed      => 124,
    country_region => "Mainland China",
    deaths         => 3,
    last_update    => "2020-02-16T12:23:02",
    province_state => "Tianjin",
    recovered      => 45,
  },
  {
    confirmed      => 121,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-16T12:03:06",
    province_state => "Liaoning",
    recovered      => 40,
  },
  {
    confirmed      => 90,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-16T13:53:03",
    province_state => "Gansu",
    recovered      => 54,
  },
  {
    confirmed      => 89,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-16T10:03:06",
    province_state => "Jilin",
    recovered      => 30,
  },
  {
    confirmed      => 75,
    country_region => "Singapore",
    deaths         => 0,
    last_update    => "2020-02-16T16:23:06",
    province_state => "",
    recovered      => 18,
  },
  {
    confirmed      => 71,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-16T08:33:02",
    province_state => "Xinjiang",
    recovered      => 12,
  },
  {
    confirmed      => 70,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-16T08:33:02",
    province_state => "Inner Mongolia",
    recovered      => 8,
  },
  {
    confirmed      => 70,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-15T08:43:03",
    province_state => "Ningxia",
    recovered      => 33,
  },
  {
    confirmed      => 59,
    country_region => "Japan",
    deaths         => 1,
    last_update    => "2020-02-16T17:43:03",
    province_state => "",
    recovered      => 12,
  },
  {
    confirmed      => 57,
    country_region => "Hong Kong",
    deaths         => 1,
    last_update    => "2020-02-16T09:53:01",
    province_state => "Hong Kong",
    recovered      => 2,
  },
  {
    confirmed      => 34,
    country_region => "Thailand",
    deaths         => 0,
    last_update    => "2020-02-16T18:03:02",
    province_state => "",
    recovered      => 14,
  },
  {
    confirmed      => 29,
    country_region => "South Korea",
    deaths         => 0,
    last_update    => "2020-02-16T01:33:02",
    province_state => "",
    recovered      => 9,
  },
  {
    confirmed      => 22,
    country_region => "Malaysia",
    deaths         => 0,
    last_update    => "2020-02-15T23:43:02",
    province_state => "",
    recovered      => 7,
  },
  {
    confirmed      => 20,
    country_region => "Taiwan",
    deaths         => 1,
    last_update    => "2020-02-16T11:23:06",
    province_state => "Taiwan",
    recovered      => 2,
  },
  {
    confirmed      => 18,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-15T08:43:03",
    province_state => "Qinghai",
    recovered      => 13,
  },
  {
    confirmed      => 16,
    country_region => "Germany",
    deaths         => 0,
    last_update    => "2020-02-13T15:13:11",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 16,
    country_region => "Vietnam",
    deaths         => 0,
    last_update    => "2020-02-13T06:33:02",
    province_state => "",
    recovered      => 7,
  },
  {
    confirmed      => 12,
    country_region => "France",
    deaths         => 1,
    last_update    => "2020-02-15T20:53:02",
    province_state => "",
    recovered      => 4,
  },
  {
    confirmed      => 10,
    country_region => "Macau",
    deaths         => 0,
    last_update    => "2020-02-16T12:03:06",
    province_state => "Macau",
    recovered      => 5,
  },
  {
    confirmed      => 9,
    country_region => "UK",
    deaths         => 0,
    last_update    => "2020-02-16T16:23:06",
    province_state => "",
    recovered      => 8,
  },
  {
    confirmed      => 9,
    country_region => "United Arab Emirates",
    deaths         => 0,
    last_update    => "2020-02-16T20:43:02",
    province_state => "",
    recovered      => 4,
  },
  {
    confirmed      => 5,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-09T19:33:02",
    province_state => "Queensland",
    recovered      => 0,
  },
  {
    confirmed      => 4,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-13T17:53:03",
    province_state => "New South Wales",
    recovered      => 4,
  },
  {
    confirmed      => 4,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-13T17:53:03",
    province_state => "Victoria",
    recovered      => 4,
  },
  {
    confirmed      => 4,
    country_region => "Canada",
    deaths         => 0,
    last_update    => "2020-02-07T05:43:03",
    province_state => "British Columbia",
    recovered      => 0,
  },
  {
    confirmed      => 3,
    country_region => "India",
    deaths         => 0,
    last_update    => "2020-02-16T07:43:02",
    province_state => "",
    recovered      => 3,
  },
  {
    confirmed      => 3,
    country_region => "Italy",
    deaths         => 0,
    last_update    => "2020-02-07T17:53:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 3,
    country_region => "Philippines",
    deaths         => 1,
    last_update    => "2020-02-12T07:43:02",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 2,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-02T22:33:07",
    province_state => "South Australia",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "Canada",
    deaths         => 0,
    last_update    => "2020-02-04T00:13:06",
    province_state => "Toronto, ON",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "Russia",
    deaths         => 0,
    last_update    => "2020-02-12T14:43:03",
    province_state => "",
    recovered      => 2,
  },
  {
    confirmed      => 2,
    country_region => "Spain",
    deaths         => 0,
    last_update    => "2020-02-15T17:23:04",
    province_state => "",
    recovered      => 2,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-09T19:03:03",
    province_state => "Chicago, IL",
    recovered      => 2,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-03T03:53:02",
    province_state => "San Benito, CA",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-13T03:13:08",
    province_state => "San Diego County, CA",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-03T00:43:02",
    province_state => "Santa Clara, CA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Belgium",
    deaths         => 0,
    last_update    => "2020-02-04T15:43:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Cambodia",
    deaths         => 0,
    last_update    => "2020-02-12T07:43:02",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Canada",
    deaths         => 0,
    last_update    => "2020-02-12T18:53:03",
    province_state => "London, ON",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Egypt",
    deaths         => 0,
    last_update    => "2020-02-14T23:53:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Finland",
    deaths         => 0,
    last_update    => "2020-02-12T00:03:12",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-12T06:43:02",
    province_state => "Tibet",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Nepal",
    deaths         => 0,
    last_update    => "2020-02-12T14:43:03",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Sri Lanka",
    deaths         => 0,
    last_update    => "2020-02-08T03:43:03",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Sweden",
    deaths         => 0,
    last_update    => "2020-02-01T02:13:26",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:43:03",
    province_state => "Boston, MA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:53:03",
    province_state => "Los Angeles, CA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-05T21:53:02",
    province_state => "Madison, WI",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:53:03",
    province_state => "Orange, CA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-13T18:53:02",
    province_state => "San Antonio, TX",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-09T07:03:04",
    province_state => "Seattle, WA",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:43:03",
    province_state => "Tempe, AZ",
    recovered      => 0,
  },
]