[
  {
    confirmed      => 56249,
    country_region => "Mainland China",
    deaths         => 1596,
    last_update    => "2020-02-15T23:13:05",
    province_state => "Hubei",
    recovered      => 5623,
  },
  {
    confirmed      => 1294,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-15T14:03:04",
    province_state => "Guangdong",
    recovered      => 410,
  },
  {
    confirmed      => 1212,
    country_region => "Mainland China",
    deaths         => 13,
    last_update    => "2020-02-15T12:13:08",
    province_state => "Henan",
    recovered      => 391,
  },
  {
    confirmed      => 1162,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-15T11:23:17",
    province_state => "Zhejiang",
    recovered      => 428,
  },
  {
    confirmed      => 1001,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-15T13:03:04",
    province_state => "Hunan",
    recovered      => 425,
  },
  {
    confirmed      => 950,
    country_region => "Mainland China",
    deaths         => 6,
    last_update    => "2020-02-15T12:13:08",
    province_state => "Anhui",
    recovered      => 221,
  },
  {
    confirmed      => 913,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-15T01:33:02",
    province_state => "Jiangxi",
    recovered      => 210,
  },
  {
    confirmed      => 604,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-15T12:13:08",
    province_state => "Jiangsu",
    recovered      => 186,
  },
  {
    confirmed      => 544,
    country_region => "Mainland China",
    deaths         => 5,
    last_update    => "2020-02-15T23:23:07",
    province_state => "Chongqing",
    recovered      => 184,
  },
  {
    confirmed      => 532,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-15T11:23:17",
    province_state => "Shandong",
    recovered      => 156,
  },
  {
    confirmed      => 470,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-15T08:43:03",
    province_state => "Sichuan",
    recovered      => 119,
  },
  {
    confirmed      => 425,
    country_region => "Mainland China",
    deaths         => 11,
    last_update    => "2020-02-15T11:43:01",
    province_state => "Heilongjiang",
    recovered      => 68,
  },
  {
    confirmed      => 375,
    country_region => "Mainland China",
    deaths         => 4,
    last_update    => "2020-02-15T09:53:01",
    province_state => "Beijing",
    recovered      => 98,
  },
  {
    confirmed      => 326,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-15T03:13:06",
    province_state => "Shanghai",
    recovered      => 124,
  },
  {
    confirmed      => 291,
    country_region => "Mainland China",
    deaths         => 3,
    last_update    => "2020-02-15T13:03:04",
    province_state => "Hebei",
    recovered      => 101,
  },
  {
    confirmed      => 285,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-15T13:03:04",
    province_state => "Fujian",
    recovered      => 71,
  },
  {
    confirmed      => 285,
    country_region => "Others",
    deaths         => 0,
    last_update    => "2020-02-15T17:03:04",
    province_state => "Diamond Princess cruise ship",
    recovered      => 0,
  },
  {
    confirmed      => 235,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-15T06:33:01",
    province_state => "Guangxi",
    recovered      => 44,
  },
  {
    confirmed      => 232,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-15T12:13:08",
    province_state => "Shaanxi",
    recovered      => 60,
  },
  {
    confirmed      => 168,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-15T06:33:01",
    province_state => "Yunnan",
    recovered      => 42,
  },
  {
    confirmed      => 162,
    country_region => "Mainland China",
    deaths         => 4,
    last_update    => "2020-02-15T11:23:17",
    province_state => "Hainan",
    recovered      => 39,
  },
  {
    confirmed      => 143,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-15T14:53:04",
    province_state => "Guizhou",
    recovered      => 41,
  },
  {
    confirmed      => 128,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-15T23:13:05",
    province_state => "Shanxi",
    recovered      => 46,
  },
  {
    confirmed      => 122,
    country_region => "Mainland China",
    deaths         => 3,
    last_update    => "2020-02-15T13:43:01",
    province_state => "Tianjin",
    recovered      => 37,
  },
  {
    confirmed      => 119,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-15T09:53:01",
    province_state => "Liaoning",
    recovered      => 31,
  },
  {
    confirmed      => 90,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-15T12:13:08",
    province_state => "Gansu",
    recovered      => 49,
  },
  {
    confirmed      => 88,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-15T12:13:08",
    province_state => "Jilin",
    recovered      => 26,
  },
  {
    confirmed      => 72,
    country_region => "Singapore",
    deaths         => 0,
    last_update    => "2020-02-15T23:53:02",
    province_state => "",
    recovered      => 18,
  },
  {
    confirmed      => 70,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-15T08:43:03",
    province_state => "Ningxia",
    recovered      => 33,
  },
  {
    confirmed      => 70,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-15T09:53:01",
    province_state => "Xinjiang",
    recovered      => 10,
  },
  {
    confirmed      => 68,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-15T14:03:04",
    province_state => "Inner Mongolia",
    recovered      => 7,
  },
  {
    confirmed      => 56,
    country_region => "Hong Kong",
    deaths         => 1,
    last_update    => "2020-02-14T09:03:12",
    province_state => "Hong Kong",
    recovered      => 1,
  },
  {
    confirmed      => 43,
    country_region => "Japan",
    deaths         => 1,
    last_update    => "2020-02-15T17:43:06",
    province_state => "",
    recovered      => 12,
  },
  {
    confirmed      => 33,
    country_region => "Thailand",
    deaths         => 0,
    last_update    => "2020-02-13T17:53:03",
    province_state => "",
    recovered      => 12,
  },
  {
    confirmed      => 28,
    country_region => "South Korea",
    deaths         => 0,
    last_update    => "2020-02-15T23:33:02",
    province_state => "",
    recovered      => 9,
  },
  {
    confirmed      => 22,
    country_region => "Malaysia",
    deaths         => 0,
    last_update    => "2020-02-15T23:43:02",
    province_state => "",
    recovered      => 7,
  },
  {
    confirmed      => 18,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-15T08:43:03",
    province_state => "Qinghai",
    recovered      => 13,
  },
  {
    confirmed      => 18,
    country_region => "Taiwan",
    deaths         => 0,
    last_update    => "2020-02-15T03:43:02",
    province_state => "Taiwan",
    recovered      => 2,
  },
  {
    confirmed      => 16,
    country_region => "Germany",
    deaths         => 0,
    last_update    => "2020-02-13T15:13:11",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 16,
    country_region => "Vietnam",
    deaths         => 0,
    last_update    => "2020-02-13T06:33:02",
    province_state => "",
    recovered      => 7,
  },
  {
    confirmed      => 12,
    country_region => "France",
    deaths         => 1,
    last_update    => "2020-02-15T20:53:02",
    province_state => "",
    recovered      => 4,
  },
  {
    confirmed      => 10,
    country_region => "Macau",
    deaths         => 0,
    last_update    => "2020-02-13T14:13:06",
    province_state => "Macau",
    recovered      => 3,
  },
  {
    confirmed      => 9,
    country_region => "UK",
    deaths         => 0,
    last_update    => "2020-02-12T19:03:06",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 8,
    country_region => "United Arab Emirates",
    deaths         => 0,
    last_update    => "2020-02-15T06:03:03",
    province_state => "",
    recovered      => 3,
  },
  {
    confirmed      => 5,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-09T19:33:02",
    province_state => "Queensland",
    recovered      => 0,
  },
  {
    confirmed      => 4,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-13T17:53:03",
    province_state => "New South Wales",
    recovered      => 4,
  },
  {
    confirmed      => 4,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-13T17:53:03",
    province_state => "Victoria",
    recovered      => 4,
  },
  {
    confirmed      => 4,
    country_region => "Canada",
    deaths         => 0,
    last_update    => "2020-02-07T05:43:03",
    province_state => "British Columbia",
    recovered      => 0,
  },
  {
    confirmed      => 3,
    country_region => "India",
    deaths         => 0,
    last_update    => "2020-02-13T18:53:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 3,
    country_region => "Italy",
    deaths         => 0,
    last_update    => "2020-02-07T17:53:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 3,
    country_region => "Philippines",
    deaths         => 1,
    last_update    => "2020-02-12T07:43:02",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 2,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-02T22:33:07",
    province_state => "South Australia",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "Canada",
    deaths         => 0,
    last_update    => "2020-02-04T00:13:06",
    province_state => "Toronto, ON",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "Russia",
    deaths         => 0,
    last_update    => "2020-02-12T14:43:03",
    province_state => "",
    recovered      => 2,
  },
  {
    confirmed      => 2,
    country_region => "Spain",
    deaths         => 0,
    last_update    => "2020-02-15T17:23:04",
    province_state => "",
    recovered      => 2,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-09T19:03:03",
    province_state => "Chicago, IL",
    recovered      => 2,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-03T03:53:02",
    province_state => "San Benito, CA",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-13T03:13:08",
    province_state => "San Diego County, CA",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-03T00:43:02",
    province_state => "Santa Clara, CA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Belgium",
    deaths         => 0,
    last_update    => "2020-02-04T15:43:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Cambodia",
    deaths         => 0,
    last_update    => "2020-02-12T07:43:02",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Canada",
    deaths         => 0,
    last_update    => "2020-02-12T18:53:03",
    province_state => "London, ON",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Egypt",
    deaths         => 0,
    last_update    => "2020-02-14T23:53:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Finland",
    deaths         => 0,
    last_update    => "2020-02-12T00:03:12",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-12T06:43:02",
    province_state => "Tibet",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Nepal",
    deaths         => 0,
    last_update    => "2020-02-12T14:43:03",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Sri Lanka",
    deaths         => 0,
    last_update    => "2020-02-08T03:43:03",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Sweden",
    deaths         => 0,
    last_update    => "2020-02-01T02:13:26",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:43:03",
    province_state => "Boston, MA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:53:03",
    province_state => "Los Angeles, CA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-05T21:53:02",
    province_state => "Madison, WI",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:53:03",
    province_state => "Orange, CA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-13T18:53:02",
    province_state => "San Antonio, TX",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-09T07:03:04",
    province_state => "Seattle, WA",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:43:03",
    province_state => "Tempe, AZ",
    recovered      => 0,
  },
]