[
  {
    confirmed      => 64084,
    country_region => "Mainland China",
    deaths         => 2346,
    last_update    => "2020-02-22T23:33:06",
    province_state => "Hubei",
    recovered      => 15299,
  },
  {
    confirmed      => 1339,
    country_region => "Mainland China",
    deaths         => 5,
    last_update    => "2020-02-22T10:03:04",
    province_state => "Guangdong",
    recovered      => 728,
  },
  {
    confirmed      => 1270,
    country_region => "Mainland China",
    deaths         => 19,
    last_update    => "2020-02-22T14:13:38",
    province_state => "Henan",
    recovered      => 830,
  },
  {
    confirmed      => 1205,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-22T11:13:13",
    province_state => "Zhejiang",
    recovered      => 719,
  },
  {
    confirmed      => 1013,
    country_region => "Mainland China",
    deaths         => 4,
    last_update    => "2020-02-22T10:03:04",
    province_state => "Hunan",
    recovered      => 692,
  },
  {
    confirmed      => 989,
    country_region => "Mainland China",
    deaths         => 6,
    last_update    => "2020-02-22T07:43:03",
    province_state => "Anhui",
    recovered      => 597,
  },
  {
    confirmed      => 934,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-22T06:13:05",
    province_state => "Jiangxi",
    recovered      => 555,
  },
  {
    confirmed      => 750,
    country_region => "Mainland China",
    deaths         => 4,
    last_update    => "2020-02-22T09:43:02",
    province_state => "Shandong",
    recovered      => 302,
  },
  {
    confirmed      => 634,
    country_region => "Others",
    deaths         => 2,
    last_update    => "2020-02-20T15:53:03",
    province_state => "Diamond Princess cruise ship",
    recovered      => 1,
  },
  {
    confirmed      => 631,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-22T07:43:03",
    province_state => "Jiangsu",
    recovered      => 401,
  },
  {
    confirmed      => 573,
    country_region => "Mainland China",
    deaths         => 6,
    last_update    => "2020-02-22T23:23:05",
    province_state => "Chongqing",
    recovered      => 328,
  },
  {
    confirmed      => 526,
    country_region => "Mainland China",
    deaths         => 3,
    last_update    => "2020-02-22T13:03:03",
    province_state => "Sichuan",
    recovered      => 250,
  },
  {
    confirmed      => 479,
    country_region => "Mainland China",
    deaths         => 12,
    last_update    => "2020-02-22T11:13:13",
    province_state => "Heilongjiang",
    recovered      => 204,
  },
  {
    confirmed      => 433,
    country_region => "South Korea",
    deaths         => 2,
    last_update    => "2020-02-22T08:33:02",
    province_state => "",
    recovered      => 16,
  },
  {
    confirmed      => 399,
    country_region => "Mainland China",
    deaths         => 4,
    last_update    => "2020-02-22T02:23:05",
    province_state => "Beijing",
    recovered      => 178,
  },
  {
    confirmed      => 335,
    country_region => "Mainland China",
    deaths         => 3,
    last_update    => "2020-02-22T06:33:17",
    province_state => "Shanghai",
    recovered      => 227,
  },
  {
    confirmed      => 309,
    country_region => "Mainland China",
    deaths         => 6,
    last_update    => "2020-02-22T12:33:04",
    province_state => "Hebei",
    recovered      => 203,
  },
  {
    confirmed      => 293,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-22T14:03:04",
    province_state => "Fujian",
    recovered      => 162,
  },
  {
    confirmed      => 249,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-22T05:53:02",
    province_state => "Guangxi",
    recovered      => 104,
  },
  {
    confirmed      => 245,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-22T09:53:02",
    province_state => "Shaanxi",
    recovered      => 149,
  },
  {
    confirmed      => 174,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-22T04:43:02",
    province_state => "Yunnan",
    recovered      => 107,
  },
  {
    confirmed      => 168,
    country_region => "Mainland China",
    deaths         => 4,
    last_update    => "2020-02-22T09:53:02",
    province_state => "Hainan",
    recovered      => 104,
  },
  {
    confirmed      => 146,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-22T01:03:10",
    province_state => "Guizhou",
    recovered      => 90,
  },
  {
    confirmed      => 135,
    country_region => "Mainland China",
    deaths         => 3,
    last_update    => "2020-02-22T12:33:04",
    province_state => "Tianjin",
    recovered      => 65,
  },
  {
    confirmed      => 132,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-22T23:23:05",
    province_state => "Shanxi",
    recovered      => 81,
  },
  {
    confirmed      => 122,
    country_region => "Japan",
    deaths         => 1,
    last_update    => "2020-02-22T14:53:02",
    province_state => "",
    recovered      => 22,
  },
  {
    confirmed      => 121,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-22T02:23:05",
    province_state => "Liaoning",
    recovered      => 66,
  },
  {
    confirmed      => 91,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-21T15:13:07",
    province_state => "Gansu",
    recovered      => 76,
  },
  {
    confirmed      => 91,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-22T12:33:04",
    province_state => "Jilin",
    recovered      => 52,
  },
  {
    confirmed      => 85,
    country_region => "Singapore",
    deaths         => 0,
    last_update    => "2020-02-21T03:43:02",
    province_state => "",
    recovered      => 37,
  },
  {
    confirmed      => 76,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-22T11:13:14",
    province_state => "Xinjiang",
    recovered      => 25,
  },
  {
    confirmed      => 75,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-22T23:53:01",
    province_state => "Inner Mongolia",
    recovered      => 26,
  },
  {
    confirmed      => 71,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-21T06:23:04",
    province_state => "Ningxia",
    recovered      => 48,
  },
  {
    confirmed      => 69,
    country_region => "Hong Kong",
    deaths         => 2,
    last_update    => "2020-02-22T13:23:05",
    province_state => "Hong Kong",
    recovered      => 6,
  },
  {
    confirmed      => 62,
    country_region => "Italy",
    deaths         => 2,
    last_update    => "2020-02-22T23:43:02",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 35,
    country_region => "Thailand",
    deaths         => 0,
    last_update    => "2020-02-21T18:53:02",
    province_state => "",
    recovered      => 17,
  },
  {
    confirmed      => 28,
    country_region => "Iran",
    deaths         => 5,
    last_update    => "2020-02-22T10:03:05",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 26,
    country_region => "Taiwan",
    deaths         => 1,
    last_update    => "2020-02-21T06:53:03",
    province_state => "Taiwan",
    recovered      => 2,
  },
  {
    confirmed      => 22,
    country_region => "Malaysia",
    deaths         => 0,
    last_update    => "2020-02-19T09:33:03",
    province_state => "",
    recovered      => 15,
  },
  {
    confirmed      => 18,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-21T04:43:02",
    province_state => "Qinghai",
    recovered      => 18,
  },
  {
    confirmed      => 16,
    country_region => "Germany",
    deaths         => 0,
    last_update    => "2020-02-21T23:03:13",
    province_state => "",
    recovered      => 14,
  },
  {
    confirmed      => 16,
    country_region => "Vietnam",
    deaths         => 0,
    last_update    => "2020-02-21T06:03:04",
    province_state => "",
    recovered      => 14,
  },
  {
    confirmed      => 13,
    country_region => "United Arab Emirates",
    deaths         => 0,
    last_update    => "2020-02-22T14:53:02",
    province_state => "",
    recovered      => 4,
  },
  {
    confirmed      => 12,
    country_region => "France",
    deaths         => 1,
    last_update    => "2020-02-15T20:53:02",
    province_state => "",
    recovered      => 4,
  },
  {
    confirmed      => 11,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-22T23:03:09",
    province_state => "Omaha, NE (From Diamond Princess)",
    recovered      => 0,
  },
  {
    confirmed      => 10,
    country_region => "Macau",
    deaths         => 0,
    last_update    => "2020-02-20T02:13:19",
    province_state => "Macau",
    recovered      => 6,
  },
  {
    confirmed      => 9,
    country_region => "UK",
    deaths         => 0,
    last_update    => "2020-02-16T16:23:06",
    province_state => "",
    recovered      => 8,
  },
  {
    confirmed      => 7,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-22T17:03:05",
    province_state => "From Diamond Princess",
    recovered      => 0,
  },
  {
    confirmed      => 6,
    country_region => "Canada",
    deaths         => 0,
    last_update    => "2020-02-21T05:23:04",
    province_state => "British Columbia",
    recovered      => 0,
  },
  {
    confirmed      => 5,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-21T05:43:02",
    province_state => "Queensland",
    recovered      => 1,
  },
  {
    confirmed      => 5,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-22T17:13:24",
    province_state => "Travis, CA (From Diamond Princess)",
    recovered      => 0,
  },
  {
    confirmed      => 4,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-13T17:53:03",
    province_state => "New South Wales",
    recovered      => 4,
  },
  {
    confirmed      => 4,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-13T17:53:03",
    province_state => "Victoria",
    recovered      => 4,
  },
  {
    confirmed      => 3,
    country_region => "India",
    deaths         => 0,
    last_update    => "2020-02-16T07:43:02",
    province_state => "",
    recovered      => 3,
  },
  {
    confirmed      => 3,
    country_region => "Philippines",
    deaths         => 1,
    last_update    => "2020-02-12T07:43:02",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 2,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-17T08:13:09",
    province_state => "South Australia",
    recovered      => 2,
  },
  {
    confirmed      => 2,
    country_region => "Canada",
    deaths         => 0,
    last_update    => "2020-02-21T05:23:04",
    province_state => "Toronto, ON",
    recovered      => 2,
  },
  {
    confirmed      => 2,
    country_region => "Russia",
    deaths         => 0,
    last_update    => "2020-02-12T14:43:03",
    province_state => "",
    recovered      => 2,
  },
  {
    confirmed      => 2,
    country_region => "Spain",
    deaths         => 0,
    last_update    => "2020-02-15T17:23:04",
    province_state => "",
    recovered      => 2,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-09T19:03:03",
    province_state => "Chicago, IL",
    recovered      => 2,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-22T17:13:24",
    province_state => "Lackland, TX (From Diamond Princess)",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-03T03:53:02",
    province_state => "San Benito, CA",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-21T05:43:02",
    province_state => "San Diego County, CA",
    recovered      => 1,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-21T05:23:04",
    province_state => "Santa Clara, CA",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Belgium",
    deaths         => 0,
    last_update    => "2020-02-17T04:23:06",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Cambodia",
    deaths         => 0,
    last_update    => "2020-02-12T07:43:02",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Canada",
    deaths         => 0,
    last_update    => "2020-02-12T18:53:03",
    province_state => "London, ON",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Egypt",
    deaths         => 0,
    last_update    => "2020-02-21T18:53:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Finland",
    deaths         => 0,
    last_update    => "2020-02-12T00:03:12",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Israel",
    deaths         => 0,
    last_update    => "2020-02-22T20:53:02",
    province_state => "From Diamond Princess",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Lebanon",
    deaths         => 0,
    last_update    => "2020-02-22T20:53:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-12T06:43:02",
    province_state => "Tibet",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Nepal",
    deaths         => 0,
    last_update    => "2020-02-12T14:43:03",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Sri Lanka",
    deaths         => 0,
    last_update    => "2020-02-08T03:43:03",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Sweden",
    deaths         => 0,
    last_update    => "2020-02-01T02:13:26",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:43:03",
    province_state => "Boston, MA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-21T05:13:09",
    province_state => "Humboldt County, CA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:53:03",
    province_state => "Los Angeles, CA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-05T21:53:02",
    province_state => "Madison, WI",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:53:03",
    province_state => "Orange, CA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-21T23:13:16",
    province_state => "Sacramento County, CA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-13T18:53:02",
    province_state => "San Antonio, TX",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-09T07:03:04",
    province_state => "Seattle, WA",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:43:03",
    province_state => "Tempe, AZ",
    recovered      => 0,
  },
]