[
  {
    confirmed      => 3554,
    country_region => "Mainland China",
    deaths         => 125,
    last_update    => "1/28/20 23:00",
    province_state => "Hubei",
    recovered      => 80,
  },
  {
    confirmed      => 207,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/28/20 23:00",
    province_state => "Guangdong",
    recovered      => 4,
  },
  {
    confirmed      => 173,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/28/20 23:00",
    province_state => "Zhejiang",
    recovered      => 3,
  },
  {
    confirmed      => 168,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "1/28/20 23:00",
    province_state => "Henan",
    recovered      => "",
  },
  {
    confirmed      => 143,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/28/20 23:00",
    province_state => "Hunan",
    recovered      => "",
  },
  {
    confirmed      => 132,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/28/20 23:00",
    province_state => "Chongqing",
    recovered      => "",
  },
  {
    confirmed      => 109,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/28/20 23:00",
    province_state => "Jiangxi",
    recovered      => 3,
  },
  {
    confirmed      => 106,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/28/20 23:00",
    province_state => "Anhui",
    recovered      => "",
  },
  {
    confirmed      => 95,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/28/20 23:00",
    province_state => "Shandong",
    recovered      => "",
  },
  {
    confirmed      => 91,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "1/28/20 23:00",
    province_state => "Beijing",
    recovered      => 4,
  },
  {
    confirmed      => 90,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/28/20 23:00",
    province_state => "Sichuan",
    recovered      => "",
  },
  {
    confirmed      => 80,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/28/20 23:00",
    province_state => "Fujian",
    recovered      => "",
  },
  {
    confirmed      => 70,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/28/20 23:00",
    province_state => "Jiangsu",
    recovered      => 1,
  },
  {
    confirmed      => 66,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "1/28/20 23:00",
    province_state => "Shanghai",
    recovered      => 4,
  },
  {
    confirmed      => 51,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/28/20 23:00",
    province_state => "Guangxi",
    recovered      => 2,
  },
  {
    confirmed      => 46,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/28/20 23:00",
    province_state => "Shaanxi",
    recovered      => "",
  },
  {
    confirmed      => 44,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/28/20 23:00",
    province_state => "Yunnan",
    recovered      => "",
  },
  {
    confirmed      => 40,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "1/28/20 23:00",
    province_state => "Hainan",
    recovered      => "",
  },
  {
    confirmed      => 34,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/28/20 23:00",
    province_state => "Liaoning",
    recovered      => "",
  },
  {
    confirmed      => 33,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "1/28/20 23:00",
    province_state => "Hebei",
    recovered      => "",
  },
  {
    confirmed      => 33,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "1/28/20 23:00",
    province_state => "Heilongjiang",
    recovered      => "",
  },
  {
    confirmed      => 27,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/28/20 23:00",
    province_state => "Shanxi",
    recovered      => "",
  },
  {
    confirmed      => 24,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/28/20 23:00",
    province_state => "Tianjin",
    recovered      => "",
  },
  {
    confirmed      => 19,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/28/20 23:00",
    province_state => "Gansu",
    recovered      => "",
  },
  {
    confirmed      => 15,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/28/20 23:00",
    province_state => "Inner Mongolia",
    recovered      => "",
  },
  {
    confirmed      => 11,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/28/20 23:00",
    province_state => "Ningxia",
    recovered      => "",
  },
  {
    confirmed      => 10,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/28/20 23:00",
    province_state => "Xinjiang",
    recovered      => "",
  },
  {
    confirmed      => 9,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/28/20 23:00",
    province_state => "Guizhou",
    recovered      => "",
  },
  {
    confirmed      => 8,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/28/20 23:00",
    province_state => "Jilin",
    recovered      => "",
  },
  {
    confirmed      => 8,
    country_region => "Taiwan",
    deaths         => "",
    last_update    => "1/28/20 23:00",
    province_state => "Taiwan",
    recovered      => "",
  },
  {
    confirmed      => 8,
    country_region => "Hong Kong",
    deaths         => "",
    last_update    => "1/28/20 23:00",
    province_state => "Hong Kong",
    recovered      => "",
  },
  {
    confirmed      => 7,
    country_region => "Macau",
    deaths         => "",
    last_update    => "1/28/20 23:00",
    province_state => "Macau",
    recovered      => "",
  },
  {
    confirmed      => 6,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/28/20 23:00",
    province_state => "Qinghai",
    recovered      => "",
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => "",
    last_update    => "1/28/20 23:00",
    province_state => "Washington",
    recovered      => "",
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => "",
    last_update    => "1/28/20 23:00",
    province_state => "Illinois",
    recovered      => "",
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => "",
    last_update    => "1/28/20 23:00",
    province_state => "California",
    recovered      => "",
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => "",
    last_update    => "1/28/20 23:00",
    province_state => "Arizona",
    recovered      => "",
  },
  {
    confirmed      => 7,
    country_region => "Japan",
    deaths         => "",
    last_update    => "1/28/20 23:00",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 14,
    country_region => "Thailand",
    deaths         => "",
    last_update    => "1/28/20 23:00",
    province_state => "",
    recovered      => 5,
  },
  {
    confirmed      => 4,
    country_region => "South Korea",
    deaths         => "",
    last_update    => "1/28/20 23:00",
    province_state => "",
    recovered      => "",
  },
  {
    confirmed      => 7,
    country_region => "Singapore",
    deaths         => "",
    last_update    => "1/28/20 23:00",
    province_state => "",
    recovered      => "",
  },
  {
    confirmed      => 2,
    country_region => "Vietnam",
    deaths         => "",
    last_update    => "1/28/20 23:00",
    province_state => "",
    recovered      => "",
  },
  {
    confirmed      => 4,
    country_region => "France",
    deaths         => "",
    last_update    => "1/28/20 23:00",
    province_state => "",
    recovered      => "",
  },
  {
    confirmed      => 1,
    country_region => "Nepal",
    deaths         => "",
    last_update    => "1/28/20 23:00",
    province_state => "",
    recovered      => "",
  },
  {
    confirmed      => 4,
    country_region => "Malaysia",
    deaths         => "",
    last_update    => "1/28/20 23:00",
    province_state => "",
    recovered      => "",
  },
  {
    confirmed      => 1,
    country_region => "Canada",
    deaths         => "",
    last_update    => "1/28/20 23:00",
    province_state => "Ontario",
    recovered      => "",
  },
  {
    confirmed      => 1,
    country_region => "Canada",
    deaths         => "",
    last_update    => "1/28/20 23:00",
    province_state => "British Columbia",
    recovered      => "",
  },
  {
    confirmed      => 1,
    country_region => "Cambodia",
    deaths         => "",
    last_update    => "1/28/20 23:00",
    province_state => "",
    recovered      => "",
  },
  {
    confirmed      => 1,
    country_region => "Sri Lanka",
    deaths         => "",
    last_update    => "1/28/20 23:00",
    province_state => "",
    recovered      => "",
  },
  {
    confirmed      => 4,
    country_region => "Australia",
    deaths         => "",
    last_update    => "1/28/20 23:00",
    province_state => "New South Wales",
    recovered      => "",
  },
  {
    confirmed      => 1,
    country_region => "Australia",
    deaths         => "",
    last_update    => "1/28/20 23:00",
    province_state => "Victoria",
    recovered      => "",
  },
  {
    confirmed      => 4,
    country_region => "Germany",
    deaths         => "",
    last_update    => "1/28/20 23:00",
    province_state => "Bavaria",
    recovered      => "",
  },
]