[
  {
    confirmed      => 48206,
    country_region => "Mainland China",
    deaths         => 1310,
    last_update    => "2020-02-13T14:13:06",
    province_state => "Hubei",
    recovered      => 3459,
  },
  {
    confirmed      => 1241,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-13T13:33:01",
    province_state => "Guangdong",
    recovered      => 314,
  },
  {
    confirmed      => 1169,
    country_region => "Mainland China",
    deaths         => 10,
    last_update    => "2020-02-13T14:53:02",
    province_state => "Henan",
    recovered      => 296,
  },
  {
    confirmed      => 1145,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-13T14:13:06",
    province_state => "Zhejiang",
    recovered      => 360,
  },
  {
    confirmed      => 968,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-13T11:53:02",
    province_state => "Hunan",
    recovered      => 339,
  },
  {
    confirmed      => 910,
    country_region => "Mainland China",
    deaths         => 5,
    last_update    => "2020-02-13T13:33:01",
    province_state => "Anhui",
    recovered      => 157,
  },
  {
    confirmed      => 872,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-13T01:13:08",
    province_state => "Jiangxi",
    recovered      => 170,
  },
  {
    confirmed      => 570,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-13T10:33:23",
    province_state => "Jiangsu",
    recovered      => 139,
  },
  {
    confirmed      => 529,
    country_region => "Mainland China",
    deaths         => 4,
    last_update    => "2020-02-13T23:23:05",
    province_state => "Chongqing",
    recovered      => 128,
  },
  {
    confirmed      => 509,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-13T13:33:01",
    province_state => "Shandong",
    recovered      => 105,
  },
  {
    confirmed      => 451,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-13T13:33:01",
    province_state => "Sichuan",
    recovered      => 104,
  },
  {
    confirmed      => 395,
    country_region => "Mainland China",
    deaths         => 9,
    last_update    => "2020-02-13T12:13:06",
    province_state => "Heilongjiang",
    recovered      => 33,
  },
  {
    confirmed      => 366,
    country_region => "Mainland China",
    deaths         => 3,
    last_update    => "2020-02-13T14:13:06",
    province_state => "Beijing",
    recovered      => 69,
  },
  {
    confirmed      => 315,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-13T06:13:15",
    province_state => "Shanghai",
    recovered      => 62,
  },
  {
    confirmed      => 279,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-13T10:33:23",
    province_state => "Fujian",
    recovered      => 57,
  },
  {
    confirmed      => 265,
    country_region => "Mainland China",
    deaths         => 3,
    last_update    => "2020-02-13T10:33:23",
    province_state => "Hebei",
    recovered      => 68,
  },
  {
    confirmed      => 229,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-13T10:33:23",
    province_state => "Shaanxi",
    recovered      => 46,
  },
  {
    confirmed      => 222,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-13T00:23:10",
    province_state => "Guangxi",
    recovered      => 33,
  },
  {
    confirmed      => 175,
    country_region => "Others",
    deaths         => 0,
    last_update    => "2020-02-12T04:23:38",
    province_state => "Diamond Princess cruise ship",
    recovered      => 0,
  },
  {
    confirmed      => 157,
    country_region => "Mainland China",
    deaths         => 4,
    last_update    => "2020-02-13T10:43:03",
    province_state => "Hainan",
    recovered      => 30,
  },
  {
    confirmed      => 156,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-13T08:43:08",
    province_state => "Yunnan",
    recovered      => 27,
  },
  {
    confirmed      => 135,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-13T10:33:23",
    province_state => "Guizhou",
    recovered      => 27,
  },
  {
    confirmed      => 126,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-13T23:23:05",
    province_state => "Shanxi",
    recovered      => 36,
  },
  {
    confirmed      => 119,
    country_region => "Mainland China",
    deaths         => 3,
    last_update    => "2020-02-13T23:43:02",
    province_state => "Tianjin",
    recovered      => 21,
  },
  {
    confirmed      => 117,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-13T14:33:02",
    province_state => "Liaoning",
    recovered      => 22,
  },
  {
    confirmed      => 90,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-13T15:53:03",
    province_state => "Gansu",
    recovered      => 39,
  },
  {
    confirmed      => 84,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-13T13:33:01",
    province_state => "Jilin",
    recovered      => 24,
  },
  {
    confirmed      => 64,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-13T01:23:08",
    province_state => "Ningxia",
    recovered      => 24,
  },
  {
    confirmed      => 63,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-13T10:33:23",
    province_state => "Xinjiang",
    recovered      => 6,
  },
  {
    confirmed      => 61,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-13T01:23:08",
    province_state => "Inner Mongolia",
    recovered      => 6,
  },
  {
    confirmed      => 58,
    country_region => "Singapore",
    deaths         => 0,
    last_update    => "2020-02-13T14:33:02",
    province_state => "",
    recovered      => 15,
  },
  {
    confirmed      => 53,
    country_region => "Hong Kong",
    deaths         => 1,
    last_update    => "2020-02-13T14:53:02",
    province_state => "Hong Kong",
    recovered      => 1,
  },
  {
    confirmed      => 33,
    country_region => "Thailand",
    deaths         => 0,
    last_update    => "2020-02-13T17:53:03",
    province_state => "",
    recovered      => 12,
  },
  {
    confirmed      => 28,
    country_region => "Japan",
    deaths         => 1,
    last_update    => "2020-02-13T12:23:05",
    province_state => "",
    recovered      => 9,
  },
  {
    confirmed      => 28,
    country_region => "South Korea",
    deaths         => 0,
    last_update    => "2020-02-12T14:43:03",
    province_state => "",
    recovered      => 7,
  },
  {
    confirmed      => 19,
    country_region => "Malaysia",
    deaths         => 0,
    last_update    => "2020-02-13T10:53:02",
    province_state => "",
    recovered      => 3,
  },
  {
    confirmed      => 18,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-13T08:43:08",
    province_state => "Qinghai",
    recovered      => 11,
  },
  {
    confirmed      => 18,
    country_region => "Taiwan",
    deaths         => 0,
    last_update    => "2020-02-09T09:13:11",
    province_state => "Taiwan",
    recovered      => 1,
  },
  {
    confirmed      => 16,
    country_region => "Germany",
    deaths         => 0,
    last_update    => "2020-02-13T15:13:11",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 16,
    country_region => "Vietnam",
    deaths         => 0,
    last_update    => "2020-02-13T06:33:02",
    province_state => "",
    recovered      => 7,
  },
  {
    confirmed      => 11,
    country_region => "France",
    deaths         => 0,
    last_update    => "2020-02-12T18:53:02",
    province_state => "",
    recovered      => 2,
  },
  {
    confirmed      => 10,
    country_region => "Macau",
    deaths         => 0,
    last_update    => "2020-02-13T14:13:06",
    province_state => "Macau",
    recovered      => 3,
  },
  {
    confirmed      => 9,
    country_region => "UK",
    deaths         => 0,
    last_update    => "2020-02-12T19:03:06",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 8,
    country_region => "United Arab Emirates",
    deaths         => 0,
    last_update    => "2020-02-12T00:33:02",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 5,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-09T19:33:02",
    province_state => "Queensland",
    recovered      => 0,
  },
  {
    confirmed      => 4,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-13T17:53:03",
    province_state => "New South Wales",
    recovered      => 4,
  },
  {
    confirmed      => 4,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-13T17:53:03",
    province_state => "Victoria",
    recovered      => 4,
  },
  {
    confirmed      => 4,
    country_region => "Canada",
    deaths         => 0,
    last_update    => "2020-02-07T05:43:03",
    province_state => "British Columbia",
    recovered      => 0,
  },
  {
    confirmed      => 3,
    country_region => "India",
    deaths         => 0,
    last_update    => "2020-02-13T18:53:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 3,
    country_region => "Italy",
    deaths         => 0,
    last_update    => "2020-02-07T17:53:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 3,
    country_region => "Philippines",
    deaths         => 1,
    last_update    => "2020-02-12T07:43:02",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 2,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-02T22:33:07",
    province_state => "South Australia",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "Canada",
    deaths         => 0,
    last_update    => "2020-02-04T00:13:06",
    province_state => "Toronto, ON",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "Russia",
    deaths         => 0,
    last_update    => "2020-02-12T14:43:03",
    province_state => "",
    recovered      => 2,
  },
  {
    confirmed      => 2,
    country_region => "Spain",
    deaths         => 0,
    last_update    => "2020-02-09T20:33:03",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-09T19:03:03",
    province_state => "Chicago, IL",
    recovered      => 2,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-03T03:53:02",
    province_state => "San Benito, CA",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-13T03:13:08",
    province_state => "San Diego County, CA",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-03T00:43:02",
    province_state => "Santa Clara, CA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Belgium",
    deaths         => 0,
    last_update    => "2020-02-04T15:43:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Cambodia",
    deaths         => 0,
    last_update    => "2020-02-12T07:43:02",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Canada",
    deaths         => 0,
    last_update    => "2020-02-12T18:53:03",
    province_state => "London, ON",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Finland",
    deaths         => 0,
    last_update    => "2020-02-12T00:03:12",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-12T06:43:02",
    province_state => "Tibet",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Nepal",
    deaths         => 0,
    last_update    => "2020-02-12T14:43:03",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Sri Lanka",
    deaths         => 0,
    last_update    => "2020-02-08T03:43:03",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Sweden",
    deaths         => 0,
    last_update    => "2020-02-01T02:13:26",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:43:03",
    province_state => "Boston, MA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:53:03",
    province_state => "Los Angeles, CA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-05T21:53:02",
    province_state => "Madison, WI",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:53:03",
    province_state => "Orange, CA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-13T18:53:02",
    province_state => "San Antonio, TX",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-09T07:03:04",
    province_state => "Seattle, WA",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:43:03",
    province_state => "Tempe, AZ",
    recovered      => 0,
  },
]