[
  {
    confirmed      => 65596,
    country_region => "Mainland China",
    deaths         => 2641,
    last_update    => "2020-02-27T12:13:14",
    province_state => "Hubei",
    recovered      => 23383,
  },
  {
    confirmed      => 1766,
    country_region => "South Korea",
    deaths         => 13,
    last_update    => "2020-02-27T12:03:04",
    province_state => "",
    recovered      => 22,
  },
  {
    confirmed      => 1347,
    country_region => "Mainland China",
    deaths         => 7,
    last_update    => "2020-02-27T09:53:02",
    province_state => "Guangdong",
    recovered      => 890,
  },
  {
    confirmed      => 1272,
    country_region => "Mainland China",
    deaths         => 20,
    last_update    => "2020-02-27T15:03:11",
    province_state => "Henan",
    recovered      => 1068,
  },
  {
    confirmed      => 1205,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-27T12:43:02",
    province_state => "Zhejiang",
    recovered      => 932,
  },
  {
    confirmed      => 1017,
    country_region => "Mainland China",
    deaths         => 4,
    last_update    => "2020-02-27T12:43:02",
    province_state => "Hunan",
    recovered      => 804,
  },
  {
    confirmed      => 989,
    country_region => "Mainland China",
    deaths         => 6,
    last_update    => "2020-02-27T14:13:06",
    province_state => "Anhui",
    recovered      => 792,
  },
  {
    confirmed      => 934,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-27T01:43:02",
    province_state => "Jiangxi",
    recovered      => 754,
  },
  {
    confirmed      => 756,
    country_region => "Mainland China",
    deaths         => 6,
    last_update    => "2020-02-27T14:13:06",
    province_state => "Shandong",
    recovered      => 387,
  },
  {
    confirmed      => 705,
    country_region => "Others",
    deaths         => 4,
    last_update    => "2020-02-26T19:33:02",
    province_state => "Diamond Princess cruise ship",
    recovered      => 10,
  },
  {
    confirmed      => 655,
    country_region => "Italy",
    deaths         => 17,
    last_update    => "2020-02-27T23:23:02",
    province_state => "",
    recovered      => 45,
  },
  {
    confirmed      => 631,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-27T14:13:06",
    province_state => "Jiangsu",
    recovered      => 498,
  },
  {
    confirmed      => 576,
    country_region => "Mainland China",
    deaths         => 6,
    last_update    => "2020-02-27T23:23:02",
    province_state => "Chongqing",
    recovered      => 401,
  },
  {
    confirmed      => 534,
    country_region => "Mainland China",
    deaths         => 3,
    last_update    => "2020-02-27T12:43:02",
    province_state => "Sichuan",
    recovered      => 321,
  },
  {
    confirmed      => 480,
    country_region => "Mainland China",
    deaths         => 13,
    last_update    => "2020-02-27T12:43:02",
    province_state => "Heilongjiang",
    recovered      => 270,
  },
  {
    confirmed      => 410,
    country_region => "Mainland China",
    deaths         => 5,
    last_update    => "2020-02-27T02:23:13",
    province_state => "Beijing",
    recovered      => 248,
  },
  {
    confirmed      => 337,
    country_region => "Mainland China",
    deaths         => 3,
    last_update    => "2020-02-27T04:03:12",
    province_state => "Shanghai",
    recovered      => 276,
  },
  {
    confirmed      => 317,
    country_region => "Mainland China",
    deaths         => 6,
    last_update    => "2020-02-27T12:43:02",
    province_state => "Hebei",
    recovered      => 274,
  },
  {
    confirmed      => 296,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-27T10:03:07",
    province_state => "Fujian",
    recovered      => 228,
  },
  {
    confirmed      => 252,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-27T10:03:07",
    province_state => "Guangxi",
    recovered      => 161,
  },
  {
    confirmed      => 245,
    country_region => "Iran",
    deaths         => 26,
    last_update    => "2020-02-27T12:03:04",
    province_state => "",
    recovered      => 49,
  },
  {
    confirmed      => 245,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-27T12:43:02",
    province_state => "Shaanxi",
    recovered      => 195,
  },
  {
    confirmed      => 214,
    country_region => "Japan",
    deaths         => 4,
    last_update    => "2020-02-27T23:33:02",
    province_state => "",
    recovered      => 22,
  },
  {
    confirmed      => 174,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-27T10:03:07",
    province_state => "Yunnan",
    recovered      => 150,
  },
  {
    confirmed      => 168,
    country_region => "Mainland China",
    deaths         => 5,
    last_update    => "2020-02-27T10:03:07",
    province_state => "Hainan",
    recovered      => 131,
  },
  {
    confirmed      => 146,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-27T00:43:02",
    province_state => "Guizhou",
    recovered      => 112,
  },
  {
    confirmed      => 136,
    country_region => "Mainland China",
    deaths         => 3,
    last_update    => "2020-02-27T23:13:04",
    province_state => "Tianjin",
    recovered      => 102,
  },
  {
    confirmed      => 133,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-27T23:13:04",
    province_state => "Shanxi",
    recovered      => 107,
  },
  {
    confirmed      => 121,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-27T14:13:06",
    province_state => "Liaoning",
    recovered      => 93,
  },
  {
    confirmed      => 93,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-27T12:43:02",
    province_state => "Jilin",
    recovered      => 67,
  },
  {
    confirmed      => 93,
    country_region => "Singapore",
    deaths         => 0,
    last_update    => "2020-02-26T19:33:02",
    province_state => "",
    recovered      => 62,
  },
  {
    confirmed      => 92,
    country_region => "Hong Kong",
    deaths         => 2,
    last_update    => "2020-02-27T09:53:02",
    province_state => "Hong Kong",
    recovered      => 24,
  },
  {
    confirmed      => 91,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-26T14:13:10",
    province_state => "Gansu",
    recovered      => 81,
  },
  {
    confirmed      => 76,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-27T12:43:02",
    province_state => "Xinjiang",
    recovered      => 43,
  },
  {
    confirmed      => 75,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-27T23:33:02",
    province_state => "Inner Mongolia",
    recovered      => 43,
  },
  {
    confirmed      => 72,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-27T10:03:07",
    province_state => "Ningxia",
    recovered      => 68,
  },
  {
    confirmed      => 46,
    country_region => "Germany",
    deaths         => 0,
    last_update    => "2020-02-27T23:13:04",
    province_state => "",
    recovered      => 16,
  },
  {
    confirmed      => 43,
    country_region => "Kuwait",
    deaths         => 0,
    last_update    => "2020-02-27T13:33:03",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 42,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-26T20:03:06",
    province_state => "Unassigned Location (From Diamond Princess)",
    recovered      => 0,
  },
  {
    confirmed      => 40,
    country_region => "Thailand",
    deaths         => 0,
    last_update    => "2020-02-26T07:23:03",
    province_state => "",
    recovered      => 22,
  },
  {
    confirmed      => 38,
    country_region => "France",
    deaths         => 2,
    last_update    => "2020-02-27T22:13:10",
    province_state => "",
    recovered      => 11,
  },
  {
    confirmed      => 33,
    country_region => "Bahrain",
    deaths         => 0,
    last_update    => "2020-02-26T21:03:07",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 32,
    country_region => "Taiwan",
    deaths         => 1,
    last_update    => "2020-02-26T12:23:04",
    province_state => "Taiwan",
    recovered      => 5,
  },
  {
    confirmed      => 23,
    country_region => "Malaysia",
    deaths         => 0,
    last_update    => "2020-02-27T15:13:13",
    province_state => "",
    recovered      => 18,
  },
  {
    confirmed      => 18,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-21T04:43:02",
    province_state => "Qinghai",
    recovered      => 18,
  },
  {
    confirmed      => 16,
    country_region => "Vietnam",
    deaths         => 0,
    last_update    => "2020-02-25T08:53:02",
    province_state => "",
    recovered      => 16,
  },
  {
    confirmed      => 15,
    country_region => "Spain",
    deaths         => 0,
    last_update    => "2020-02-27T13:23:02",
    province_state => "",
    recovered      => 2,
  },
  {
    confirmed      => 15,
    country_region => "UK",
    deaths         => 0,
    last_update    => "2020-02-27T13:23:02",
    province_state => "",
    recovered      => 8,
  },
  {
    confirmed      => 13,
    country_region => "United Arab Emirates",
    deaths         => 0,
    last_update    => "2020-02-22T14:53:02",
    province_state => "",
    recovered      => 4,
  },
  {
    confirmed      => 10,
    country_region => "Macau",
    deaths         => 0,
    last_update    => "2020-02-27T12:43:02",
    province_state => "Macau",
    recovered      => 8,
  },
  {
    confirmed      => 8,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-27T03:33:06",
    province_state => "From Diamond Princess",
    recovered      => 0,
  },
  {
    confirmed      => 8,
    country_region => "Switzerland",
    deaths         => 0,
    last_update    => "2020-02-27T23:03:11",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 7,
    country_region => "Canada",
    deaths         => 0,
    last_update    => "2020-02-27T03:33:06",
    province_state => "British Columbia",
    recovered      => 3,
  },
  {
    confirmed      => 7,
    country_region => "Iraq",
    deaths         => 0,
    last_update    => "2020-02-27T22:23:11",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 7,
    country_region => "Sweden",
    deaths         => 0,
    last_update    => "2020-02-27T20:33:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 5,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-21T05:43:02",
    province_state => "Queensland",
    recovered      => 1,
  },
  {
    confirmed      => 5,
    country_region => "Canada",
    deaths         => 0,
    last_update    => "2020-02-27T22:43:02",
    province_state => "Toronto, ON",
    recovered      => 2,
  },
  {
    confirmed      => 4,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-13T17:53:03",
    province_state => "New South Wales",
    recovered      => 4,
  },
  {
    confirmed      => 4,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-13T17:53:03",
    province_state => "Victoria",
    recovered      => 4,
  },
  {
    confirmed      => 4,
    country_region => "Oman",
    deaths         => 0,
    last_update    => "2020-02-26T04:53:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 3,
    country_region => "Austria",
    deaths         => 0,
    last_update    => "2020-02-27T14:03:03",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 3,
    country_region => "Croatia",
    deaths         => 0,
    last_update    => "2020-02-26T20:03:06",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 3,
    country_region => "Greece",
    deaths         => 0,
    last_update    => "2020-02-27T14:03:03",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 3,
    country_region => "India",
    deaths         => 0,
    last_update    => "2020-02-16T07:43:02",
    province_state => "",
    recovered      => 3,
  },
  {
    confirmed      => 3,
    country_region => "Israel",
    deaths         => 0,
    last_update    => "2020-02-27T14:03:03",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 3,
    country_region => "Philippines",
    deaths         => 1,
    last_update    => "2020-02-12T07:43:02",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 2,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-17T08:13:09",
    province_state => "South Australia",
    recovered      => 2,
  },
  {
    confirmed      => 2,
    country_region => "Finland",
    deaths         => 0,
    last_update    => "2020-02-26T19:03:08",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 2,
    country_region => "Lebanon",
    deaths         => 0,
    last_update    => "2020-02-26T19:33:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "Pakistan",
    deaths         => 0,
    last_update    => "2020-02-26T23:53:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "Russia",
    deaths         => 0,
    last_update    => "2020-02-12T14:43:03",
    province_state => "",
    recovered      => 2,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-09T19:03:03",
    province_state => "Chicago, IL",
    recovered      => 2,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-27T20:33:02",
    province_state => "Sacramento County, CA",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-03T03:53:02",
    province_state => "San Benito, CA",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-21T05:43:02",
    province_state => "San Diego County, CA",
    recovered      => 1,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-21T05:23:04",
    province_state => "Santa Clara, CA",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Afghanistan",
    deaths         => 0,
    last_update    => "2020-02-24T23:33:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Algeria",
    deaths         => 0,
    last_update    => "2020-02-25T23:43:03",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Belgium",
    deaths         => 0,
    last_update    => "2020-02-17T04:23:06",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Brazil",
    deaths         => 0,
    last_update    => "2020-02-26T23:53:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Cambodia",
    deaths         => 0,
    last_update    => "2020-02-12T07:43:02",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Canada",
    deaths         => 0,
    last_update    => "2020-02-12T18:53:03",
    province_state => "London, ON",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Denmark",
    deaths         => 0,
    last_update    => "2020-02-27T16:23:03",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Egypt",
    deaths         => 0,
    last_update    => "2020-02-21T18:53:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Estonia",
    deaths         => 0,
    last_update    => "2020-02-27T16:23:03",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Georgia",
    deaths         => 0,
    last_update    => "2020-02-27T16:23:03",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-12T06:43:02",
    province_state => "Tibet",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Nepal",
    deaths         => 0,
    last_update    => "2020-02-12T14:43:03",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Netherlands",
    deaths         => 0,
    last_update    => "2020-02-27T21:13:10",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "North Macedonia",
    deaths         => 0,
    last_update    => "2020-02-27T16:23:03",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Norway",
    deaths         => 0,
    last_update    => "2020-02-27T16:23:03",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Romania",
    deaths         => 0,
    last_update    => "2020-02-27T16:23:03",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "San Marino",
    deaths         => 0,
    last_update    => "2020-02-27T21:13:10",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Sri Lanka",
    deaths         => 0,
    last_update    => "2020-02-08T03:43:03",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:43:03",
    province_state => "Boston, MA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-21T05:13:09",
    province_state => "Humboldt County, CA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:53:03",
    province_state => "Los Angeles, CA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-05T21:53:02",
    province_state => "Madison, WI",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:53:03",
    province_state => "Orange, CA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-13T18:53:02",
    province_state => "San Antonio, TX",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-09T07:03:04",
    province_state => "Seattle, WA",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-25T21:23:03",
    province_state => "Tempe, AZ",
    recovered      => 1,
  },
  {
    confirmed      => 0,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-24T23:33:02",
    province_state => "Lackland, TX (From Diamond Princess)",
    recovered      => 0,
  },
  {
    confirmed      => 0,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-24T23:33:02",
    province_state => "Omaha, NE (From Diamond Princess)",
    recovered      => 0,
  },
  {
    confirmed      => 0,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-24T23:33:02",
    province_state => "Travis, CA (From Diamond Princess)",
    recovered      => 0,
  },
]