[
  {
    confirmed      => 29631,
    country_region => "Mainland China",
    deaths         => 871,
    last_update    => "2020-02-09T23:33:02",
    province_state => "Hubei",
    recovered      => 1795,
  },
  {
    confirmed      => 1131,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-09T15:03:05",
    province_state => "Guangdong",
    recovered      => 141,
  },
  {
    confirmed      => 1075,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-09T12:03:04",
    province_state => "Zhejiang",
    recovered      => 201,
  },
  {
    confirmed      => 1033,
    country_region => "Mainland China",
    deaths         => 6,
    last_update    => "2020-02-09T11:23:08",
    province_state => "Henan",
    recovered      => 153,
  },
  {
    confirmed      => 838,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-09T12:33:01",
    province_state => "Hunan",
    recovered      => 186,
  },
  {
    confirmed      => 779,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-09T09:33:02",
    province_state => "Anhui",
    recovered      => 72,
  },
  {
    confirmed      => 740,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-09T11:33:12",
    province_state => "Jiangxi",
    recovered      => 73,
  },
  {
    confirmed      => 468,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-09T23:53:02",
    province_state => "Chongqing",
    recovered      => 51,
  },
  {
    confirmed      => 468,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-09T10:23:11",
    province_state => "Jiangsu",
    recovered      => 71,
  },
  {
    confirmed      => 444,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-09T15:03:05",
    province_state => "Shandong",
    recovered      => 63,
  },
  {
    confirmed      => 386,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-09T12:43:01",
    province_state => "Sichuan",
    recovered      => 71,
  },
  {
    confirmed      => 326,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-09T03:43:02",
    province_state => "Beijing",
    recovered      => 37,
  },
  {
    confirmed      => 307,
    country_region => "Mainland China",
    deaths         => 6,
    last_update    => "2020-02-09T08:43:05",
    province_state => "Heilongjiang",
    recovered      => 14,
  },
  {
    confirmed      => 293,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-09T06:33:01",
    province_state => "Shanghai",
    recovered      => 44,
  },
  {
    confirmed      => 250,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-09T09:13:11",
    province_state => "Fujian",
    recovered      => 35,
  },
  {
    confirmed      => 208,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-09T03:03:09",
    province_state => "Shaanxi",
    recovered      => 25,
  },
  {
    confirmed      => 206,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-09T12:43:01",
    province_state => "Hebei",
    recovered      => 34,
  },
  {
    confirmed      => 195,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-09T00:33:07",
    province_state => "Guangxi",
    recovered      => 18,
  },
  {
    confirmed      => 141,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-09T08:53:02",
    province_state => "Yunnan",
    recovered      => 18,
  },
  {
    confirmed      => 131,
    country_region => "Mainland China",
    deaths         => 3,
    last_update    => "2020-02-09T13:33:02",
    province_state => "Hainan",
    recovered      => 19,
  },
  {
    confirmed      => 119,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-09T23:43:02",
    province_state => "Shanxi",
    recovered      => 25,
  },
  {
    confirmed      => 107,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-09T12:23:03",
    province_state => "Liaoning",
    recovered      => 12,
  },
  {
    confirmed      => 99,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-09T09:53:02",
    province_state => "Guizhou",
    recovered      => 7,
  },
  {
    confirmed      => 91,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-09T23:43:02",
    province_state => "Tianjin",
    recovered      => 4,
  },
  {
    confirmed      => 83,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-09T23:33:02",
    province_state => "Gansu",
    recovered      => 16,
  },
  {
    confirmed      => 78,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-09T09:03:04",
    province_state => "Jilin",
    recovered      => 12,
  },
  {
    confirmed      => 64,
    country_region => "Others",
    deaths         => 0,
    last_update    => "2020-02-09T06:13:11",
    province_state => "Diamond Princess cruise ship",
    recovered      => 0,
  },
  {
    confirmed      => 54,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-09T02:23:07",
    province_state => "Inner Mongolia",
    recovered      => 5,
  },
  {
    confirmed      => 45,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-09T02:03:11",
    province_state => "Ningxia",
    recovered      => 13,
  },
  {
    confirmed      => 45,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-09T01:23:08",
    province_state => "Xinjiang",
    recovered      => 0,
  },
  {
    confirmed      => 40,
    country_region => "Singapore",
    deaths         => 0,
    last_update    => "2020-02-09T02:43:02",
    province_state => "",
    recovered      => 2,
  },
  {
    confirmed      => 32,
    country_region => "Thailand",
    deaths         => 0,
    last_update    => "2020-02-08T12:53:01",
    province_state => "",
    recovered      => 10,
  },
  {
    confirmed      => 29,
    country_region => "Hong Kong",
    deaths         => 1,
    last_update    => "2020-02-09T09:53:02",
    province_state => "Hong Kong",
    recovered      => 0,
  },
  {
    confirmed      => 26,
    country_region => "Japan",
    deaths         => 0,
    last_update    => "2020-02-09T06:13:11",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 25,
    country_region => "South Korea",
    deaths         => 0,
    last_update    => "2020-02-09T02:33:02",
    province_state => "",
    recovered      => 3,
  },
  {
    confirmed      => 18,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-06T02:13:15",
    province_state => "Qinghai",
    recovered      => 3,
  },
  {
    confirmed      => 18,
    country_region => "Taiwan",
    deaths         => 0,
    last_update    => "2020-02-09T09:13:11",
    province_state => "Taiwan",
    recovered      => 1,
  },
  {
    confirmed      => 16,
    country_region => "Malaysia",
    deaths         => 0,
    last_update    => "2020-02-08T10:23:04",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 14,
    country_region => "Germany",
    deaths         => 0,
    last_update    => "2020-02-09T06:13:11",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 13,
    country_region => "Vietnam",
    deaths         => 0,
    last_update    => "2020-02-08T07:23:04",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 11,
    country_region => "France",
    deaths         => 0,
    last_update    => "2020-02-08T09:53:01",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 10,
    country_region => "Macau",
    deaths         => 0,
    last_update    => "2020-02-06T14:23:04",
    province_state => "Macau",
    recovered      => 1,
  },
  {
    confirmed      => 7,
    country_region => "United Arab Emirates",
    deaths         => 0,
    last_update    => "2020-02-08T07:03:16",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 5,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-09T19:33:02",
    province_state => "Queensland",
    recovered      => 0,
  },
  {
    confirmed      => 4,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-06T03:13:22",
    province_state => "New South Wales",
    recovered      => 2,
  },
  {
    confirmed      => 4,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-01T18:12:49",
    province_state => "Victoria",
    recovered      => 0,
  },
  {
    confirmed      => 4,
    country_region => "Canada",
    deaths         => 0,
    last_update    => "2020-02-07T05:43:03",
    province_state => "British Columbia",
    recovered      => 0,
  },
  {
    confirmed      => 3,
    country_region => "India",
    deaths         => 0,
    last_update    => "2020-02-03T21:43:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 3,
    country_region => "Italy",
    deaths         => 0,
    last_update    => "2020-02-07T17:53:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 3,
    country_region => "Philippines",
    deaths         => 1,
    last_update    => "2020-02-07T16:43:04",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 3,
    country_region => "UK",
    deaths         => 0,
    last_update    => "2020-02-07T18:33:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-02T22:33:07",
    province_state => "South Australia",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "Canada",
    deaths         => 0,
    last_update    => "2020-02-04T00:13:06",
    province_state => "Toronto, ON",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "Russia",
    deaths         => 0,
    last_update    => "2020-01-31T16:13:45",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "Spain",
    deaths         => 0,
    last_update    => "2020-02-09T20:33:03",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-09T19:03:03",
    province_state => "Chicago, IL",
    recovered      => 2,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-03T03:53:02",
    province_state => "San Benito, CA",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-03T00:43:02",
    province_state => "Santa Clara, CA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Belgium",
    deaths         => 0,
    last_update    => "2020-02-04T15:43:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Cambodia",
    deaths         => 0,
    last_update    => "2020-01-31T08:15:53",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Canada",
    deaths         => 0,
    last_update    => "2020-02-04T00:03:11",
    province_state => "London, ON",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Finland",
    deaths         => 0,
    last_update    => "2020-01-31T08:15:53",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-01T01:52:40",
    province_state => "Tibet",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Nepal",
    deaths         => 0,
    last_update    => "2020-01-31T08:15:53",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Sri Lanka",
    deaths         => 0,
    last_update    => "2020-02-08T03:43:03",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Sweden",
    deaths         => 0,
    last_update    => "2020-02-01T02:13:26",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:43:03",
    province_state => "Boston, MA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:53:03",
    province_state => "Los Angeles, CA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-05T21:53:02",
    province_state => "Madison, WI",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:53:03",
    province_state => "Orange, CA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-09T07:03:04",
    province_state => "Seattle, WA",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:43:03",
    province_state => "Tempe, AZ",
    recovered      => 0,
  },
]