[
  {
    confirmed      => 31728,
    country_region => "Mainland China",
    deaths         => 974,
    last_update    => "2020-02-10T23:33:02",
    province_state => "Hubei",
    recovered      => 2222,
  },
  {
    confirmed      => 1159,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-10T13:43:02",
    province_state => "Guangdong",
    recovered      => 167,
  },
  {
    confirmed      => 1092,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-10T14:13:12",
    province_state => "Zhejiang",
    recovered      => 242,
  },
  {
    confirmed      => 1073,
    country_region => "Mainland China",
    deaths         => 6,
    last_update    => "2020-02-10T13:53:02",
    province_state => "Henan",
    recovered      => 191,
  },
  {
    confirmed      => 879,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-10T13:53:02",
    province_state => "Hunan",
    recovered      => 208,
  },
  {
    confirmed      => 830,
    country_region => "Mainland China",
    deaths         => 3,
    last_update    => "2020-02-10T07:23:04",
    province_state => "Anhui",
    recovered      => 88,
  },
  {
    confirmed      => 771,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-10T13:53:02",
    province_state => "Jiangxi",
    recovered      => 105,
  },
  {
    confirmed      => 492,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-10T14:03:05",
    province_state => "Jiangsu",
    recovered      => 81,
  },
  {
    confirmed      => 486,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-10T23:43:02",
    province_state => "Chongqing",
    recovered      => 66,
  },
  {
    confirmed      => 466,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-10T09:33:02",
    province_state => "Shandong",
    recovered      => 66,
  },
  {
    confirmed      => 405,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-10T10:03:02",
    province_state => "Sichuan",
    recovered      => 80,
  },
  {
    confirmed      => 337,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-10T03:13:08",
    province_state => "Beijing",
    recovered      => 44,
  },
  {
    confirmed      => 331,
    country_region => "Mainland China",
    deaths         => 7,
    last_update    => "2020-02-10T07:33:05",
    province_state => "Heilongjiang",
    recovered      => 30,
  },
  {
    confirmed      => 299,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-10T06:03:13",
    province_state => "Shanghai",
    recovered      => 48,
  },
  {
    confirmed      => 261,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-10T14:03:05",
    province_state => "Fujian",
    recovered      => 39,
  },
  {
    confirmed      => 218,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-10T10:03:02",
    province_state => "Hebei",
    recovered      => 41,
  },
  {
    confirmed      => 213,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-10T13:23:06",
    province_state => "Shaanxi",
    recovered      => 30,
  },
  {
    confirmed      => 210,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-10T14:03:05",
    province_state => "Guangxi",
    recovered      => 24,
  },
  {
    confirmed      => 149,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-10T09:43:02",
    province_state => "Yunnan",
    recovered      => 19,
  },
  {
    confirmed      => 138,
    country_region => "Mainland China",
    deaths         => 3,
    last_update    => "2020-02-10T09:33:02",
    province_state => "Hainan",
    recovered      => 19,
  },
  {
    confirmed      => 135,
    country_region => "Others",
    deaths         => 0,
    last_update    => "2020-02-10T16:03:12",
    province_state => "Diamond Princess cruise ship",
    recovered      => 0,
  },
  {
    confirmed      => 119,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-09T23:43:02",
    province_state => "Shanxi",
    recovered      => 25,
  },
  {
    confirmed      => 109,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-10T12:33:02",
    province_state => "Guizhou",
    recovered      => 10,
  },
  {
    confirmed      => 108,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-10T14:03:05",
    province_state => "Liaoning",
    recovered      => 13,
  },
  {
    confirmed      => 95,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-10T14:23:08",
    province_state => "Tianjin",
    recovered      => 8,
  },
  {
    confirmed      => 83,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-10T07:23:04",
    province_state => "Gansu",
    recovered      => 17,
  },
  {
    confirmed      => 80,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-10T14:03:05",
    province_state => "Jilin",
    recovered      => 13,
  },
  {
    confirmed      => 58,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-10T02:43:05",
    province_state => "Inner Mongolia",
    recovered      => 5,
  },
  {
    confirmed      => 49,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-10T01:43:02",
    province_state => "Ningxia",
    recovered      => 13,
  },
  {
    confirmed      => 49,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-10T01:13:06",
    province_state => "Xinjiang",
    recovered      => 0,
  },
  {
    confirmed      => 45,
    country_region => "Singapore",
    deaths         => 0,
    last_update    => "2020-02-10T19:03:02",
    province_state => "",
    recovered      => 2,
  },
  {
    confirmed      => 38,
    country_region => "Hong Kong",
    deaths         => 1,
    last_update    => "2020-02-10T10:13:06",
    province_state => "Hong Kong",
    recovered      => 0,
  },
  {
    confirmed      => 32,
    country_region => "Thailand",
    deaths         => 0,
    last_update    => "2020-02-08T12:53:01",
    province_state => "",
    recovered      => 10,
  },
  {
    confirmed      => 27,
    country_region => "South Korea",
    deaths         => 0,
    last_update    => "2020-02-10T03:03:09",
    province_state => "",
    recovered      => 3,
  },
  {
    confirmed      => 26,
    country_region => "Japan",
    deaths         => 0,
    last_update    => "2020-02-10T21:33:02",
    province_state => "",
    recovered      => 4,
  },
  {
    confirmed      => 18,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-06T02:13:15",
    province_state => "Qinghai",
    recovered      => 3,
  },
  {
    confirmed      => 18,
    country_region => "Malaysia",
    deaths         => 0,
    last_update    => "2020-02-10T03:03:09",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 18,
    country_region => "Taiwan",
    deaths         => 0,
    last_update    => "2020-02-09T09:13:11",
    province_state => "Taiwan",
    recovered      => 1,
  },
  {
    confirmed      => 14,
    country_region => "Germany",
    deaths         => 0,
    last_update    => "2020-02-09T06:13:11",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 14,
    country_region => "Vietnam",
    deaths         => 0,
    last_update    => "2020-02-10T03:03:09",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 11,
    country_region => "France",
    deaths         => 0,
    last_update    => "2020-02-08T09:53:01",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 10,
    country_region => "Macau",
    deaths         => 0,
    last_update    => "2020-02-06T14:23:04",
    province_state => "Macau",
    recovered      => 1,
  },
  {
    confirmed      => 8,
    country_region => "UK",
    deaths         => 0,
    last_update    => "2020-02-10T19:03:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 8,
    country_region => "United Arab Emirates",
    deaths         => 0,
    last_update    => "2020-02-10T23:03:09",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 5,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-09T19:33:02",
    province_state => "Queensland",
    recovered      => 0,
  },
  {
    confirmed      => 4,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-06T03:13:22",
    province_state => "New South Wales",
    recovered      => 2,
  },
  {
    confirmed      => 4,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-01T18:12:49",
    province_state => "Victoria",
    recovered      => 0,
  },
  {
    confirmed      => 4,
    country_region => "Canada",
    deaths         => 0,
    last_update    => "2020-02-07T05:43:03",
    province_state => "British Columbia",
    recovered      => 0,
  },
  {
    confirmed      => 3,
    country_region => "India",
    deaths         => 0,
    last_update    => "2020-02-03T21:43:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 3,
    country_region => "Italy",
    deaths         => 0,
    last_update    => "2020-02-07T17:53:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 3,
    country_region => "Philippines",
    deaths         => 1,
    last_update    => "2020-02-07T16:43:04",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-02T22:33:07",
    province_state => "South Australia",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "Canada",
    deaths         => 0,
    last_update    => "2020-02-04T00:13:06",
    province_state => "Toronto, ON",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "Russia",
    deaths         => 0,
    last_update    => "2020-01-31T16:13:45",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "Spain",
    deaths         => 0,
    last_update    => "2020-02-09T20:33:03",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-09T19:03:03",
    province_state => "Chicago, IL",
    recovered      => 2,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-03T03:53:02",
    province_state => "San Benito, CA",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-03T00:43:02",
    province_state => "Santa Clara, CA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Belgium",
    deaths         => 0,
    last_update    => "2020-02-04T15:43:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Cambodia",
    deaths         => 0,
    last_update    => "2020-01-31T08:15:53",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Canada",
    deaths         => 0,
    last_update    => "2020-02-04T00:03:11",
    province_state => "London, ON",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Finland",
    deaths         => 0,
    last_update    => "2020-01-31T08:15:53",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-01T01:52:40",
    province_state => "Tibet",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Nepal",
    deaths         => 0,
    last_update    => "2020-01-31T08:15:53",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Sri Lanka",
    deaths         => 0,
    last_update    => "2020-02-08T03:43:03",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Sweden",
    deaths         => 0,
    last_update    => "2020-02-01T02:13:26",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:43:03",
    province_state => "Boston, MA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:53:03",
    province_state => "Los Angeles, CA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-05T21:53:02",
    province_state => "Madison, WI",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:53:03",
    province_state => "Orange, CA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-09T07:03:04",
    province_state => "Seattle, WA",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:43:03",
    province_state => "Tempe, AZ",
    recovered      => 0,
  },
]