[
  {
    confirmed      => 59989,
    country_region => "Mainland China",
    deaths         => 1789,
    last_update    => "2020-02-17T23:13:06",
    province_state => "Hubei",
    recovered      => 7862,
  },
  {
    confirmed      => 1322,
    country_region => "Mainland China",
    deaths         => 4,
    last_update    => "2020-02-17T12:43:02",
    province_state => "Guangdong",
    recovered      => 524,
  },
  {
    confirmed      => 1246,
    country_region => "Mainland China",
    deaths         => 16,
    last_update    => "2020-02-17T14:53:02",
    province_state => "Henan",
    recovered      => 509,
  },
  {
    confirmed      => 1171,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-17T11:23:06",
    province_state => "Zhejiang",
    recovered      => 507,
  },
  {
    confirmed      => 1006,
    country_region => "Mainland China",
    deaths         => 3,
    last_update    => "2020-02-17T11:43:01",
    province_state => "Hunan",
    recovered      => 498,
  },
  {
    confirmed      => 973,
    country_region => "Mainland China",
    deaths         => 6,
    last_update    => "2020-02-17T09:13:07",
    province_state => "Anhui",
    recovered      => 280,
  },
  {
    confirmed      => 930,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-17T01:33:02",
    province_state => "Jiangxi",
    recovered      => 275,
  },
  {
    confirmed      => 626,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-17T10:23:04",
    province_state => "Jiangsu",
    recovered      => 258,
  },
  {
    confirmed      => 553,
    country_region => "Mainland China",
    deaths         => 5,
    last_update    => "2020-02-17T23:13:06",
    province_state => "Chongqing",
    recovered      => 225,
  },
  {
    confirmed      => 541,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-17T11:03:06",
    province_state => "Shandong",
    recovered      => 191,
  },
  {
    confirmed      => 495,
    country_region => "Mainland China",
    deaths         => 3,
    last_update    => "2020-02-17T13:13:09",
    province_state => "Sichuan",
    recovered      => 156,
  },
  {
    confirmed      => 457,
    country_region => "Mainland China",
    deaths         => 11,
    last_update    => "2020-02-17T08:03:06",
    province_state => "Heilongjiang",
    recovered      => 85,
  },
  {
    confirmed      => 454,
    country_region => "Others",
    deaths         => 0,
    last_update    => "2020-02-17T14:33:04",
    province_state => "Diamond Princess cruise ship",
    recovered      => 0,
  },
  {
    confirmed      => 381,
    country_region => "Mainland China",
    deaths         => 4,
    last_update    => "2020-02-17T01:23:02",
    province_state => "Beijing",
    recovered      => 114,
  },
  {
    confirmed      => 333,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-17T23:53:02",
    province_state => "Shanghai",
    recovered      => 161,
  },
  {
    confirmed      => 301,
    country_region => "Mainland China",
    deaths         => 3,
    last_update    => "2020-02-17T13:03:06",
    province_state => "Hebei",
    recovered      => 122,
  },
  {
    confirmed      => 290,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-17T10:23:04",
    province_state => "Fujian",
    recovered      => 90,
  },
  {
    confirmed      => 240,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-17T11:43:01",
    province_state => "Shaanxi",
    recovered      => 79,
  },
  {
    confirmed      => 238,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-17T10:23:04",
    province_state => "Guangxi",
    recovered      => 53,
  },
  {
    confirmed      => 171,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-17T10:23:04",
    province_state => "Yunnan",
    recovered      => 47,
  },
  {
    confirmed      => 163,
    country_region => "Mainland China",
    deaths         => 4,
    last_update    => "2020-02-17T11:03:06",
    province_state => "Hainan",
    recovered      => 59,
  },
  {
    confirmed      => 146,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-17T11:13:16",
    province_state => "Guizhou",
    recovered      => 57,
  },
  {
    confirmed      => 130,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-17T22:53:01",
    province_state => "Shanxi",
    recovered      => 53,
  },
  {
    confirmed      => 125,
    country_region => "Mainland China",
    deaths         => 3,
    last_update    => "2020-02-17T12:43:02",
    province_state => "Tianjin",
    recovered      => 46,
  },
  {
    confirmed      => 121,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-17T11:13:16",
    province_state => "Liaoning",
    recovered      => 43,
  },
  {
    confirmed      => 91,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-17T14:53:02",
    province_state => "Gansu",
    recovered      => 58,
  },
  {
    confirmed      => 89,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-17T11:03:06",
    province_state => "Jilin",
    recovered      => 34,
  },
  {
    confirmed      => 77,
    country_region => "Singapore",
    deaths         => 0,
    last_update    => "2020-02-17T14:33:04",
    province_state => "",
    recovered      => 24,
  },
  {
    confirmed      => 75,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-17T01:53:01",
    province_state => "Xinjiang",
    recovered      => 12,
  },
  {
    confirmed      => 72,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-17T02:03:06",
    province_state => "Inner Mongolia",
    recovered      => 8,
  },
  {
    confirmed      => 70,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-17T11:03:06",
    province_state => "Ningxia",
    recovered      => 35,
  },
  {
    confirmed      => 66,
    country_region => "Japan",
    deaths         => 1,
    last_update    => "2020-02-17T14:33:04",
    province_state => "",
    recovered      => 12,
  },
  {
    confirmed      => 60,
    country_region => "Hong Kong",
    deaths         => 1,
    last_update    => "2020-02-17T22:53:01",
    province_state => "Hong Kong",
    recovered      => 2,
  },
  {
    confirmed      => 35,
    country_region => "Thailand",
    deaths         => 0,
    last_update    => "2020-02-17T07:33:02",
    province_state => "",
    recovered      => 15,
  },
  {
    confirmed      => 30,
    country_region => "South Korea",
    deaths         => 0,
    last_update    => "2020-02-17T23:43:01",
    province_state => "",
    recovered      => 10,
  },
  {
    confirmed      => 22,
    country_region => "Malaysia",
    deaths         => 0,
    last_update    => "2020-02-15T23:43:02",
    province_state => "",
    recovered      => 7,
  },
  {
    confirmed      => 22,
    country_region => "Taiwan",
    deaths         => 1,
    last_update    => "2020-02-17T15:43:02",
    province_state => "Taiwan",
    recovered      => 2,
  },
  {
    confirmed      => 18,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-15T08:43:03",
    province_state => "Qinghai",
    recovered      => 13,
  },
  {
    confirmed      => 16,
    country_region => "Germany",
    deaths         => 0,
    last_update    => "2020-02-13T15:13:11",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 16,
    country_region => "Vietnam",
    deaths         => 0,
    last_update    => "2020-02-13T06:33:02",
    province_state => "",
    recovered      => 7,
  },
  {
    confirmed      => 12,
    country_region => "France",
    deaths         => 1,
    last_update    => "2020-02-15T20:53:02",
    province_state => "",
    recovered      => 4,
  },
  {
    confirmed      => 10,
    country_region => "Macau",
    deaths         => 0,
    last_update    => "2020-02-16T12:03:06",
    province_state => "Macau",
    recovered      => 5,
  },
  {
    confirmed      => 9,
    country_region => "UK",
    deaths         => 0,
    last_update    => "2020-02-16T16:23:06",
    province_state => "",
    recovered      => 8,
  },
  {
    confirmed      => 9,
    country_region => "United Arab Emirates",
    deaths         => 0,
    last_update    => "2020-02-16T20:43:02",
    province_state => "",
    recovered      => 4,
  },
  {
    confirmed      => 5,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-09T19:33:02",
    province_state => "Queensland",
    recovered      => 0,
  },
  {
    confirmed      => 5,
    country_region => "Canada",
    deaths         => 0,
    last_update    => "2020-02-17T08:03:07",
    province_state => "British Columbia",
    recovered      => 0,
  },
  {
    confirmed      => 4,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-13T17:53:03",
    province_state => "New South Wales",
    recovered      => 4,
  },
  {
    confirmed      => 4,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-13T17:53:03",
    province_state => "Victoria",
    recovered      => 4,
  },
  {
    confirmed      => 3,
    country_region => "India",
    deaths         => 0,
    last_update    => "2020-02-16T07:43:02",
    province_state => "",
    recovered      => 3,
  },
  {
    confirmed      => 3,
    country_region => "Italy",
    deaths         => 0,
    last_update    => "2020-02-07T17:53:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 3,
    country_region => "Philippines",
    deaths         => 1,
    last_update    => "2020-02-12T07:43:02",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 2,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-17T08:13:09",
    province_state => "South Australia",
    recovered      => 2,
  },
  {
    confirmed      => 2,
    country_region => "Canada",
    deaths         => 0,
    last_update    => "2020-02-04T00:13:06",
    province_state => "Toronto, ON",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "Russia",
    deaths         => 0,
    last_update    => "2020-02-12T14:43:03",
    province_state => "",
    recovered      => 2,
  },
  {
    confirmed      => 2,
    country_region => "Spain",
    deaths         => 0,
    last_update    => "2020-02-15T17:23:04",
    province_state => "",
    recovered      => 2,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-09T19:03:03",
    province_state => "Chicago, IL",
    recovered      => 2,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-03T03:53:02",
    province_state => "San Benito, CA",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-13T03:13:08",
    province_state => "San Diego County, CA",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-03T00:43:02",
    province_state => "Santa Clara, CA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Belgium",
    deaths         => 0,
    last_update    => "2020-02-17T04:23:06",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Cambodia",
    deaths         => 0,
    last_update    => "2020-02-12T07:43:02",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Canada",
    deaths         => 0,
    last_update    => "2020-02-12T18:53:03",
    province_state => "London, ON",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Egypt",
    deaths         => 0,
    last_update    => "2020-02-14T23:53:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Finland",
    deaths         => 0,
    last_update    => "2020-02-12T00:03:12",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-12T06:43:02",
    province_state => "Tibet",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Nepal",
    deaths         => 0,
    last_update    => "2020-02-12T14:43:03",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Sri Lanka",
    deaths         => 0,
    last_update    => "2020-02-08T03:43:03",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Sweden",
    deaths         => 0,
    last_update    => "2020-02-01T02:13:26",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:43:03",
    province_state => "Boston, MA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:53:03",
    province_state => "Los Angeles, CA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-05T21:53:02",
    province_state => "Madison, WI",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:53:03",
    province_state => "Orange, CA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-13T18:53:02",
    province_state => "San Antonio, TX",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-09T07:03:04",
    province_state => "Seattle, WA",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:43:03",
    province_state => "Tempe, AZ",
    recovered      => 0,
  },
]