[
  {
    confirmed      => 1,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/22/2020 17:00",
    province_state => "Anhui",
    recovered      => "",
  },
  {
    confirmed      => 14,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/22/2020 17:00",
    province_state => "Beijing",
    recovered      => "",
  },
  {
    confirmed      => 6,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/22/2020 17:00",
    province_state => "Chongqing",
    recovered      => "",
  },
  {
    confirmed      => 1,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/22/2020 17:00",
    province_state => "Fujian",
    recovered      => "",
  },
  {
    confirmed      => "",
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/22/2020 17:00",
    province_state => "Gansu",
    recovered      => "",
  },
  {
    confirmed      => 26,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/22/2020 17:00",
    province_state => "Guangdong",
    recovered      => "",
  },
  {
    confirmed      => 2,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/22/2020 17:00",
    province_state => "Guangxi",
    recovered      => "",
  },
  {
    confirmed      => 1,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/22/2020 17:00",
    province_state => "Guizhou",
    recovered      => "",
  },
  {
    confirmed      => 4,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/22/2020 17:00",
    province_state => "Hainan",
    recovered      => "",
  },
  {
    confirmed      => 1,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/22/2020 17:00",
    province_state => "Hebei",
    recovered      => "",
  },
  {
    confirmed      => "",
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/22/2020 17:00",
    province_state => "Heilongjiang",
    recovered      => "",
  },
  {
    confirmed      => 5,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/22/2020 17:00",
    province_state => "Henan",
    recovered      => "",
  },
  {
    confirmed      => "",
    country_region => "Hong Kong",
    deaths         => "",
    last_update    => "1/22/2020 17:00",
    province_state => "Hong Kong",
    recovered      => "",
  },
  {
    confirmed      => 444,
    country_region => "Mainland China",
    deaths         => 17,
    last_update    => "1/22/2020 17:00",
    province_state => "Hubei",
    recovered      => 28,
  },
  {
    confirmed      => 4,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/22/2020 17:00",
    province_state => "Hunan",
    recovered      => "",
  },
  {
    confirmed      => "",
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/22/2020 17:00",
    province_state => "Inner Mongolia",
    recovered      => "",
  },
  {
    confirmed      => 1,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/22/2020 17:00",
    province_state => "Jiangsu",
    recovered      => "",
  },
  {
    confirmed      => 2,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/22/2020 17:00",
    province_state => "Jiangxi",
    recovered      => "",
  },
  {
    confirmed      => "",
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/22/2020 17:00",
    province_state => "Jilin",
    recovered      => "",
  },
  {
    confirmed      => 2,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/22/2020 17:00",
    province_state => "Liaoning",
    recovered      => "",
  },
  {
    confirmed      => 1,
    country_region => "Macau",
    deaths         => "",
    last_update    => "1/22/2020 17:00",
    province_state => "Macau",
    recovered      => "",
  },
  {
    confirmed      => 1,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/22/2020 17:00",
    province_state => "Ningxia",
    recovered      => "",
  },
  {
    confirmed      => "",
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/22/2020 17:00",
    province_state => "Qinghai",
    recovered      => "",
  },
  {
    confirmed      => "",
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/22/2020 17:00",
    province_state => "Shaanxi",
    recovered      => "",
  },
  {
    confirmed      => 2,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/22/2020 17:00",
    province_state => "Shandong",
    recovered      => "",
  },
  {
    confirmed      => 9,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/22/2020 17:00",
    province_state => "Shanghai",
    recovered      => "",
  },
  {
    confirmed      => 1,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/22/2020 17:00",
    province_state => "Shanxi",
    recovered      => "",
  },
  {
    confirmed      => 5,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/22/2020 17:00",
    province_state => "Sichuan",
    recovered      => "",
  },
  {
    confirmed      => 1,
    country_region => "Taiwan",
    deaths         => "",
    last_update    => "1/22/2020 17:00",
    province_state => "Taiwan",
    recovered      => "",
  },
  {
    confirmed      => 4,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/22/2020 17:00",
    province_state => "Tianjin",
    recovered      => "",
  },
  {
    confirmed      => "",
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/22/2020 17:00",
    province_state => "Tibet",
    recovered      => "",
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => "",
    last_update    => "1/22/2020 17:00",
    province_state => "Washington",
    recovered      => "",
  },
  {
    confirmed      => "",
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/22/2020 17:00",
    province_state => "Xinjiang",
    recovered      => "",
  },
  {
    confirmed      => 1,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/22/2020 17:00",
    province_state => "Yunnan",
    recovered      => "",
  },
  {
    confirmed      => 10,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/22/2020 17:00",
    province_state => "Zhejiang",
    recovered      => "",
  },
  {
    confirmed      => 2,
    country_region => "Japan",
    deaths         => "",
    last_update    => "1/22/2020 17:00",
    province_state => "",
    recovered      => "",
  },
  {
    confirmed      => 2,
    country_region => "Thailand",
    deaths         => "",
    last_update    => "1/22/2020 17:00",
    province_state => "",
    recovered      => "",
  },
  {
    confirmed      => 1,
    country_region => "South Korea",
    deaths         => "",
    last_update    => "1/22/2020 17:00",
    province_state => "",
    recovered      => "",
  },
]