[
  {
    confirmed      => 1058,
    country_region => "Mainland China",
    deaths         => 52,
    last_update    => "1/26/20 16:00",
    province_state => "Hubei",
    recovered      => 42,
  },
  {
    confirmed      => 111,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/26/20 16:00",
    province_state => "Guangdong",
    recovered      => 2,
  },
  {
    confirmed      => 104,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/26/20 16:00",
    province_state => "Zhejiang",
    recovered      => 1,
  },
  {
    confirmed      => 83,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "1/26/20 16:00",
    province_state => "Henan",
    recovered      => "",
  },
  {
    confirmed      => 75,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/26/20 16:00",
    province_state => "Chongqing",
    recovered      => "",
  },
  {
    confirmed      => 69,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/26/20 16:00",
    province_state => "Hunan",
    recovered      => "",
  },
  {
    confirmed      => 68,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/26/20 16:00",
    province_state => "Beijing",
    recovered      => 2,
  },
  {
    confirmed      => 60,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/26/20 16:00",
    province_state => "Anhui",
    recovered      => "",
  },
  {
    confirmed      => 46,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/26/20 16:00",
    province_state => "Shandong",
    recovered      => "",
  },
  {
    confirmed      => 44,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/26/20 16:00",
    province_state => "Sichuan",
    recovered      => "",
  },
  {
    confirmed      => 40,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "1/26/20 16:00",
    province_state => "Shanghai",
    recovered      => 1,
  },
  {
    confirmed      => 36,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/26/20 16:00",
    province_state => "Guangxi",
    recovered      => "",
  },
  {
    confirmed      => 36,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/26/20 16:00",
    province_state => "Jiangxi",
    recovered      => "",
  },
  {
    confirmed      => 35,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/26/20 16:00",
    province_state => "Fujian",
    recovered      => "",
  },
  {
    confirmed      => 33,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/26/20 16:00",
    province_state => "Jiangsu",
    recovered      => 1,
  },
  {
    confirmed      => 22,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/26/20 16:00",
    province_state => "Hainan",
    recovered      => "",
  },
  {
    confirmed      => 22,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/26/20 16:00",
    province_state => "Shaanxi",
    recovered      => "",
  },
  {
    confirmed      => 21,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/26/20 16:00",
    province_state => "Liaoning",
    recovered      => "",
  },
  {
    confirmed      => 16,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/26/20 16:00",
    province_state => "Yunnan",
    recovered      => "",
  },
  {
    confirmed      => 15,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "1/26/20 16:00",
    province_state => "Heilongjiang",
    recovered      => "",
  },
  {
    confirmed      => 14,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/26/20 16:00",
    province_state => "Tianjin",
    recovered      => "",
  },
  {
    confirmed      => 13,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "1/26/20 16:00",
    province_state => "Hebei",
    recovered      => "",
  },
  {
    confirmed      => 9,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/26/20 16:00",
    province_state => "Shanxi",
    recovered      => "",
  },
  {
    confirmed      => 8,
    country_region => "Hong Kong",
    deaths         => "",
    last_update    => "1/26/20 16:00",
    province_state => "Hong Kong",
    recovered      => "",
  },
  {
    confirmed      => 7,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/26/20 16:00",
    province_state => "Inner Mongolia",
    recovered      => "",
  },
  {
    confirmed      => 7,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/26/20 16:00",
    province_state => "Gansu",
    recovered      => "",
  },
  {
    confirmed      => 5,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/26/20 16:00",
    province_state => "Guizhou",
    recovered      => "",
  },
  {
    confirmed      => 5,
    country_region => "Macau",
    deaths         => "",
    last_update    => "1/26/20 16:00",
    province_state => "Macau",
    recovered      => "",
  },
  {
    confirmed      => 4,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/26/20 16:00",
    province_state => "Ningxia",
    recovered      => "",
  },
  {
    confirmed      => 4,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/26/20 16:00",
    province_state => "Jilin",
    recovered      => "",
  },
  {
    confirmed      => 4,
    country_region => "Taiwan",
    deaths         => "",
    last_update    => "1/26/20 16:00",
    province_state => "Taiwan",
    recovered      => "",
  },
  {
    confirmed      => 4,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/26/20 16:00",
    province_state => "Xinjiang",
    recovered      => "",
  },
  {
    confirmed      => 1,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/26/20 16:00",
    province_state => "Qinghai",
    recovered      => "",
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => "",
    last_update    => "1/26/20 16:00",
    province_state => "Washington",
    recovered      => "",
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => "",
    last_update    => "1/26/20 16:00",
    province_state => "Illinois",
    recovered      => "",
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => "",
    last_update    => "1/26/20 16:00",
    province_state => "California",
    recovered      => "",
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => "",
    last_update    => "1/26/20 16:00",
    province_state => "Arizona",
    recovered      => "",
  },
  {
    confirmed      => 4,
    country_region => "Japan",
    deaths         => "",
    last_update    => "1/26/20 16:00",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 8,
    country_region => "Thailand",
    deaths         => "",
    last_update    => "1/26/20 16:00",
    province_state => "",
    recovered      => 2,
  },
  {
    confirmed      => 3,
    country_region => "South Korea",
    deaths         => "",
    last_update    => "1/26/20 16:00",
    province_state => "",
    recovered      => "",
  },
  {
    confirmed      => 4,
    country_region => "Singapore",
    deaths         => "",
    last_update    => "1/26/20 16:00",
    province_state => "",
    recovered      => "",
  },
  {
    confirmed      => 2,
    country_region => "Vietnam",
    deaths         => "",
    last_update    => "1/26/20 16:00",
    province_state => "",
    recovered      => "",
  },
  {
    confirmed      => 3,
    country_region => "France",
    deaths         => "",
    last_update    => "1/26/20 16:00",
    province_state => "",
    recovered      => "",
  },
  {
    confirmed      => 4,
    country_region => "Australia",
    deaths         => "",
    last_update    => "1/26/20 16:00",
    province_state => "",
    recovered      => "",
  },
  {
    confirmed      => 1,
    country_region => "Nepal",
    deaths         => "",
    last_update    => "1/26/20 16:00",
    province_state => "",
    recovered      => "",
  },
  {
    confirmed      => 4,
    country_region => "Malaysia",
    deaths         => "",
    last_update    => "1/26/20 16:00",
    province_state => "",
    recovered      => "",
  },
  {
    confirmed      => 1,
    country_region => "Canada",
    deaths         => "",
    last_update    => "1/26/20 16:00",
    province_state => "Ontario",
    recovered      => "",
  },
]