[
  {
    confirmed      => 761,
    country_region => "Mainland China",
    deaths         => 40,
    last_update    => "1/25/20 17:00",
    province_state => "Hubei",
    recovered      => 32,
  },
  {
    confirmed      => 78,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/25/20 17:00",
    province_state => "Guangdong",
    recovered      => 2,
  },
  {
    confirmed      => 62,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/25/20 17:00",
    province_state => "Zhejiang",
    recovered      => 1,
  },
  {
    confirmed      => 57,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/25/20 17:00",
    province_state => "Chongqing",
    recovered      => "",
  },
  {
    confirmed      => 43,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/25/20 17:00",
    province_state => "Hunan",
    recovered      => "",
  },
  {
    confirmed      => 41,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/25/20 17:00",
    province_state => "Beijing",
    recovered      => 2,
  },
  {
    confirmed      => 39,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/25/20 17:00",
    province_state => "Anhui",
    recovered      => "",
  },
  {
    confirmed      => 33,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/25/20 17:00",
    province_state => "Shanghai",
    recovered      => 1,
  },
  {
    confirmed      => 32,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/25/20 17:00",
    province_state => "Henan",
    recovered      => "",
  },
  {
    confirmed      => 28,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/25/20 17:00",
    province_state => "Sichuan",
    recovered      => "",
  },
  {
    confirmed      => 27,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/25/20 17:00",
    province_state => "Shandong",
    recovered      => "",
  },
  {
    confirmed      => 23,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/25/20 17:00",
    province_state => "Guangxi",
    recovered      => "",
  },
  {
    confirmed      => 19,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/25/20 17:00",
    province_state => "Hainan",
    recovered      => "",
  },
  {
    confirmed      => 18,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/25/20 17:00",
    province_state => "Jiangxi",
    recovered      => "",
  },
  {
    confirmed      => 18,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/25/20 17:00",
    province_state => "Fujian",
    recovered      => "",
  },
  {
    confirmed      => 18,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/25/20 17:00",
    province_state => "Jiangsu",
    recovered      => 1,
  },
  {
    confirmed      => 17,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/25/20 17:00",
    province_state => "Liaoning",
    recovered      => "",
  },
  {
    confirmed      => 15,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/25/20 17:00",
    province_state => "Shaanxi",
    recovered      => "",
  },
  {
    confirmed      => 11,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/25/20 17:00",
    province_state => "Yunnan",
    recovered      => "",
  },
  {
    confirmed      => 10,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/25/20 17:00",
    province_state => "Tianjin",
    recovered      => "",
  },
  {
    confirmed      => 9,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "1/25/20 17:00",
    province_state => "Heilongjiang",
    recovered      => "",
  },
  {
    confirmed      => 8,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "1/25/20 17:00",
    province_state => "Hebei",
    recovered      => "",
  },
  {
    confirmed      => 7,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/25/20 17:00",
    province_state => "Inner Mongolia",
    recovered      => "",
  },
  {
    confirmed      => 6,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/25/20 17:00",
    province_state => "Shanxi",
    recovered      => "",
  },
  {
    confirmed      => 5,
    country_region => "Hong Kong",
    deaths         => "",
    last_update    => "1/25/20 17:00",
    province_state => "Hong Kong",
    recovered      => "",
  },
  {
    confirmed      => 4,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/25/20 17:00",
    province_state => "Guizhou",
    recovered      => "",
  },
  {
    confirmed      => 4,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/25/20 17:00",
    province_state => "Jilin",
    recovered      => "",
  },
  {
    confirmed      => 4,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/25/20 17:00",
    province_state => "Gansu",
    recovered      => "",
  },
  {
    confirmed      => 3,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/25/20 17:00",
    province_state => "Ningxia",
    recovered      => "",
  },
  {
    confirmed      => 3,
    country_region => "Taiwan",
    deaths         => "",
    last_update    => "1/25/20 17:00",
    province_state => "Taiwan",
    recovered      => "",
  },
  {
    confirmed      => 3,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/25/20 17:00",
    province_state => "Xinjiang",
    recovered      => "",
  },
  {
    confirmed      => 2,
    country_region => "Macau",
    deaths         => "",
    last_update    => "1/25/20 17:00",
    province_state => "Macau",
    recovered      => "",
  },
  {
    confirmed      => 1,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/25/20 17:00",
    province_state => "Qinghai",
    recovered      => "",
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => "",
    last_update    => "1/25/20 17:00",
    province_state => "Washington",
    recovered      => "",
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => "",
    last_update    => "1/25/20 17:00",
    province_state => "Illinois",
    recovered      => "",
  },
  {
    confirmed      => 2,
    country_region => "Japan",
    deaths         => "",
    last_update    => "1/25/20 17:00",
    province_state => "",
    recovered      => "",
  },
  {
    confirmed      => 7,
    country_region => "Thailand",
    deaths         => "",
    last_update    => "1/25/20 17:00",
    province_state => "",
    recovered      => "",
  },
  {
    confirmed      => 2,
    country_region => "South Korea",
    deaths         => "",
    last_update    => "1/25/20 17:00",
    province_state => "",
    recovered      => "",
  },
  {
    confirmed      => 3,
    country_region => "Singapore",
    deaths         => "",
    last_update    => "1/25/20 17:00",
    province_state => "",
    recovered      => "",
  },
  {
    confirmed      => 2,
    country_region => "Vietnam",
    deaths         => "",
    last_update    => "1/25/20 17:00",
    province_state => "",
    recovered      => "",
  },
  {
    confirmed      => 3,
    country_region => "France",
    deaths         => "",
    last_update    => "1/25/20 17:00",
    province_state => "",
    recovered      => "",
  },
  {
    confirmed      => 4,
    country_region => "Australia",
    deaths         => "",
    last_update    => "1/25/20 17:00",
    province_state => "",
    recovered      => "",
  },
  {
    confirmed      => 1,
    country_region => "Nepal",
    deaths         => "",
    last_update    => "1/25/20 17:00",
    province_state => "",
    recovered      => "",
  },
  {
    confirmed      => 3,
    country_region => "Malaysia",
    deaths         => "",
    last_update    => "1/25/20 17:00",
    province_state => "",
    recovered      => "",
  },
]