[
  {
    confirmed      => 62662,
    country_region => "Mainland China",
    deaths         => 2144,
    last_update    => "2020-02-21T13:03:09",
    province_state => "Hubei",
    recovered      => 11881,
  },
  {
    confirmed      => 1333,
    country_region => "Mainland China",
    deaths         => 5,
    last_update    => "2020-02-21T10:13:09",
    province_state => "Guangdong",
    recovered      => 690,
  },
  {
    confirmed      => 1267,
    country_region => "Mainland China",
    deaths         => 19,
    last_update    => "2020-02-21T13:43:02",
    province_state => "Henan",
    recovered      => 736,
  },
  {
    confirmed      => 1203,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-21T10:23:02",
    province_state => "Zhejiang",
    recovered      => 679,
  },
  {
    confirmed      => 1011,
    country_region => "Mainland China",
    deaths         => 4,
    last_update    => "2020-02-21T15:13:07",
    province_state => "Hunan",
    recovered      => 661,
  },
  {
    confirmed      => 988,
    country_region => "Mainland China",
    deaths         => 6,
    last_update    => "2020-02-21T10:13:09",
    province_state => "Anhui",
    recovered      => 539,
  },
  {
    confirmed      => 934,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-21T01:13:05",
    province_state => "Jiangxi",
    recovered      => 489,
  },
  {
    confirmed      => 749,
    country_region => "Mainland China",
    deaths         => 4,
    last_update    => "2020-02-21T10:23:02",
    province_state => "Shandong",
    recovered      => 281,
  },
  {
    confirmed      => 634,
    country_region => "Others",
    deaths         => 2,
    last_update    => "2020-02-20T15:53:03",
    province_state => "Diamond Princess cruise ship",
    recovered      => 1,
  },
  {
    confirmed      => 631,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-21T11:43:01",
    province_state => "Jiangsu",
    recovered      => 373,
  },
  {
    confirmed      => 572,
    country_region => "Mainland China",
    deaths         => 6,
    last_update    => "2020-02-21T23:13:14",
    province_state => "Chongqing",
    recovered      => 316,
  },
  {
    confirmed      => 525,
    country_region => "Mainland China",
    deaths         => 3,
    last_update    => "2020-02-21T12:53:01",
    province_state => "Sichuan",
    recovered      => 231,
  },
  {
    confirmed      => 479,
    country_region => "Mainland China",
    deaths         => 12,
    last_update    => "2020-02-21T11:43:01",
    province_state => "Heilongjiang",
    recovered      => 175,
  },
  {
    confirmed      => 396,
    country_region => "Mainland China",
    deaths         => 4,
    last_update    => "2020-02-21T01:03:09",
    province_state => "Beijing",
    recovered      => 169,
  },
  {
    confirmed      => 334,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-21T05:53:01",
    province_state => "Shanghai",
    recovered      => 211,
  },
  {
    confirmed      => 308,
    country_region => "Mainland China",
    deaths         => 5,
    last_update    => "2020-02-21T12:53:01",
    province_state => "Hebei",
    recovered      => 184,
  },
  {
    confirmed      => 293,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-21T11:43:01",
    province_state => "Fujian",
    recovered      => 149,
  },
  {
    confirmed      => 246,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-21T11:43:01",
    province_state => "Guangxi",
    recovered      => 97,
  },
  {
    confirmed      => 245,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-21T11:43:01",
    province_state => "Shaanxi",
    recovered      => 134,
  },
  {
    confirmed      => 204,
    country_region => "South Korea",
    deaths         => 2,
    last_update    => "2020-02-21T13:43:02",
    province_state => "",
    recovered      => 16,
  },
  {
    confirmed      => 174,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-21T06:23:04",
    province_state => "Yunnan",
    recovered      => 96,
  },
  {
    confirmed      => 168,
    country_region => "Mainland China",
    deaths         => 4,
    last_update    => "2020-02-21T10:13:09",
    province_state => "Hainan",
    recovered      => 95,
  },
  {
    confirmed      => 146,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-21T12:53:01",
    province_state => "Guizhou",
    recovered      => 77,
  },
  {
    confirmed      => 132,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-21T23:33:06",
    province_state => "Shanxi",
    recovered      => 78,
  },
  {
    confirmed      => 132,
    country_region => "Mainland China",
    deaths         => 3,
    last_update    => "2020-02-21T12:53:01",
    province_state => "Tianjin",
    recovered      => 62,
  },
  {
    confirmed      => 121,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-21T01:33:02",
    province_state => "Liaoning",
    recovered      => 61,
  },
  {
    confirmed      => 105,
    country_region => "Japan",
    deaths         => 1,
    last_update    => "2020-02-21T19:03:06",
    province_state => "",
    recovered      => 22,
  },
  {
    confirmed      => 91,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-21T15:13:07",
    province_state => "Gansu",
    recovered      => 76,
  },
  {
    confirmed      => 91,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-21T10:13:09",
    province_state => "Jilin",
    recovered      => 45,
  },
  {
    confirmed      => 85,
    country_region => "Singapore",
    deaths         => 0,
    last_update    => "2020-02-21T03:43:02",
    province_state => "",
    recovered      => 37,
  },
  {
    confirmed      => 76,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-21T13:43:02",
    province_state => "Xinjiang",
    recovered      => 24,
  },
  {
    confirmed      => 75,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-21T08:03:15",
    province_state => "Inner Mongolia",
    recovered      => 17,
  },
  {
    confirmed      => 71,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-21T06:23:04",
    province_state => "Ningxia",
    recovered      => 48,
  },
  {
    confirmed      => 68,
    country_region => "Hong Kong",
    deaths         => 2,
    last_update    => "2020-02-21T03:43:02",
    province_state => "Hong Kong",
    recovered      => 5,
  },
  {
    confirmed      => 35,
    country_region => "Thailand",
    deaths         => 0,
    last_update    => "2020-02-21T18:53:02",
    province_state => "",
    recovered      => 17,
  },
  {
    confirmed      => 26,
    country_region => "Taiwan",
    deaths         => 1,
    last_update    => "2020-02-21T06:53:03",
    province_state => "Taiwan",
    recovered      => 2,
  },
  {
    confirmed      => 22,
    country_region => "Malaysia",
    deaths         => 0,
    last_update    => "2020-02-19T09:33:03",
    province_state => "",
    recovered      => 15,
  },
  {
    confirmed      => 20,
    country_region => "Italy",
    deaths         => 1,
    last_update    => "2020-02-21T23:33:06",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 18,
    country_region => "Iran",
    deaths         => 4,
    last_update    => "2020-02-21T18:53:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 18,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-21T04:43:02",
    province_state => "Qinghai",
    recovered      => 18,
  },
  {
    confirmed      => 16,
    country_region => "Germany",
    deaths         => 0,
    last_update    => "2020-02-21T23:03:13",
    province_state => "",
    recovered      => 14,
  },
  {
    confirmed      => 16,
    country_region => "Vietnam",
    deaths         => 0,
    last_update    => "2020-02-21T06:03:04",
    province_state => "",
    recovered      => 14,
  },
  {
    confirmed      => 12,
    country_region => "France",
    deaths         => 1,
    last_update    => "2020-02-15T20:53:02",
    province_state => "",
    recovered      => 4,
  },
  {
    confirmed      => 11,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-21T23:23:06",
    province_state => "Ashland, NE",
    recovered      => 0,
  },
  {
    confirmed      => 10,
    country_region => "Macau",
    deaths         => 0,
    last_update    => "2020-02-20T02:13:19",
    province_state => "Macau",
    recovered      => 6,
  },
  {
    confirmed      => 9,
    country_region => "UK",
    deaths         => 0,
    last_update    => "2020-02-16T16:23:06",
    province_state => "",
    recovered      => 8,
  },
  {
    confirmed      => 9,
    country_region => "United Arab Emirates",
    deaths         => 0,
    last_update    => "2020-02-16T20:43:02",
    province_state => "",
    recovered      => 4,
  },
  {
    confirmed      => 6,
    country_region => "Canada",
    deaths         => 0,
    last_update    => "2020-02-21T05:23:04",
    province_state => "British Columbia",
    recovered      => 0,
  },
  {
    confirmed      => 5,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-21T05:43:02",
    province_state => "Queensland",
    recovered      => 1,
  },
  {
    confirmed      => 5,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-21T23:23:06",
    province_state => "Travis, CA",
    recovered      => 0,
  },
  {
    confirmed      => 4,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-21T23:03:13",
    province_state => "From Diamond Princess",
    recovered      => 0,
  },
  {
    confirmed      => 4,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-13T17:53:03",
    province_state => "New South Wales",
    recovered      => 4,
  },
  {
    confirmed      => 4,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-13T17:53:03",
    province_state => "Victoria",
    recovered      => 4,
  },
  {
    confirmed      => 3,
    country_region => "India",
    deaths         => 0,
    last_update    => "2020-02-16T07:43:02",
    province_state => "",
    recovered      => 3,
  },
  {
    confirmed      => 3,
    country_region => "Philippines",
    deaths         => 1,
    last_update    => "2020-02-12T07:43:02",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 2,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-17T08:13:09",
    province_state => "South Australia",
    recovered      => 2,
  },
  {
    confirmed      => 2,
    country_region => "Canada",
    deaths         => 0,
    last_update    => "2020-02-21T05:23:04",
    province_state => "Toronto, ON",
    recovered      => 2,
  },
  {
    confirmed      => 2,
    country_region => "Russia",
    deaths         => 0,
    last_update    => "2020-02-12T14:43:03",
    province_state => "",
    recovered      => 2,
  },
  {
    confirmed      => 2,
    country_region => "Spain",
    deaths         => 0,
    last_update    => "2020-02-15T17:23:04",
    province_state => "",
    recovered      => 2,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-09T19:03:03",
    province_state => "Chicago, IL",
    recovered      => 2,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-21T23:23:06",
    province_state => "Lackland, TX",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-03T03:53:02",
    province_state => "San Benito, CA",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-21T05:43:02",
    province_state => "San Diego County, CA",
    recovered      => 1,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-21T05:23:04",
    province_state => "Santa Clara, CA",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Belgium",
    deaths         => 0,
    last_update    => "2020-02-17T04:23:06",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Cambodia",
    deaths         => 0,
    last_update    => "2020-02-12T07:43:02",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Canada",
    deaths         => 0,
    last_update    => "2020-02-12T18:53:03",
    province_state => "London, ON",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Egypt",
    deaths         => 0,
    last_update    => "2020-02-21T18:53:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Finland",
    deaths         => 0,
    last_update    => "2020-02-12T00:03:12",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Israel",
    deaths         => 0,
    last_update    => "2020-02-21T15:33:03",
    province_state => "From Diamond Princess",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Lebanon",
    deaths         => 0,
    last_update    => "2020-02-21T15:33:03",
    province_state => "None",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-12T06:43:02",
    province_state => "Tibet",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Nepal",
    deaths         => 0,
    last_update    => "2020-02-12T14:43:03",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Sri Lanka",
    deaths         => 0,
    last_update    => "2020-02-08T03:43:03",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Sweden",
    deaths         => 0,
    last_update    => "2020-02-01T02:13:26",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:43:03",
    province_state => "Boston, MA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-21T05:13:09",
    province_state => "Humboldt County, CA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:53:03",
    province_state => "Los Angeles, CA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-05T21:53:02",
    province_state => "Madison, WI",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:53:03",
    province_state => "Orange, CA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-21T23:13:16",
    province_state => "Sacramento County, CA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-13T18:53:02",
    province_state => "San Antonio, TX",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-09T07:03:04",
    province_state => "Seattle, WA",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:43:03",
    province_state => "Tempe, AZ",
    recovered      => 0,
  },
]