[
  {
    confirmed      => 24953,
    country_region => "Mainland China",
    deaths         => 699,
    last_update    => "2020-02-07T23:43:02",
    province_state => "Hubei",
    recovered      => 1115,
  },
  {
    confirmed      => 1034,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-07T10:13:06",
    province_state => "Guangdong",
    recovered      => 88,
  },
  {
    confirmed      => 1006,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-07T11:33:11",
    province_state => "Zhejiang",
    recovered      => 123,
  },
  {
    confirmed      => 914,
    country_region => "Mainland China",
    deaths         => 3,
    last_update    => "2020-02-07T14:03:12",
    province_state => "Henan",
    recovered      => 86,
  },
  {
    confirmed      => 772,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-07T11:33:11",
    province_state => "Hunan",
    recovered      => 112,
  },
  {
    confirmed      => 665,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-07T05:13:07",
    province_state => "Anhui",
    recovered      => 47,
  },
  {
    confirmed      => 661,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-07T01:23:02",
    province_state => "Jiangxi",
    recovered      => 45,
  },
  {
    confirmed      => 426,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-07T23:33:02",
    province_state => "Chongqing",
    recovered      => 31,
  },
  {
    confirmed      => 408,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-07T14:03:12",
    province_state => "Jiangsu",
    recovered      => 43,
  },
  {
    confirmed      => 386,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-07T11:33:11",
    province_state => "Shandong",
    recovered      => 37,
  },
  {
    confirmed      => 344,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-07T08:23:09",
    province_state => "Sichuan",
    recovered      => 42,
  },
  {
    confirmed      => 297,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-07T03:23:02",
    province_state => "Beijing",
    recovered      => 33,
  },
  {
    confirmed      => 277,
    country_region => "Mainland China",
    deaths         => 3,
    last_update    => "2020-02-07T07:43:02",
    province_state => "Heilongjiang",
    recovered      => 12,
  },
  {
    confirmed      => 277,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-07T06:14:15",
    province_state => "Shanghai",
    recovered      => 30,
  },
  {
    confirmed      => 224,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-07T13:23:03",
    province_state => "Fujian",
    recovered      => 20,
  },
  {
    confirmed      => 184,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-07T08:23:09",
    province_state => "Shaanxi",
    recovered      => 17,
  },
  {
    confirmed      => 172,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-07T00:33:02",
    province_state => "Guangxi",
    recovered      => 17,
  },
  {
    confirmed      => 172,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-07T12:03:04",
    province_state => "Hebei",
    recovered      => 22,
  },
  {
    confirmed      => 138,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-07T23:23:04",
    province_state => "Yunnan",
    recovered      => 12,
  },
  {
    confirmed      => 117,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-07T12:33:02",
    province_state => "Hainan",
    recovered      => 10,
  },
  {
    confirmed      => 104,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-07T23:43:02",
    province_state => "Shanxi",
    recovered      => 15,
  },
  {
    confirmed      => 99,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-07T15:33:03",
    province_state => "Liaoning",
    recovered      => 7,
  },
  {
    confirmed      => 81,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-07T11:13:07",
    province_state => "Guizhou",
    recovered      => 6,
  },
  {
    confirmed      => 81,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-07T05:43:03",
    province_state => "Tianjin",
    recovered      => 2,
  },
  {
    confirmed      => 67,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-07T02:33:06",
    province_state => "Gansu",
    recovered      => 9,
  },
  {
    confirmed      => 65,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-07T00:43:02",
    province_state => "Jilin",
    recovered      => 4,
  },
  {
    confirmed      => 61,
    country_region => "Others",
    deaths         => 0,
    last_update    => "2020-02-07T16:33:03",
    province_state => "Cruise Ship",
    recovered      => 0,
  },
  {
    confirmed      => 50,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-07T11:13:07",
    province_state => "Inner Mongolia",
    recovered      => 5,
  },
  {
    confirmed      => 43,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-07T11:13:07",
    province_state => "Ningxia",
    recovered      => 5,
  },
  {
    confirmed      => 39,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-07T01:43:02",
    province_state => "Xinjiang",
    recovered      => 0,
  },
  {
    confirmed      => 30,
    country_region => "Singapore",
    deaths         => 0,
    last_update    => "2020-02-07T03:03:03",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 25,
    country_region => "Hong Kong",
    deaths         => 1,
    last_update    => "2020-02-07T11:53:02",
    province_state => "Hong Kong",
    recovered      => 0,
  },
  {
    confirmed      => 25,
    country_region => "Japan",
    deaths         => 0,
    last_update    => "2020-02-07T04:13:20",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 25,
    country_region => "Thailand",
    deaths         => 0,
    last_update    => "2020-02-04T15:33:03",
    province_state => "",
    recovered      => 5,
  },
  {
    confirmed      => 24,
    country_region => "South Korea",
    deaths         => 0,
    last_update    => "2020-02-07T03:03:03",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 18,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-06T02:13:15",
    province_state => "Qinghai",
    recovered      => 3,
  },
  {
    confirmed      => 16,
    country_region => "Taiwan",
    deaths         => 0,
    last_update    => "2020-02-06T15:03:04",
    province_state => "Taiwan",
    recovered      => 1,
  },
  {
    confirmed      => 13,
    country_region => "Germany",
    deaths         => 0,
    last_update    => "2020-02-07T16:33:03",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 12,
    country_region => "Malaysia",
    deaths         => 0,
    last_update    => "2020-02-07T09:13:21",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 10,
    country_region => "Macau",
    deaths         => 0,
    last_update    => "2020-02-06T14:23:04",
    province_state => "Macau",
    recovered      => 1,
  },
  {
    confirmed      => 10,
    country_region => "Vietnam",
    deaths         => 0,
    last_update    => "2020-02-06T01:13:08",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 6,
    country_region => "France",
    deaths         => 0,
    last_update    => "2020-02-01T01:52:40",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 5,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-07T01:03:02",
    province_state => "Queensland",
    recovered      => 0,
  },
  {
    confirmed      => 5,
    country_region => "United Arab Emirates",
    deaths         => 0,
    last_update    => "2020-02-02T05:43:01",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 4,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-06T03:13:22",
    province_state => "New South Wales",
    recovered      => 2,
  },
  {
    confirmed      => 4,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-01T18:12:49",
    province_state => "Victoria",
    recovered      => 0,
  },
  {
    confirmed      => 4,
    country_region => "Canada",
    deaths         => 0,
    last_update    => "2020-02-07T05:43:03",
    province_state => "British Columbia",
    recovered      => 0,
  },
  {
    confirmed      => 3,
    country_region => "India",
    deaths         => 0,
    last_update    => "2020-02-03T21:43:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 3,
    country_region => "Italy",
    deaths         => 0,
    last_update    => "2020-02-07T17:53:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 3,
    country_region => "Philippines",
    deaths         => 1,
    last_update    => "2020-02-07T16:43:04",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 3,
    country_region => "UK",
    deaths         => 0,
    last_update    => "2020-02-07T18:33:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-02T22:33:07",
    province_state => "South Australia",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "Canada",
    deaths         => 0,
    last_update    => "2020-02-04T00:13:06",
    province_state => "Toronto, ON",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "Russia",
    deaths         => 0,
    last_update    => "2020-01-31T16:13:45",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:43:03",
    province_state => "Chicago, IL",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-03T03:53:02",
    province_state => "San Benito, CA",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-03T00:43:02",
    province_state => "Santa Clara, CA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Belgium",
    deaths         => 0,
    last_update    => "2020-02-04T15:43:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Cambodia",
    deaths         => 0,
    last_update    => "2020-01-31T08:15:53",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Canada",
    deaths         => 0,
    last_update    => "2020-02-04T00:03:11",
    province_state => "London, ON",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Finland",
    deaths         => 0,
    last_update    => "2020-01-31T08:15:53",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-01T01:52:40",
    province_state => "Tibet",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Nepal",
    deaths         => 0,
    last_update    => "2020-01-31T08:15:53",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Spain",
    deaths         => 0,
    last_update    => "2020-02-01T23:43:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Sri Lanka",
    deaths         => 0,
    last_update    => "2020-01-31T08:15:53",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Sweden",
    deaths         => 0,
    last_update    => "2020-02-01T02:13:26",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:43:03",
    province_state => "Boston, MA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:53:03",
    province_state => "Los Angeles, CA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-05T21:53:02",
    province_state => "Madison, WI",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:53:03",
    province_state => "Orange, CA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:43:03",
    province_state => "Seattle, WA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:43:03",
    province_state => "Tempe, AZ",
    recovered      => 0,
  },
]