[
  {
    confirmed      => 22112,
    country_region => "Mainland China",
    deaths         => 618,
    last_update    => "2020-02-06T23:23:02",
    province_state => "Hubei",
    recovered      => 817,
  },
  {
    confirmed      => 970,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-06T12:43:02",
    province_state => "Guangdong",
    recovered      => 69,
  },
  {
    confirmed      => 954,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-06T10:53:04",
    province_state => "Zhejiang",
    recovered      => 94,
  },
  {
    confirmed      => 851,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-06T11:23:14",
    province_state => "Henan",
    recovered      => 56,
  },
  {
    confirmed      => 711,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-06T13:13:06",
    province_state => "Hunan",
    recovered      => 81,
  },
  {
    confirmed      => 600,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-06T02:33:01",
    province_state => "Jiangxi",
    recovered      => 37,
  },
  {
    confirmed      => 591,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-06T13:33:02",
    province_state => "Anhui",
    recovered      => 34,
  },
  {
    confirmed      => 411,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-06T23:33:02",
    province_state => "Chongqing",
    recovered      => 24,
  },
  {
    confirmed      => 373,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-06T08:03:10",
    province_state => "Jiangsu",
    recovered      => 34,
  },
  {
    confirmed      => 347,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-06T07:53:02",
    province_state => "Shandong",
    recovered      => 27,
  },
  {
    confirmed      => 321,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-06T08:03:10",
    province_state => "Sichuan",
    recovered      => 31,
  },
  {
    confirmed      => 274,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-06T03:23:11",
    province_state => "Beijing",
    recovered      => 31,
  },
  {
    confirmed      => 257,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-06T06:53:07",
    province_state => "Shanghai",
    recovered      => 25,
  },
  {
    confirmed      => 227,
    country_region => "Mainland China",
    deaths         => 3,
    last_update    => "2020-02-06T08:13:06",
    province_state => "Heilongjiang",
    recovered      => 8,
  },
  {
    confirmed      => 215,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-06T11:03:19",
    province_state => "Fujian",
    recovered      => 14,
  },
  {
    confirmed      => 173,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-06T13:53:02",
    province_state => "Shaanxi",
    recovered      => 9,
  },
  {
    confirmed      => 168,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-06T04:13:13",
    province_state => "Guangxi",
    recovered      => 14,
  },
  {
    confirmed      => 157,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-06T13:53:02",
    province_state => "Hebei",
    recovered      => 13,
  },
  {
    confirmed      => 133,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-06T09:43:02",
    province_state => "Yunnan",
    recovered      => 7,
  },
  {
    confirmed      => 106,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-06T11:13:24",
    province_state => "Hainan",
    recovered      => 8,
  },
  {
    confirmed      => 96,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-06T23:03:02",
    province_state => "Shanxi",
    recovered      => 12,
  },
  {
    confirmed      => 94,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-06T14:33:02",
    province_state => "Liaoning",
    recovered      => 5,
  },
  {
    confirmed      => 79,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-06T23:43:01",
    province_state => "Tianjin",
    recovered      => 2,
  },
  {
    confirmed      => 71,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-06T09:53:02",
    province_state => "Guizhou",
    recovered      => 6,
  },
  {
    confirmed      => 62,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-05T16:23:06",
    province_state => "Gansu",
    recovered      => 6,
  },
  {
    confirmed      => 59,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-06T14:23:04",
    province_state => "Jilin",
    recovered      => 4,
  },
  {
    confirmed      => 46,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-06T02:23:08",
    province_state => "Inner Mongolia",
    recovered      => 4,
  },
  {
    confirmed      => 45,
    country_region => "Japan",
    deaths         => 0,
    last_update    => "2020-02-06T02:53:03",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 40,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-06T02:13:15",
    province_state => "Ningxia",
    recovered      => 1,
  },
  {
    confirmed      => 36,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-06T01:13:08",
    province_state => "Xinjiang",
    recovered      => 0,
  },
  {
    confirmed      => 28,
    country_region => "Singapore",
    deaths         => 0,
    last_update    => "2020-02-05T16:33:03",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 25,
    country_region => "Thailand",
    deaths         => 0,
    last_update    => "2020-02-04T15:33:03",
    province_state => "",
    recovered      => 5,
  },
  {
    confirmed      => 24,
    country_region => "Hong Kong",
    deaths         => 1,
    last_update    => "2020-02-06T14:43:02",
    province_state => "Hong Kong",
    recovered      => 0,
  },
  {
    confirmed      => 23,
    country_region => "South Korea",
    deaths         => 0,
    last_update    => "2020-02-06T02:53:03",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 18,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-06T02:13:15",
    province_state => "Qinghai",
    recovered      => 3,
  },
  {
    confirmed      => 16,
    country_region => "Taiwan",
    deaths         => 0,
    last_update    => "2020-02-06T15:03:04",
    province_state => "Taiwan",
    recovered      => 1,
  },
  {
    confirmed      => 12,
    country_region => "Germany",
    deaths         => 0,
    last_update    => "2020-02-03T20:53:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 12,
    country_region => "Malaysia",
    deaths         => 0,
    last_update    => "2020-02-05T15:43:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 10,
    country_region => "Macau",
    deaths         => 0,
    last_update    => "2020-02-06T14:23:04",
    province_state => "Macau",
    recovered      => 1,
  },
  {
    confirmed      => 10,
    country_region => "Vietnam",
    deaths         => 0,
    last_update    => "2020-02-06T01:13:08",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 6,
    country_region => "France",
    deaths         => 0,
    last_update    => "2020-02-01T01:52:40",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 5,
    country_region => "United Arab Emirates",
    deaths         => 0,
    last_update    => "2020-02-02T05:43:01",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 4,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-06T03:13:22",
    province_state => "New South Wales",
    recovered      => 2,
  },
  {
    confirmed      => 4,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-06T02:53:03",
    province_state => "Queensland",
    recovered      => 0,
  },
  {
    confirmed      => 4,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-01T18:12:49",
    province_state => "Victoria",
    recovered      => 0,
  },
  {
    confirmed      => 3,
    country_region => "India",
    deaths         => 0,
    last_update    => "2020-02-03T21:43:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-02T22:33:07",
    province_state => "South Australia",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "Canada",
    deaths         => 0,
    last_update    => "2020-02-05T17:33:03",
    province_state => "British Columbia",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "Canada",
    deaths         => 0,
    last_update    => "2020-02-04T00:13:06",
    province_state => "Toronto, ON",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "Italy",
    deaths         => 0,
    last_update    => "2020-01-31T08:15:53",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "Philippines",
    deaths         => 1,
    last_update    => "2020-02-02T03:33:07",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "Russia",
    deaths         => 0,
    last_update    => "2020-01-31T16:13:45",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "UK",
    deaths         => 0,
    last_update    => "2020-02-01T01:52:40",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:43:03",
    province_state => "Chicago, IL",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-03T03:53:02",
    province_state => "San Benito, CA",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-03T00:43:02",
    province_state => "Santa Clara, CA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Belgium",
    deaths         => 0,
    last_update    => "2020-02-04T15:43:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Cambodia",
    deaths         => 0,
    last_update    => "2020-01-31T08:15:53",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Canada",
    deaths         => 0,
    last_update    => "2020-02-04T00:03:11",
    province_state => "London, ON",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Finland",
    deaths         => 0,
    last_update    => "2020-01-31T08:15:53",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-01T01:52:40",
    province_state => "Tibet",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Nepal",
    deaths         => 0,
    last_update    => "2020-01-31T08:15:53",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Spain",
    deaths         => 0,
    last_update    => "2020-02-01T23:43:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Sri Lanka",
    deaths         => 0,
    last_update    => "2020-01-31T08:15:53",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Sweden",
    deaths         => 0,
    last_update    => "2020-02-01T02:13:26",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:43:03",
    province_state => "Boston, MA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:53:03",
    province_state => "Los Angeles, CA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-05T21:53:02",
    province_state => "Madison, WI",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:53:03",
    province_state => "Orange, CA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:43:03",
    province_state => "Seattle, WA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:43:03",
    province_state => "Tempe, AZ",
    recovered      => 0,
  },
]