[
  {
    confirmed      => 27100,
    country_region => "Mainland China",
    deaths         => 780,
    last_update    => "2020-02-08T23:33:06",
    province_state => "Hubei",
    recovered      => 1439,
  },
  {
    confirmed      => 1095,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-08T11:53:01",
    province_state => "Guangdong",
    recovered      => 112,
  },
  {
    confirmed      => 1048,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-08T10:53:02",
    province_state => "Zhejiang",
    recovered      => 175,
  },
  {
    confirmed      => 981,
    country_region => "Mainland China",
    deaths         => 4,
    last_update    => "2020-02-08T14:13:12",
    province_state => "Henan",
    recovered      => 116,
  },
  {
    confirmed      => 803,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-08T12:53:01",
    province_state => "Hunan",
    recovered      => 156,
  },
  {
    confirmed      => 733,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-08T07:43:02",
    province_state => "Anhui",
    recovered      => 59,
  },
  {
    confirmed      => 698,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-08T01:23:02",
    province_state => "Jiangxi",
    recovered      => 55,
  },
  {
    confirmed      => 439,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-08T10:23:04",
    province_state => "Jiangsu",
    recovered      => 51,
  },
  {
    confirmed      => 428,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-08T11:03:15",
    province_state => "Chongqing",
    recovered      => 39,
  },
  {
    confirmed      => 416,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-08T11:33:02",
    province_state => "Shandong",
    recovered      => 44,
  },
  {
    confirmed      => 364,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-08T15:23:04",
    province_state => "Sichuan",
    recovered      => 60,
  },
  {
    confirmed      => 315,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-08T03:13:09",
    province_state => "Beijing",
    recovered      => 34,
  },
  {
    confirmed      => 295,
    country_region => "Mainland China",
    deaths         => 5,
    last_update    => "2020-02-08T04:03:09",
    province_state => "Heilongjiang",
    recovered      => 13,
  },
  {
    confirmed      => 286,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-08T06:33:02",
    province_state => "Shanghai",
    recovered      => 41,
  },
  {
    confirmed      => 239,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-08T08:13:10",
    province_state => "Fujian",
    recovered      => 24,
  },
  {
    confirmed      => 195,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-08T11:33:02",
    province_state => "Hebei",
    recovered      => 30,
  },
  {
    confirmed      => 195,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-08T10:13:06",
    province_state => "Shaanxi",
    recovered      => 20,
  },
  {
    confirmed      => 183,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-08T00:23:03",
    province_state => "Guangxi",
    recovered      => 17,
  },
  {
    confirmed      => 138,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-08T08:43:02",
    province_state => "Yunnan",
    recovered      => 17,
  },
  {
    confirmed      => 124,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-08T10:23:04",
    province_state => "Hainan",
    recovered      => 14,
  },
  {
    confirmed      => 115,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-08T23:53:02",
    province_state => "Shanxi",
    recovered      => 21,
  },
  {
    confirmed      => 105,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-08T11:53:01",
    province_state => "Liaoning",
    recovered      => 8,
  },
  {
    confirmed      => 89,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-08T06:43:03",
    province_state => "Guizhou",
    recovered      => 7,
  },
  {
    confirmed      => 88,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-08T08:23:04",
    province_state => "Tianjin",
    recovered      => 4,
  },
  {
    confirmed      => 79,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-08T15:13:14",
    province_state => "Gansu",
    recovered      => 12,
  },
  {
    confirmed      => 69,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-08T00:13:04",
    province_state => "Jilin",
    recovered      => 4,
  },
  {
    confirmed      => 61,
    country_region => "Others",
    deaths         => 0,
    last_update    => "2020-02-07T16:33:03",
    province_state => "Cruise Ship",
    recovered      => 0,
  },
  {
    confirmed      => 52,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-08T03:33:02",
    province_state => "Inner Mongolia",
    recovered      => 5,
  },
  {
    confirmed      => 45,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-08T09:13:16",
    province_state => "Ningxia",
    recovered      => 15,
  },
  {
    confirmed      => 42,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-08T03:23:10",
    province_state => "Xinjiang",
    recovered      => 0,
  },
  {
    confirmed      => 33,
    country_region => "Singapore",
    deaths         => 0,
    last_update    => "2020-02-08T12:53:01",
    province_state => "",
    recovered      => 2,
  },
  {
    confirmed      => 32,
    country_region => "Thailand",
    deaths         => 0,
    last_update    => "2020-02-08T12:53:01",
    province_state => "",
    recovered      => 10,
  },
  {
    confirmed      => 26,
    country_region => "Hong Kong",
    deaths         => 1,
    last_update    => "2020-02-08T00:03:07",
    province_state => "Hong Kong",
    recovered      => 0,
  },
  {
    confirmed      => 25,
    country_region => "Japan",
    deaths         => 0,
    last_update    => "2020-02-07T04:13:20",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 24,
    country_region => "South Korea",
    deaths         => 0,
    last_update    => "2020-02-07T03:03:03",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 18,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-06T02:13:15",
    province_state => "Qinghai",
    recovered      => 3,
  },
  {
    confirmed      => 17,
    country_region => "Taiwan",
    deaths         => 0,
    last_update    => "2020-02-08T05:23:02",
    province_state => "Taiwan",
    recovered      => 1,
  },
  {
    confirmed      => 16,
    country_region => "Malaysia",
    deaths         => 0,
    last_update    => "2020-02-08T10:23:04",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 13,
    country_region => "Germany",
    deaths         => 0,
    last_update    => "2020-02-07T16:33:03",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 13,
    country_region => "Vietnam",
    deaths         => 0,
    last_update    => "2020-02-08T07:23:04",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 11,
    country_region => "France",
    deaths         => 0,
    last_update    => "2020-02-08T09:53:01",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 10,
    country_region => "Macau",
    deaths         => 0,
    last_update    => "2020-02-06T14:23:04",
    province_state => "Macau",
    recovered      => 1,
  },
  {
    confirmed      => 7,
    country_region => "United Arab Emirates",
    deaths         => 0,
    last_update    => "2020-02-08T07:03:16",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 5,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-07T01:03:02",
    province_state => "Queensland",
    recovered      => 0,
  },
  {
    confirmed      => 4,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-06T03:13:22",
    province_state => "New South Wales",
    recovered      => 2,
  },
  {
    confirmed      => 4,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-01T18:12:49",
    province_state => "Victoria",
    recovered      => 0,
  },
  {
    confirmed      => 4,
    country_region => "Canada",
    deaths         => 0,
    last_update    => "2020-02-07T05:43:03",
    province_state => "British Columbia",
    recovered      => 0,
  },
  {
    confirmed      => 3,
    country_region => "India",
    deaths         => 0,
    last_update    => "2020-02-03T21:43:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 3,
    country_region => "Italy",
    deaths         => 0,
    last_update    => "2020-02-07T17:53:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 3,
    country_region => "Philippines",
    deaths         => 1,
    last_update    => "2020-02-07T16:43:04",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 3,
    country_region => "UK",
    deaths         => 0,
    last_update    => "2020-02-07T18:33:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-02T22:33:07",
    province_state => "South Australia",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "Canada",
    deaths         => 0,
    last_update    => "2020-02-04T00:13:06",
    province_state => "Toronto, ON",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "Russia",
    deaths         => 0,
    last_update    => "2020-01-31T16:13:45",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:43:03",
    province_state => "Chicago, IL",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-03T03:53:02",
    province_state => "San Benito, CA",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-03T00:43:02",
    province_state => "Santa Clara, CA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Belgium",
    deaths         => 0,
    last_update    => "2020-02-04T15:43:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Cambodia",
    deaths         => 0,
    last_update    => "2020-01-31T08:15:53",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Canada",
    deaths         => 0,
    last_update    => "2020-02-04T00:03:11",
    province_state => "London, ON",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Finland",
    deaths         => 0,
    last_update    => "2020-01-31T08:15:53",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-01T01:52:40",
    province_state => "Tibet",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Nepal",
    deaths         => 0,
    last_update    => "2020-01-31T08:15:53",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Spain",
    deaths         => 0,
    last_update    => "2020-02-01T23:43:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Sri Lanka",
    deaths         => 0,
    last_update    => "2020-02-08T03:43:03",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Sweden",
    deaths         => 0,
    last_update    => "2020-02-01T02:13:26",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:43:03",
    province_state => "Boston, MA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:53:03",
    province_state => "Los Angeles, CA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-05T21:53:02",
    province_state => "Madison, WI",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:53:03",
    province_state => "Orange, CA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:43:03",
    province_state => "Seattle, WA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:43:03",
    province_state => "Tempe, AZ",
    recovered      => 0,
  },
]