[
  {
    confirmed      => 5806,
    country_region => "Mainland China",
    deaths         => 204,
    last_update    => "1/31/2020 23:59",
    province_state => "Hubei",
    recovered      => 141,
  },
  {
    confirmed      => 538,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/31/2020 23:59",
    province_state => "Zhejiang",
    recovered      => 14,
  },
  {
    confirmed      => 436,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/31/2020 23:59",
    province_state => "Guangdong",
    recovered      => 11,
  },
  {
    confirmed      => 352,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "1/31/2020 23:59",
    province_state => "Henan",
    recovered      => 3,
  },
  {
    confirmed      => 332,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/31/2020 23:59",
    province_state => "Hunan",
    recovered      => 2,
  },
  {
    confirmed      => 240,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/31/2020 23:59",
    province_state => "Jiangxi",
    recovered      => 7,
  },
  {
    confirmed      => 237,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/31/2020 23:59",
    province_state => "Anhui",
    recovered      => 3,
  },
  {
    confirmed      => 211,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/31/2020 23:59",
    province_state => "Chongqing",
    recovered      => 1,
  },
  {
    confirmed      => 184,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/31/2020 23:59",
    province_state => "Shandong",
    recovered      => 2,
  },
  {
    confirmed      => 177,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "1/31/2020 23:59",
    province_state => "Sichuan",
    recovered      => 1,
  },
  {
    confirmed      => 168,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/31/2020 23:59",
    province_state => "Jiangsu",
    recovered      => 5,
  },
  {
    confirmed      => 139,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "1/31/2020 23:59",
    province_state => "Beijing",
    recovered      => 5,
  },
  {
    confirmed      => 135,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "1/31/2020 23:59",
    province_state => "Shanghai",
    recovered      => 9,
  },
  {
    confirmed      => 120,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/31/2020 23:59",
    province_state => "Fujian",
    recovered      => "",
  },
  {
    confirmed      => 87,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/31/2020 23:59",
    province_state => "Guangxi",
    recovered      => 2,
  },
  {
    confirmed      => 87,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/31/2020 23:59",
    province_state => "Shaanxi",
    recovered      => "",
  },
  {
    confirmed      => 83,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/31/2020 23:59",
    province_state => "Yunnan",
    recovered      => 1,
  },
  {
    confirmed      => 82,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "1/31/2020 23:59",
    province_state => "Hebei",
    recovered      => "",
  },
  {
    confirmed      => 59,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "1/31/2020 23:59",
    province_state => "Heilongjiang",
    recovered      => "",
  },
  {
    confirmed      => 52,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "1/31/2020 23:59",
    province_state => "Hainan",
    recovered      => 1,
  },
  {
    confirmed      => 48,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/31/2020 23:59",
    province_state => "Liaoning",
    recovered      => 1,
  },
  {
    confirmed      => 39,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/31/2020 23:59",
    province_state => "Shanxi",
    recovered      => 1,
  },
  {
    confirmed      => 32,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/31/2020 23:59",
    province_state => "Tianjin",
    recovered      => "",
  },
  {
    confirmed      => 29,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/31/2020 23:59",
    province_state => "Guizhou",
    recovered      => 2,
  },
  {
    confirmed      => 29,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/31/2020 23:59",
    province_state => "Gansu",
    recovered      => "",
  },
  {
    confirmed      => 21,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/31/2020 23:59",
    province_state => "Ningxia",
    recovered      => "",
  },
  {
    confirmed      => 20,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/31/2020 23:59",
    province_state => "Inner Mongolia",
    recovered      => 1,
  },
  {
    confirmed      => 17,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/31/2020 23:59",
    province_state => "Xinjiang",
    recovered      => "",
  },
  {
    confirmed      => 14,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/31/2020 23:59",
    province_state => "Jilin",
    recovered      => 1,
  },
  {
    confirmed      => 12,
    country_region => "Hong Kong",
    deaths         => "",
    last_update    => "1/31/2020 23:59",
    province_state => "Hong Kong",
    recovered      => "",
  },
  {
    confirmed      => 10,
    country_region => "Taiwan",
    deaths         => "",
    last_update    => "1/31/2020 23:59",
    province_state => "Taiwan",
    recovered      => "",
  },
  {
    confirmed      => 8,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/31/2020 23:59",
    province_state => "Qinghai",
    recovered      => "",
  },
  {
    confirmed      => 7,
    country_region => "Macau",
    deaths         => "",
    last_update    => "1/31/2020 23:59",
    province_state => "Macau",
    recovered      => "",
  },
  {
    confirmed      => 1,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/31/2020 23:59",
    province_state => "Tibet",
    recovered      => "",
  },
  {
    confirmed      => 19,
    country_region => "Thailand",
    deaths         => "",
    last_update    => "1/31/2020 23:59",
    province_state => "",
    recovered      => 5,
  },
  {
    confirmed      => 15,
    country_region => "Japan",
    deaths         => "",
    last_update    => "1/31/2020 23:59",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 13,
    country_region => "Singapore",
    deaths         => "",
    last_update    => "1/31/2020 23:59",
    province_state => "",
    recovered      => "",
  },
  {
    confirmed      => 11,
    country_region => "South Korea",
    deaths         => "",
    last_update    => "1/31/2020 23:59",
    province_state => "",
    recovered      => "",
  },
  {
    confirmed      => 8,
    country_region => "Malaysia",
    deaths         => "",
    last_update    => "1/31/2020 23:59",
    province_state => "",
    recovered      => "",
  },
  {
    confirmed      => 5,
    country_region => "France",
    deaths         => "",
    last_update    => "1/31/2020 23:59",
    province_state => "",
    recovered      => "",
  },
  {
    confirmed      => 5,
    country_region => "Germany",
    deaths         => "",
    last_update    => "1/31/2020 23:59",
    province_state => "Bavaria",
    recovered      => "",
  },
  {
    confirmed      => 4,
    country_region => "Australia",
    deaths         => "",
    last_update    => "1/31/2020 23:59",
    province_state => "New South Wales",
    recovered      => 2,
  },
  {
    confirmed      => 4,
    country_region => "United Arab Emirates",
    deaths         => "",
    last_update    => "1/31/2020 23:59",
    province_state => "",
    recovered      => "",
  },
  {
    confirmed      => 3,
    country_region => "Australia",
    deaths         => "",
    last_update    => "1/31/2020 23:59",
    province_state => "Victoria",
    recovered      => "",
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => "",
    last_update    => "1/31/2020 23:59",
    province_state => "Illinois",
    recovered      => "",
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => "",
    last_update    => "1/31/2020 23:59",
    province_state => "California",
    recovered      => "",
  },
  {
    confirmed      => 2,
    country_region => "Vietnam",
    deaths         => "",
    last_update    => "1/31/2020 23:59",
    province_state => "",
    recovered      => "",
  },
  {
    confirmed      => 2,
    country_region => "Canada",
    deaths         => "",
    last_update    => "1/31/2020 23:59",
    province_state => "Ontario",
    recovered      => "",
  },
  {
    confirmed      => 2,
    country_region => "Australia",
    deaths         => "",
    last_update    => "1/31/2020 23:59",
    province_state => "Queensland",
    recovered      => "",
  },
  {
    confirmed      => 2,
    country_region => "Italy",
    deaths         => "",
    last_update    => "1/31/2020 23:59",
    province_state => "",
    recovered      => "",
  },
  {
    confirmed      => 2,
    country_region => "UK",
    deaths         => "",
    last_update    => "1/31/2020 23:59",
    province_state => "",
    recovered      => "",
  },
  {
    confirmed      => 2,
    country_region => "Russia",
    deaths         => "",
    last_update    => "1/31/2020 23:59",
    province_state => "",
    recovered      => "",
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => "",
    last_update    => "1/31/2020 23:59",
    province_state => "Washington",
    recovered      => "",
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => "",
    last_update    => "1/31/2020 23:59",
    province_state => "Arizona",
    recovered      => "",
  },
  {
    confirmed      => 1,
    country_region => "Nepal",
    deaths         => "",
    last_update    => "1/31/2020 23:59",
    province_state => "",
    recovered      => "",
  },
  {
    confirmed      => 1,
    country_region => "Canada",
    deaths         => "",
    last_update    => "1/31/2020 23:59",
    province_state => "British Columbia",
    recovered      => "",
  },
  {
    confirmed      => 1,
    country_region => "Cambodia",
    deaths         => "",
    last_update    => "1/31/2020 23:59",
    province_state => "",
    recovered      => "",
  },
  {
    confirmed      => 1,
    country_region => "Sri Lanka",
    deaths         => "",
    last_update    => "1/31/2020 23:59",
    province_state => "",
    recovered      => "",
  },
  {
    confirmed      => 1,
    country_region => "Finland",
    deaths         => "",
    last_update    => "1/31/2020 23:59",
    province_state => "",
    recovered      => "",
  },
  {
    confirmed      => 1,
    country_region => "Philippines",
    deaths         => "",
    last_update    => "1/31/2020 23:59",
    province_state => "",
    recovered      => "",
  },
  {
    confirmed      => 1,
    country_region => "India",
    deaths         => "",
    last_update    => "1/31/2020 23:59",
    province_state => "",
    recovered      => "",
  },
  {
    confirmed      => 1,
    country_region => "Sweden",
    deaths         => "",
    last_update    => "1/31/2020 23:59",
    province_state => "",
    recovered      => "",
  },
]