[
  {
    confirmed      => 4903,
    country_region => "Mainland China",
    deaths         => 162,
    last_update    => "1/30/20 16:00",
    province_state => "Hubei",
    recovered      => 90,
  },
  {
    confirmed      => 428,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/30/20 16:00",
    province_state => "Zhejiang",
    recovered      => 4,
  },
  {
    confirmed      => 354,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/30/20 16:00",
    province_state => "Guangdong",
    recovered      => 10,
  },
  {
    confirmed      => 278,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "1/30/20 16:00",
    province_state => "Henan",
    recovered      => 2,
  },
  {
    confirmed      => 277,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/30/20 16:00",
    province_state => "Hunan",
    recovered      => 2,
  },
  {
    confirmed      => 200,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/30/20 16:00",
    province_state => "Anhui",
    recovered      => 2,
  },
  {
    confirmed      => 182,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/30/20 16:00",
    province_state => "Chongqing",
    recovered      => 1,
  },
  {
    confirmed      => 162,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/30/20 16:00",
    province_state => "Jiangxi",
    recovered      => 5,
  },
  {
    confirmed      => 158,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/30/20 16:00",
    province_state => "Shandong",
    recovered      => 1,
  },
  {
    confirmed      => 142,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "1/30/20 16:00",
    province_state => "Sichuan",
    recovered      => 1,
  },
  {
    confirmed      => 129,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/30/20 16:00",
    province_state => "Jiangsu",
    recovered      => 1,
  },
  {
    confirmed      => 114,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "1/30/20 16:00",
    province_state => "Beijing",
    recovered      => 4,
  },
  {
    confirmed      => 112,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "1/30/20 16:00",
    province_state => "Shanghai",
    recovered      => 5,
  },
  {
    confirmed      => 101,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/30/20 16:00",
    province_state => "Fujian",
    recovered      => "",
  },
  {
    confirmed      => 78,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/30/20 16:00",
    province_state => "Guangxi",
    recovered      => 2,
  },
  {
    confirmed      => 70,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/30/20 16:00",
    province_state => "Yunnan",
    recovered      => "",
  },
  {
    confirmed      => 65,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "1/30/20 16:00",
    province_state => "Hebei",
    recovered      => "",
  },
  {
    confirmed      => 63,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/30/20 16:00",
    province_state => "Shaanxi",
    recovered      => "",
  },
  {
    confirmed      => 46,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "1/30/20 16:00",
    province_state => "Hainan",
    recovered      => 1,
  },
  {
    confirmed      => 44,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "1/30/20 16:00",
    province_state => "Heilongjiang",
    recovered      => "",
  },
  {
    confirmed      => 41,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/30/20 16:00",
    province_state => "Liaoning",
    recovered      => 1,
  },
  {
    confirmed      => 35,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/30/20 16:00",
    province_state => "Shanxi",
    recovered      => 1,
  },
  {
    confirmed      => 31,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/30/20 16:00",
    province_state => "Tianjin",
    recovered      => "",
  },
  {
    confirmed      => 26,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/30/20 16:00",
    province_state => "Gansu",
    recovered      => "",
  },
  {
    confirmed      => 19,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/30/20 16:00",
    province_state => "Inner Mongolia",
    recovered      => "",
  },
  {
    confirmed      => 17,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/30/20 16:00",
    province_state => "Ningxia",
    recovered      => "",
  },
  {
    confirmed      => 14,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/30/20 16:00",
    province_state => "Jilin",
    recovered      => 1,
  },
  {
    confirmed      => 14,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/30/20 16:00",
    province_state => "Xinjiang",
    recovered      => "",
  },
  {
    confirmed      => 12,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/30/20 16:00",
    province_state => "Guizhou",
    recovered      => 1,
  },
  {
    confirmed      => 10,
    country_region => "Hong Kong",
    deaths         => "",
    last_update    => "1/30/20 16:00",
    province_state => "Hong Kong",
    recovered      => "",
  },
  {
    confirmed      => 9,
    country_region => "Taiwan",
    deaths         => "",
    last_update    => "1/30/20 16:00",
    province_state => "Taiwan",
    recovered      => "",
  },
  {
    confirmed      => 8,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/30/20 16:00",
    province_state => "Qinghai",
    recovered      => "",
  },
  {
    confirmed      => 7,
    country_region => "Macau",
    deaths         => "",
    last_update    => "1/30/20 16:00",
    province_state => "Macau",
    recovered      => "",
  },
  {
    confirmed      => 1,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/30/20 16:00",
    province_state => "Tibet",
    recovered      => "",
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => "",
    last_update    => "1/30/20 16:00",
    province_state => "Washington",
    recovered      => "",
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => "",
    last_update    => "1/30/20 16:00",
    province_state => "Illinois",
    recovered      => "",
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => "",
    last_update    => "1/30/20 16:00",
    province_state => "California",
    recovered      => "",
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => "",
    last_update    => "1/30/20 16:00",
    province_state => "Arizona",
    recovered      => "",
  },
  {
    confirmed      => 11,
    country_region => "Japan",
    deaths         => "",
    last_update    => "1/30/20 16:00",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 14,
    country_region => "Thailand",
    deaths         => "",
    last_update    => "1/30/20 16:00",
    province_state => "",
    recovered      => 5,
  },
  {
    confirmed      => 4,
    country_region => "South Korea",
    deaths         => "",
    last_update    => "1/30/20 16:00",
    province_state => "",
    recovered      => "",
  },
  {
    confirmed      => 10,
    country_region => "Singapore",
    deaths         => "",
    last_update    => "1/30/20 16:00",
    province_state => "",
    recovered      => "",
  },
  {
    confirmed      => 2,
    country_region => "Vietnam",
    deaths         => "",
    last_update    => "1/30/20 16:00",
    province_state => "",
    recovered      => "",
  },
  {
    confirmed      => 5,
    country_region => "France",
    deaths         => "",
    last_update    => "1/30/20 16:00",
    province_state => "",
    recovered      => "",
  },
  {
    confirmed      => 1,
    country_region => "Nepal",
    deaths         => "",
    last_update    => "1/30/20 16:00",
    province_state => "",
    recovered      => "",
  },
  {
    confirmed      => 8,
    country_region => "Malaysia",
    deaths         => "",
    last_update    => "1/30/20 16:00",
    province_state => "",
    recovered      => "",
  },
  {
    confirmed      => 2,
    country_region => "Canada",
    deaths         => "",
    last_update    => "1/30/20 16:00",
    province_state => "Ontario",
    recovered      => "",
  },
  {
    confirmed      => 1,
    country_region => "Canada",
    deaths         => "",
    last_update    => "1/30/20 16:00",
    province_state => "British Columbia",
    recovered      => "",
  },
  {
    confirmed      => 1,
    country_region => "Cambodia",
    deaths         => "",
    last_update    => "1/30/20 16:00",
    province_state => "",
    recovered      => "",
  },
  {
    confirmed      => 1,
    country_region => "Sri Lanka",
    deaths         => "",
    last_update    => "1/30/20 16:00",
    province_state => "",
    recovered      => "",
  },
  {
    confirmed      => 4,
    country_region => "Australia",
    deaths         => "",
    last_update    => "1/30/20 16:00",
    province_state => "New South Wales",
    recovered      => 2,
  },
  {
    confirmed      => 2,
    country_region => "Australia",
    deaths         => "",
    last_update    => "1/30/20 16:00",
    province_state => "Victoria",
    recovered      => "",
  },
  {
    confirmed      => 3,
    country_region => "Australia",
    deaths         => "",
    last_update    => "1/30/20 16:00",
    province_state => "Queensland",
    recovered      => "",
  },
  {
    confirmed      => 4,
    country_region => "Germany",
    deaths         => "",
    last_update    => "1/30/20 16:00",
    province_state => "Bavaria",
    recovered      => "",
  },
  {
    confirmed      => 1,
    country_region => "Finland",
    deaths         => "",
    last_update    => "1/30/20 16:00",
    province_state => "",
    recovered      => "",
  },
  {
    confirmed      => 4,
    country_region => "United Arab Emirates",
    deaths         => "",
    last_update    => "1/30/20 16:00",
    province_state => "",
    recovered      => "",
  },
  {
    confirmed      => 1,
    country_region => "Philippines",
    deaths         => "",
    last_update    => "1/30/20 16:00",
    province_state => "",
    recovered      => "",
  },
  {
    confirmed      => 1,
    country_region => "India",
    deaths         => "",
    last_update    => "1/30/20 16:00",
    province_state => "",
    recovered      => "",
  },
]