[
  {
    confirmed      => 11177,
    country_region => "Mainland China",
    deaths         => 350,
    last_update    => "2020-02-02T23:43:02",
    province_state => "Hubei",
    recovered      => 295,
  },
  {
    confirmed      => 661,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-02T18:03:05",
    province_state => "Zhejiang",
    recovered      => 32,
  },
  {
    confirmed      => 632,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-02T18:03:05",
    province_state => "Guangdong",
    recovered      => 15,
  },
  {
    confirmed      => 493,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-02T18:03:05",
    province_state => "Henan",
    recovered      => 10,
  },
  {
    confirmed      => 463,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-02T18:03:05",
    province_state => "Hunan",
    recovered      => 16,
  },
  {
    confirmed      => 340,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-02T18:03:05",
    province_state => "Anhui",
    recovered      => 7,
  },
  {
    confirmed      => 333,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-02T18:03:05",
    province_state => "Jiangxi",
    recovered      => 12,
  },
  {
    confirmed      => 300,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-02T23:33:02",
    province_state => "Chongqing",
    recovered      => 7,
  },
  {
    confirmed      => 236,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-02T18:03:05",
    province_state => "Jiangsu",
    recovered      => 7,
  },
  {
    confirmed      => 231,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-02T18:03:05",
    province_state => "Sichuan",
    recovered      => 11,
  },
  {
    confirmed      => 230,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-02T18:03:05",
    province_state => "Shandong",
    recovered      => 6,
  },
  {
    confirmed      => 191,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-02T08:43:02",
    province_state => "Beijing",
    recovered      => 9,
  },
  {
    confirmed      => 182,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-02T05:53:02",
    province_state => "Shanghai",
    recovered      => 10,
  },
  {
    confirmed      => 159,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-02T03:43:01",
    province_state => "Fujian",
    recovered      => 0,
  },
  {
    confirmed      => 116,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-02T03:23:14",
    province_state => "Shaanxi",
    recovered      => 0,
  },
  {
    confirmed      => 111,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-02T00:23:13",
    province_state => "Guangxi",
    recovered      => 2,
  },
  {
    confirmed      => 105,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-02T18:03:05",
    province_state => "Yunnan",
    recovered      => 3,
  },
  {
    confirmed      => 104,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-02T02:53:02",
    province_state => "Hebei",
    recovered      => 3,
  },
  {
    confirmed      => 95,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-02T03:23:14",
    province_state => "Heilongjiang",
    recovered      => 2,
  },
  {
    confirmed      => 70,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-02T18:03:05",
    province_state => "Liaoning",
    recovered      => 1,
  },
  {
    confirmed      => 66,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-02T23:23:13",
    province_state => "Shanxi",
    recovered      => 3,
  },
  {
    confirmed      => 64,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-02T18:03:05",
    province_state => "Hainan",
    recovered      => 4,
  },
  {
    confirmed      => 51,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-02T23:43:02",
    province_state => "Gansu",
    recovered      => 3,
  },
  {
    confirmed      => 48,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-02T09:43:01",
    province_state => "Tianjin",
    recovered      => 1,
  },
  {
    confirmed      => 38,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-02T01:03:32",
    province_state => "Guizhou",
    recovered      => 2,
  },
  {
    confirmed      => 28,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-02T01:43:02",
    province_state => "Ningxia",
    recovered      => 0,
  },
  {
    confirmed      => 27,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-02T03:43:01",
    province_state => "Inner Mongolia",
    recovered      => 1,
  },
  {
    confirmed      => 23,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-02T02:33:02",
    province_state => "Jilin",
    recovered      => 1,
  },
  {
    confirmed      => 21,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-02T00:43:02",
    province_state => "Xinjiang",
    recovered      => 0,
  },
  {
    confirmed      => 20,
    country_region => "Japan",
    deaths         => 0,
    last_update    => "2020-02-01T18:53:03",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 19,
    country_region => "Thailand",
    deaths         => 0,
    last_update    => "2020-01-31T10:37:00",
    province_state => "",
    recovered      => 5,
  },
  {
    confirmed      => 18,
    country_region => "Singapore",
    deaths         => 0,
    last_update    => "2020-02-02T01:03:32",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 15,
    country_region => "Hong Kong",
    deaths         => 0,
    last_update    => "2020-02-02T23:53:02",
    province_state => "Hong Kong",
    recovered      => 0,
  },
  {
    confirmed      => 15,
    country_region => "South Korea",
    deaths         => 0,
    last_update    => "2020-02-02T02:23:13",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 11,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-02T05:33:03",
    province_state => "Qinghai",
    recovered      => 0,
  },
  {
    confirmed      => 10,
    country_region => "Germany",
    deaths         => 0,
    last_update    => "2020-02-02T18:03:05",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 10,
    country_region => "Taiwan",
    deaths         => 0,
    last_update    => "2020-01-31T15:20:56",
    province_state => "Taiwan",
    recovered      => 0,
  },
  {
    confirmed      => 8,
    country_region => "Macau",
    deaths         => 0,
    last_update    => "2020-02-02T04:23:14",
    province_state => "Macau",
    recovered      => 0,
  },
  {
    confirmed      => 8,
    country_region => "Malaysia",
    deaths         => 0,
    last_update    => "2020-01-31T08:15:53",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 6,
    country_region => "France",
    deaths         => 0,
    last_update    => "2020-02-01T01:52:40",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 6,
    country_region => "Vietnam",
    deaths         => 0,
    last_update    => "2020-02-01T07:38:12",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 5,
    country_region => "United Arab Emirates",
    deaths         => 0,
    last_update    => "2020-02-02T05:43:01",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 4,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-01T18:12:49",
    province_state => "New South Wales",
    recovered      => 2,
  },
  {
    confirmed      => 4,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-01T18:12:49",
    province_state => "Victoria",
    recovered      => 0,
  },
  {
    confirmed      => 3,
    country_region => "Canada",
    deaths         => 0,
    last_update    => "2020-02-01T18:12:49",
    province_state => "Ontario",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-02T22:33:07",
    province_state => "Queensland",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-02T22:33:07",
    province_state => "South Australia",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "India",
    deaths         => 0,
    last_update    => "2020-02-02T06:03:08",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "Italy",
    deaths         => 0,
    last_update    => "2020-01-31T08:15:53",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "Philippines",
    deaths         => 1,
    last_update    => "2020-02-02T03:33:07",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "Russia",
    deaths         => 0,
    last_update    => "2020-01-31T16:13:45",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "UK",
    deaths         => 0,
    last_update    => "2020-02-01T01:52:40",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:43:03",
    province_state => "Chicago, IL",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Cambodia",
    deaths         => 0,
    last_update    => "2020-01-31T08:15:53",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Canada",
    deaths         => 0,
    last_update    => "2020-02-01T18:12:49",
    province_state => "British Columbia",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Finland",
    deaths         => 0,
    last_update    => "2020-01-31T08:15:53",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-01T01:52:40",
    province_state => "Tibet",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Nepal",
    deaths         => 0,
    last_update    => "2020-01-31T08:15:53",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Spain",
    deaths         => 0,
    last_update    => "2020-02-01T23:43:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Sri Lanka",
    deaths         => 0,
    last_update    => "2020-01-31T08:15:53",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Sweden",
    deaths         => 0,
    last_update    => "2020-02-01T02:13:26",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:43:03",
    province_state => "Boston, MA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:53:03",
    province_state => "Los Angeles, CA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:53:03",
    province_state => "Orange, CA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:53:03",
    province_state => "Santa Clara, CA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:43:03",
    province_state => "Seattle, WA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:43:03",
    province_state => "Tempe, AZ",
    recovered      => 0,
  },
]