[
  {
    confirmed      => 33366,
    country_region => "Mainland China",
    deaths         => 1068,
    last_update    => "2020-02-12T14:13:08",
    province_state => "Hubei",
    recovered      => 2686,
  },
  {
    confirmed      => 1219,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-12T12:23:09",
    province_state => "Guangdong",
    recovered      => 275,
  },
  {
    confirmed      => 1135,
    country_region => "Mainland China",
    deaths         => 8,
    last_update    => "2020-02-12T14:13:08",
    province_state => "Henan",
    recovered      => 246,
  },
  {
    confirmed      => 1131,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-12T10:13:20",
    province_state => "Zhejiang",
    recovered      => 321,
  },
  {
    confirmed      => 946,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-12T12:43:03",
    province_state => "Hunan",
    recovered      => 304,
  },
  {
    confirmed      => 889,
    country_region => "Mainland China",
    deaths         => 4,
    last_update    => "2020-02-12T10:13:20",
    province_state => "Anhui",
    recovered      => 127,
  },
  {
    confirmed      => 844,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-12T01:23:06",
    province_state => "Jiangxi",
    recovered      => 152,
  },
  {
    confirmed      => 543,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-12T14:13:08",
    province_state => "Jiangsu",
    recovered      => 125,
  },
  {
    confirmed      => 518,
    country_region => "Mainland China",
    deaths         => 3,
    last_update    => "2020-02-12T23:13:08",
    province_state => "Chongqing",
    recovered      => 102,
  },
  {
    confirmed      => 497,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-12T11:13:05",
    province_state => "Shandong",
    recovered      => 92,
  },
  {
    confirmed      => 436,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-12T12:43:03",
    province_state => "Sichuan",
    recovered      => 92,
  },
  {
    confirmed      => 378,
    country_region => "Mainland China",
    deaths         => 8,
    last_update    => "2020-02-12T14:13:08",
    province_state => "Heilongjiang",
    recovered      => 31,
  },
  {
    confirmed      => 352,
    country_region => "Mainland China",
    deaths         => 3,
    last_update    => "2020-02-12T02:43:03",
    province_state => "Beijing",
    recovered      => 56,
  },
  {
    confirmed      => 311,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-12T06:23:08",
    province_state => "Shanghai",
    recovered      => 57,
  },
  {
    confirmed      => 272,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-12T11:53:02",
    province_state => "Fujian",
    recovered      => 53,
  },
  {
    confirmed      => 251,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-12T11:13:05",
    province_state => "Hebei",
    recovered      => 54,
  },
  {
    confirmed      => 225,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-12T11:13:05",
    province_state => "Shaanxi",
    recovered      => 43,
  },
  {
    confirmed      => 222,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-12T15:03:05",
    province_state => "Guangxi",
    recovered      => 32,
  },
  {
    confirmed      => 175,
    country_region => "Others",
    deaths         => 0,
    last_update    => "2020-02-12T04:23:38",
    province_state => "Diamond Princess cruise ship",
    recovered      => 0,
  },
  {
    confirmed      => 157,
    country_region => "Mainland China",
    deaths         => 4,
    last_update    => "2020-02-12T17:03:03",
    province_state => "Hainan",
    recovered      => 27,
  },
  {
    confirmed      => 154,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-12T14:13:08",
    province_state => "Yunnan",
    recovered      => 26,
  },
  {
    confirmed      => 133,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-12T09:43:02",
    province_state => "Guizhou",
    recovered      => 18,
  },
  {
    confirmed      => 126,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-12T23:03:02",
    province_state => "Shanxi",
    recovered      => 33,
  },
  {
    confirmed      => 116,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-12T13:33:02",
    province_state => "Liaoning",
    recovered      => 20,
  },
  {
    confirmed      => 112,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-12T15:03:05",
    province_state => "Tianjin",
    recovered      => 11,
  },
  {
    confirmed      => 87,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-12T23:23:01",
    province_state => "Gansu",
    recovered      => 31,
  },
  {
    confirmed      => 83,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-12T14:13:08",
    province_state => "Jilin",
    recovered      => 22,
  },
  {
    confirmed      => 60,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-12T11:13:05",
    province_state => "Inner Mongolia",
    recovered      => 6,
  },
  {
    confirmed      => 59,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-12T01:43:02",
    province_state => "Xinjiang",
    recovered      => 3,
  },
  {
    confirmed      => 58,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-12T11:13:05",
    province_state => "Ningxia",
    recovered      => 24,
  },
  {
    confirmed      => 50,
    country_region => "Hong Kong",
    deaths         => 1,
    last_update    => "2020-02-12T09:53:02",
    province_state => "Hong Kong",
    recovered      => 1,
  },
  {
    confirmed      => 50,
    country_region => "Singapore",
    deaths         => 0,
    last_update    => "2020-02-12T19:53:02",
    province_state => "",
    recovered      => 15,
  },
  {
    confirmed      => 33,
    country_region => "Thailand",
    deaths         => 0,
    last_update    => "2020-02-11T18:43:04",
    province_state => "",
    recovered      => 10,
  },
  {
    confirmed      => 28,
    country_region => "Japan",
    deaths         => 0,
    last_update    => "2020-02-12T02:43:03",
    province_state => "",
    recovered      => 9,
  },
  {
    confirmed      => 28,
    country_region => "South Korea",
    deaths         => 0,
    last_update    => "2020-02-12T14:43:03",
    province_state => "",
    recovered      => 7,
  },
  {
    confirmed      => 18,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-12T08:03:06",
    province_state => "Qinghai",
    recovered      => 9,
  },
  {
    confirmed      => 18,
    country_region => "Malaysia",
    deaths         => 0,
    last_update    => "2020-02-11T03:13:13",
    province_state => "",
    recovered      => 3,
  },
  {
    confirmed      => 18,
    country_region => "Taiwan",
    deaths         => 0,
    last_update    => "2020-02-09T09:13:11",
    province_state => "Taiwan",
    recovered      => 1,
  },
  {
    confirmed      => 16,
    country_region => "Germany",
    deaths         => 0,
    last_update    => "2020-02-11T19:33:03",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 15,
    country_region => "Vietnam",
    deaths         => 0,
    last_update    => "2020-02-11T16:43:06",
    province_state => "",
    recovered      => 6,
  },
  {
    confirmed      => 11,
    country_region => "France",
    deaths         => 0,
    last_update    => "2020-02-12T18:53:02",
    province_state => "",
    recovered      => 2,
  },
  {
    confirmed      => 10,
    country_region => "Macau",
    deaths         => 0,
    last_update    => "2020-02-12T09:53:02",
    province_state => "Macau",
    recovered      => 2,
  },
  {
    confirmed      => 9,
    country_region => "UK",
    deaths         => 0,
    last_update    => "2020-02-12T19:03:06",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 8,
    country_region => "United Arab Emirates",
    deaths         => 0,
    last_update    => "2020-02-12T00:33:02",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 5,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-09T19:33:02",
    province_state => "Queensland",
    recovered      => 0,
  },
  {
    confirmed      => 4,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-06T03:13:22",
    province_state => "New South Wales",
    recovered      => 2,
  },
  {
    confirmed      => 4,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-01T18:12:49",
    province_state => "Victoria",
    recovered      => 0,
  },
  {
    confirmed      => 4,
    country_region => "Canada",
    deaths         => 0,
    last_update    => "2020-02-07T05:43:03",
    province_state => "British Columbia",
    recovered      => 0,
  },
  {
    confirmed      => 3,
    country_region => "India",
    deaths         => 0,
    last_update    => "2020-02-03T21:43:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 3,
    country_region => "Italy",
    deaths         => 0,
    last_update    => "2020-02-07T17:53:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 3,
    country_region => "Philippines",
    deaths         => 1,
    last_update    => "2020-02-12T07:43:02",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 2,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-02T22:33:07",
    province_state => "South Australia",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "Canada",
    deaths         => 0,
    last_update    => "2020-02-04T00:13:06",
    province_state => "Toronto, ON",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "Russia",
    deaths         => 0,
    last_update    => "2020-02-12T14:43:03",
    province_state => "",
    recovered      => 2,
  },
  {
    confirmed      => 2,
    country_region => "Spain",
    deaths         => 0,
    last_update    => "2020-02-09T20:33:03",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-09T19:03:03",
    province_state => "Chicago, IL",
    recovered      => 2,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-03T03:53:02",
    province_state => "San Benito, CA",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-03T00:43:02",
    province_state => "Santa Clara, CA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Belgium",
    deaths         => 0,
    last_update    => "2020-02-04T15:43:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Cambodia",
    deaths         => 0,
    last_update    => "2020-02-12T07:43:02",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Canada",
    deaths         => 0,
    last_update    => "2020-02-12T18:53:03",
    province_state => "London, ON",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Finland",
    deaths         => 0,
    last_update    => "2020-02-12T00:03:12",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-12T06:43:02",
    province_state => "Tibet",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Nepal",
    deaths         => 0,
    last_update    => "2020-02-12T14:43:03",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Sri Lanka",
    deaths         => 0,
    last_update    => "2020-02-08T03:43:03",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Sweden",
    deaths         => 0,
    last_update    => "2020-02-01T02:13:26",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:43:03",
    province_state => "Boston, MA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:53:03",
    province_state => "Los Angeles, CA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-05T21:53:02",
    province_state => "Madison, WI",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:53:03",
    province_state => "Orange, CA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-11T01:23:05",
    province_state => "San Diego County, CA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-09T07:03:04",
    province_state => "Seattle, WA",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:43:03",
    province_state => "Tempe, AZ",
    recovered      => 0,
  },
]