[
  {
    confirmed      => 3554,
    country_region => "Mainland China",
    deaths         => 125,
    last_update    => "1/29/20 19:30",
    province_state => "Hubei",
    recovered      => 88,
  },
  {
    confirmed      => 296,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/29/20 19:30",
    province_state => "Zhejiang",
    recovered      => 3,
  },
  {
    confirmed      => 277,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/29/20 19:30",
    province_state => "Guangdong",
    recovered      => 5,
  },
  {
    confirmed      => 221,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/29/20 19:30",
    province_state => "Hunan",
    recovered      => "",
  },
  {
    confirmed      => 206,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "1/29/20 19:30",
    province_state => "Henan",
    recovered      => 1,
  },
  {
    confirmed      => 152,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/29/20 19:30",
    province_state => "Anhui",
    recovered      => 2,
  },
  {
    confirmed      => 147,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/29/20 19:30",
    province_state => "Chongqing",
    recovered      => 1,
  },
  {
    confirmed      => 130,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/29/20 19:30",
    province_state => "Shandong",
    recovered      => 1,
  },
  {
    confirmed      => 111,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "1/29/20 19:30",
    province_state => "Beijing",
    recovered      => 4,
  },
  {
    confirmed      => 109,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/29/20 19:30",
    province_state => "Jiangxi",
    recovered      => 3,
  },
  {
    confirmed      => 108,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "1/29/20 19:30",
    province_state => "Sichuan",
    recovered      => 1,
  },
  {
    confirmed      => 99,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/29/20 19:30",
    province_state => "Jiangsu",
    recovered      => 1,
  },
  {
    confirmed      => 96,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "1/29/20 19:30",
    province_state => "Shanghai",
    recovered      => 5,
  },
  {
    confirmed      => 84,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/29/20 19:30",
    province_state => "Fujian",
    recovered      => "",
  },
  {
    confirmed      => 58,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/29/20 19:30",
    province_state => "Guangxi",
    recovered      => 2,
  },
  {
    confirmed      => 56,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/29/20 19:30",
    province_state => "Shaanxi",
    recovered      => "",
  },
  {
    confirmed      => 55,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/29/20 19:30",
    province_state => "Yunnan",
    recovered      => "",
  },
  {
    confirmed      => 48,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "1/29/20 19:30",
    province_state => "Hebei",
    recovered      => "",
  },
  {
    confirmed      => 43,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "1/29/20 19:30",
    province_state => "Hainan",
    recovered      => "",
  },
  {
    confirmed      => 39,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/29/20 19:30",
    province_state => "Liaoning",
    recovered      => 1,
  },
  {
    confirmed      => 38,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "1/29/20 19:30",
    province_state => "Heilongjiang",
    recovered      => "",
  },
  {
    confirmed      => 27,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/29/20 19:30",
    province_state => "Tianjin",
    recovered      => "",
  },
  {
    confirmed      => 27,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/29/20 19:30",
    province_state => "Shanxi",
    recovered      => 1,
  },
  {
    confirmed      => 24,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/29/20 19:30",
    province_state => "Gansu",
    recovered      => "",
  },
  {
    confirmed      => 16,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/29/20 19:30",
    province_state => "Inner Mongolia",
    recovered      => "",
  },
  {
    confirmed      => 13,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/29/20 19:30",
    province_state => "Xinjiang",
    recovered      => "",
  },
  {
    confirmed      => 12,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/29/20 19:30",
    province_state => "Ningxia",
    recovered      => "",
  },
  {
    confirmed      => 10,
    country_region => "Hong Kong",
    deaths         => "",
    last_update    => "1/29/20 19:30",
    province_state => "Hong Kong",
    recovered      => "",
  },
  {
    confirmed      => 9,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/29/20 19:30",
    province_state => "Guizhou",
    recovered      => 1,
  },
  {
    confirmed      => 9,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/29/20 19:30",
    province_state => "Jilin",
    recovered      => "",
  },
  {
    confirmed      => 8,
    country_region => "Taiwan",
    deaths         => "",
    last_update    => "1/29/20 19:30",
    province_state => "Taiwan",
    recovered      => "",
  },
  {
    confirmed      => 7,
    country_region => "Macau",
    deaths         => "",
    last_update    => "1/29/20 19:30",
    province_state => "Macau",
    recovered      => "",
  },
  {
    confirmed      => 6,
    country_region => "Mainland China",
    deaths         => "",
    last_update    => "1/29/20 19:30",
    province_state => "Qinghai",
    recovered      => "",
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => "",
    last_update    => "1/29/20 19:30",
    province_state => "Washington",
    recovered      => "",
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => "",
    last_update    => "1/29/20 19:30",
    province_state => "Illinois",
    recovered      => "",
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => "",
    last_update    => "1/29/20 19:30",
    province_state => "California",
    recovered      => "",
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => "",
    last_update    => "1/29/20 19:30",
    province_state => "Arizona",
    recovered      => "",
  },
  {
    confirmed      => 7,
    country_region => "Japan",
    deaths         => "",
    last_update    => "1/29/20 19:30",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 14,
    country_region => "Thailand",
    deaths         => "",
    last_update    => "1/29/20 19:30",
    province_state => "",
    recovered      => 5,
  },
  {
    confirmed      => 4,
    country_region => "South Korea",
    deaths         => "",
    last_update    => "1/29/20 19:30",
    province_state => "",
    recovered      => "",
  },
  {
    confirmed      => 7,
    country_region => "Singapore",
    deaths         => "",
    last_update    => "1/29/20 19:30",
    province_state => "",
    recovered      => "",
  },
  {
    confirmed      => 2,
    country_region => "Vietnam",
    deaths         => "",
    last_update    => "1/29/20 19:30",
    province_state => "",
    recovered      => "",
  },
  {
    confirmed      => 5,
    country_region => "France",
    deaths         => "",
    last_update    => "1/29/20 19:30",
    province_state => "",
    recovered      => "",
  },
  {
    confirmed      => 1,
    country_region => "Nepal",
    deaths         => "",
    last_update    => "1/29/20 19:30",
    province_state => "",
    recovered      => "",
  },
  {
    confirmed      => 7,
    country_region => "Malaysia",
    deaths         => "",
    last_update    => "1/29/20 19:30",
    province_state => "",
    recovered      => "",
  },
  {
    confirmed      => 1,
    country_region => "Canada",
    deaths         => "",
    last_update    => "1/29/20 19:30",
    province_state => "Ontario",
    recovered      => "",
  },
  {
    confirmed      => 1,
    country_region => "Canada",
    deaths         => "",
    last_update    => "1/29/20 19:30",
    province_state => "British Columbia",
    recovered      => "",
  },
  {
    confirmed      => 1,
    country_region => "Cambodia",
    deaths         => "",
    last_update    => "1/29/20 19:30",
    province_state => "",
    recovered      => "",
  },
  {
    confirmed      => 1,
    country_region => "Sri Lanka",
    deaths         => "",
    last_update    => "1/29/20 19:30",
    province_state => "",
    recovered      => "",
  },
  {
    confirmed      => 4,
    country_region => "Australia",
    deaths         => "",
    last_update    => "1/29/20 19:30",
    province_state => "New South Wales",
    recovered      => "",
  },
  {
    confirmed      => 1,
    country_region => "Australia",
    deaths         => "",
    last_update    => "1/29/20 19:30",
    province_state => "Victoria",
    recovered      => "",
  },
  {
    confirmed      => 4,
    country_region => "Germany",
    deaths         => "",
    last_update    => "1/29/20 19:30",
    province_state => "Bavaria",
    recovered      => "",
  },
  {
    confirmed      => 1,
    country_region => "Finland",
    deaths         => "",
    last_update    => "1/29/20 19:30",
    province_state => "",
    recovered      => "",
  },
  {
    confirmed      => 4,
    country_region => "United Arab Emirates",
    deaths         => "",
    last_update    => "1/29/20 19:30",
    province_state => "",
    recovered      => "",
  },
]