[
  {
    confirmed      => 13522,
    country_region => "Mainland China",
    deaths         => 414,
    last_update    => "2020-02-03T23:23:03",
    province_state => "Hubei",
    recovered      => 386,
  },
  {
    confirmed      => 725,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-03T12:53:02",
    province_state => "Guangdong",
    recovered      => 21,
  },
  {
    confirmed      => 724,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-03T13:33:02",
    province_state => "Zhejiang",
    recovered      => 43,
  },
  {
    confirmed      => 566,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-03T17:11:34",
    province_state => "Henan",
    recovered      => 16,
  },
  {
    confirmed      => 521,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-03T11:03:10",
    province_state => "Hunan",
    recovered      => 22,
  },
  {
    confirmed      => 408,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-03T17:11:34",
    province_state => "Anhui",
    recovered      => 14,
  },
  {
    confirmed      => 391,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-03T01:33:02",
    province_state => "Jiangxi",
    recovered      => 18,
  },
  {
    confirmed      => 337,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-03T23:43:02",
    province_state => "Chongqing",
    recovered      => 9,
  },
  {
    confirmed      => 271,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-03T11:03:10",
    province_state => "Jiangsu",
    recovered      => 8,
  },
  {
    confirmed      => 259,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-03T17:11:34",
    province_state => "Shandong",
    recovered      => 7,
  },
  {
    confirmed      => 254,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-03T11:23:23",
    province_state => "Sichuan",
    recovered      => 14,
  },
  {
    confirmed      => 212,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-03T09:23:05",
    province_state => "Beijing",
    recovered      => 12,
  },
  {
    confirmed      => 203,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-03T07:03:12",
    province_state => "Shanghai",
    recovered      => 10,
  },
  {
    confirmed      => 179,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-03T11:33:13",
    province_state => "Fujian",
    recovered      => 1,
  },
  {
    confirmed      => 128,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-03T02:33:02",
    province_state => "Shaanxi",
    recovered      => 0,
  },
  {
    confirmed      => 127,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-03T12:33:02",
    province_state => "Guangxi",
    recovered      => 7,
  },
  {
    confirmed      => 121,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-03T07:13:19",
    province_state => "Heilongjiang",
    recovered      => 2,
  },
  {
    confirmed      => 117,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-03T23:23:03",
    province_state => "Yunnan",
    recovered      => 5,
  },
  {
    confirmed      => 113,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-03T00:23:14",
    province_state => "Hebei",
    recovered      => 3,
  },
  {
    confirmed      => 74,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-03T17:11:34",
    province_state => "Liaoning",
    recovered      => 1,
  },
  {
    confirmed      => 74,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-03T23:13:11",
    province_state => "Shanxi",
    recovered      => 2,
  },
  {
    confirmed      => 72,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-03T17:11:34",
    province_state => "Hainan",
    recovered      => 4,
  },
  {
    confirmed      => 60,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-03T13:53:03",
    province_state => "Tianjin",
    recovered      => 1,
  },
  {
    confirmed      => 55,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-03T23:03:08",
    province_state => "Gansu",
    recovered      => 3,
  },
  {
    confirmed      => 46,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-03T01:03:22",
    province_state => "Guizhou",
    recovered      => 2,
  },
  {
    confirmed      => 34,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-03T03:03:09",
    province_state => "Inner Mongolia",
    recovered      => 1,
  },
  {
    confirmed      => 31,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-03T00:53:03",
    province_state => "Jilin",
    recovered      => 1,
  },
  {
    confirmed      => 31,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-03T08:33:03",
    province_state => "Ningxia",
    recovered      => 1,
  },
  {
    confirmed      => 24,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-03T01:13:21",
    province_state => "Xinjiang",
    recovered      => 0,
  },
  {
    confirmed      => 20,
    country_region => "Japan",
    deaths         => 0,
    last_update    => "2020-02-01T18:53:03",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 19,
    country_region => "Thailand",
    deaths         => 0,
    last_update    => "2020-01-31T10:37:00",
    province_state => "",
    recovered      => 5,
  },
  {
    confirmed      => 18,
    country_region => "Singapore",
    deaths         => 0,
    last_update    => "2020-02-02T01:03:32",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 15,
    country_region => "Hong Kong",
    deaths         => 0,
    last_update    => "2020-02-02T23:53:02",
    province_state => "Hong Kong",
    recovered      => 0,
  },
  {
    confirmed      => 15,
    country_region => "South Korea",
    deaths         => 0,
    last_update    => "2020-02-02T02:23:13",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 13,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-03T02:43:01",
    province_state => "Qinghai",
    recovered      => 0,
  },
  {
    confirmed      => 12,
    country_region => "Germany",
    deaths         => 0,
    last_update    => "2020-02-03T20:53:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 10,
    country_region => "Taiwan",
    deaths         => 0,
    last_update    => "2020-01-31T15:20:56",
    province_state => "Taiwan",
    recovered      => 0,
  },
  {
    confirmed      => 8,
    country_region => "Macau",
    deaths         => 0,
    last_update    => "2020-02-02T04:23:14",
    province_state => "Macau",
    recovered      => 0,
  },
  {
    confirmed      => 8,
    country_region => "Malaysia",
    deaths         => 0,
    last_update    => "2020-01-31T08:15:53",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 8,
    country_region => "Vietnam",
    deaths         => 0,
    last_update    => "2020-02-03T21:43:02",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 6,
    country_region => "France",
    deaths         => 0,
    last_update    => "2020-02-01T01:52:40",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 5,
    country_region => "United Arab Emirates",
    deaths         => 0,
    last_update    => "2020-02-02T05:43:01",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 4,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-01T18:12:49",
    province_state => "New South Wales",
    recovered      => 2,
  },
  {
    confirmed      => 4,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-01T18:12:49",
    province_state => "Victoria",
    recovered      => 0,
  },
  {
    confirmed      => 3,
    country_region => "Canada",
    deaths         => 0,
    last_update    => "2020-02-01T18:12:49",
    province_state => "Ontario",
    recovered      => 0,
  },
  {
    confirmed      => 3,
    country_region => "India",
    deaths         => 0,
    last_update    => "2020-02-03T21:43:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-02T22:33:07",
    province_state => "Queensland",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-02T22:33:07",
    province_state => "South Australia",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "Italy",
    deaths         => 0,
    last_update    => "2020-01-31T08:15:53",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "Philippines",
    deaths         => 1,
    last_update    => "2020-02-02T03:33:07",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "Russia",
    deaths         => 0,
    last_update    => "2020-01-31T16:13:45",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "UK",
    deaths         => 0,
    last_update    => "2020-02-01T01:52:40",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:43:03",
    province_state => "Chicago, IL",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-03T03:53:02",
    province_state => "San Benito, CA",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-03T00:43:02",
    province_state => "Santa Clara, CA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Cambodia",
    deaths         => 0,
    last_update    => "2020-01-31T08:15:53",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Canada",
    deaths         => 0,
    last_update    => "2020-02-01T18:12:49",
    province_state => "British Columbia",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Finland",
    deaths         => 0,
    last_update    => "2020-01-31T08:15:53",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-01T01:52:40",
    province_state => "Tibet",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Nepal",
    deaths         => 0,
    last_update    => "2020-01-31T08:15:53",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Spain",
    deaths         => 0,
    last_update    => "2020-02-01T23:43:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Sri Lanka",
    deaths         => 0,
    last_update    => "2020-01-31T08:15:53",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Sweden",
    deaths         => 0,
    last_update    => "2020-02-01T02:13:26",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:43:03",
    province_state => "Boston, MA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:53:03",
    province_state => "Los Angeles, CA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:53:03",
    province_state => "Orange, CA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:43:03",
    province_state => "Seattle, WA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:43:03",
    province_state => "Tempe, AZ",
    recovered      => 0,
  },
]