[
  {
    confirmed      => 33366,
    country_region => "Mainland China",
    deaths         => 1068,
    last_update    => "2020-02-11T23:33:02",
    province_state => "Hubei",
    recovered      => 2639,
  },
  {
    confirmed      => 1177,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-11T14:03:05",
    province_state => "Guangdong",
    recovered      => 212,
  },
  {
    confirmed      => 1117,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-11T12:53:02",
    province_state => "Zhejiang",
    recovered      => 270,
  },
  {
    confirmed      => 1105,
    country_region => "Mainland China",
    deaths         => 7,
    last_update    => "2020-02-11T14:03:05",
    province_state => "Henan",
    recovered      => 218,
  },
  {
    confirmed      => 912,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-11T12:53:02",
    province_state => "Hunan",
    recovered      => 247,
  },
  {
    confirmed      => 860,
    country_region => "Mainland China",
    deaths         => 4,
    last_update    => "2020-02-11T09:43:02",
    province_state => "Anhui",
    recovered      => 105,
  },
  {
    confirmed      => 804,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-11T14:03:05",
    province_state => "Jiangxi",
    recovered      => 128,
  },
  {
    confirmed      => 515,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-11T08:13:06",
    province_state => "Jiangsu",
    recovered      => 93,
  },
  {
    confirmed      => 505,
    country_region => "Mainland China",
    deaths         => 3,
    last_update    => "2020-02-11T23:53:02",
    province_state => "Chongqing",
    recovered      => 79,
  },
  {
    confirmed      => 487,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-11T11:23:04",
    province_state => "Shandong",
    recovered      => 80,
  },
  {
    confirmed      => 417,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-11T11:23:04",
    province_state => "Sichuan",
    recovered      => 85,
  },
  {
    confirmed      => 360,
    country_region => "Mainland China",
    deaths         => 8,
    last_update    => "2020-02-11T11:23:04",
    province_state => "Heilongjiang",
    recovered      => 28,
  },
  {
    confirmed      => 342,
    country_region => "Mainland China",
    deaths         => 3,
    last_update    => "2020-02-11T03:03:07",
    province_state => "Beijing",
    recovered      => 48,
  },
  {
    confirmed      => 303,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-11T06:23:02",
    province_state => "Shanghai",
    recovered      => 52,
  },
  {
    confirmed      => 267,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-11T14:03:05",
    province_state => "Fujian",
    recovered      => 45,
  },
  {
    confirmed      => 239,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-11T11:23:04",
    province_state => "Hebei",
    recovered      => 48,
  },
  {
    confirmed      => 219,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-11T06:03:16",
    province_state => "Shaanxi",
    recovered      => 32,
  },
  {
    confirmed      => 215,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-11T11:23:04",
    province_state => "Guangxi",
    recovered      => 33,
  },
  {
    confirmed      => 153,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-11T09:23:04",
    province_state => "Yunnan",
    recovered      => 20,
  },
  {
    confirmed      => 144,
    country_region => "Mainland China",
    deaths         => 3,
    last_update    => "2020-02-11T14:33:02",
    province_state => "Hainan",
    recovered      => 20,
  },
  {
    confirmed      => 135,
    country_region => "Others",
    deaths         => 0,
    last_update    => "2020-02-10T16:03:12",
    province_state => "Diamond Princess cruise ship",
    recovered      => 0,
  },
  {
    confirmed      => 127,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-11T14:03:05",
    province_state => "Guizhou",
    recovered      => 17,
  },
  {
    confirmed      => 124,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-11T23:33:02",
    province_state => "Shanxi",
    recovered      => 30,
  },
  {
    confirmed      => 111,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-11T12:53:02",
    province_state => "Liaoning",
    recovered      => 19,
  },
  {
    confirmed      => 106,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-11T23:13:05",
    province_state => "Tianjin",
    recovered      => 10,
  },
  {
    confirmed      => 86,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2020-02-11T15:23:04",
    province_state => "Gansu",
    recovered      => 24,
  },
  {
    confirmed      => 81,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2020-02-11T08:03:06",
    province_state => "Jilin",
    recovered      => 18,
  },
  {
    confirmed      => 58,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-10T02:43:05",
    province_state => "Inner Mongolia",
    recovered      => 5,
  },
  {
    confirmed      => 55,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-11T09:13:11",
    province_state => "Xinjiang",
    recovered      => 3,
  },
  {
    confirmed      => 53,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-11T10:03:08",
    province_state => "Ningxia",
    recovered      => 22,
  },
  {
    confirmed      => 49,
    country_region => "Hong Kong",
    deaths         => 1,
    last_update    => "2020-02-11T09:43:02",
    province_state => "Hong Kong",
    recovered      => 0,
  },
  {
    confirmed      => 47,
    country_region => "Singapore",
    deaths         => 0,
    last_update    => "2020-02-11T16:43:06",
    province_state => "",
    recovered      => 9,
  },
  {
    confirmed      => 33,
    country_region => "Thailand",
    deaths         => 0,
    last_update    => "2020-02-11T18:43:04",
    province_state => "",
    recovered      => 10,
  },
  {
    confirmed      => 28,
    country_region => "South Korea",
    deaths         => 0,
    last_update    => "2020-02-11T02:53:02",
    province_state => "",
    recovered      => 3,
  },
  {
    confirmed      => 26,
    country_region => "Japan",
    deaths         => 0,
    last_update    => "2020-02-11T02:53:02",
    province_state => "",
    recovered      => 9,
  },
  {
    confirmed      => 18,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-11T11:23:04",
    province_state => "Qinghai",
    recovered      => 5,
  },
  {
    confirmed      => 18,
    country_region => "Malaysia",
    deaths         => 0,
    last_update    => "2020-02-11T03:13:13",
    province_state => "",
    recovered      => 3,
  },
  {
    confirmed      => 18,
    country_region => "Taiwan",
    deaths         => 0,
    last_update    => "2020-02-09T09:13:11",
    province_state => "Taiwan",
    recovered      => 1,
  },
  {
    confirmed      => 16,
    country_region => "Germany",
    deaths         => 0,
    last_update    => "2020-02-11T19:33:03",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 15,
    country_region => "Vietnam",
    deaths         => 0,
    last_update    => "2020-02-11T16:43:06",
    province_state => "",
    recovered      => 6,
  },
  {
    confirmed      => 11,
    country_region => "France",
    deaths         => 0,
    last_update    => "2020-02-08T09:53:01",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 10,
    country_region => "Macau",
    deaths         => 0,
    last_update    => "2020-02-06T14:23:04",
    province_state => "Macau",
    recovered      => 1,
  },
  {
    confirmed      => 8,
    country_region => "UK",
    deaths         => 0,
    last_update    => "2020-02-10T19:03:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 8,
    country_region => "United Arab Emirates",
    deaths         => 0,
    last_update    => "2020-02-10T23:03:09",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 5,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-09T19:33:02",
    province_state => "Queensland",
    recovered      => 0,
  },
  {
    confirmed      => 4,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-06T03:13:22",
    province_state => "New South Wales",
    recovered      => 2,
  },
  {
    confirmed      => 4,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-01T18:12:49",
    province_state => "Victoria",
    recovered      => 0,
  },
  {
    confirmed      => 4,
    country_region => "Canada",
    deaths         => 0,
    last_update    => "2020-02-07T05:43:03",
    province_state => "British Columbia",
    recovered      => 0,
  },
  {
    confirmed      => 3,
    country_region => "India",
    deaths         => 0,
    last_update    => "2020-02-03T21:43:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 3,
    country_region => "Italy",
    deaths         => 0,
    last_update    => "2020-02-07T17:53:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 3,
    country_region => "Philippines",
    deaths         => 1,
    last_update    => "2020-02-07T16:43:04",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2020-02-02T22:33:07",
    province_state => "South Australia",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "Canada",
    deaths         => 0,
    last_update    => "2020-02-04T00:13:06",
    province_state => "Toronto, ON",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "Russia",
    deaths         => 0,
    last_update    => "2020-01-31T16:13:45",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "Spain",
    deaths         => 0,
    last_update    => "2020-02-09T20:33:03",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-09T19:03:03",
    province_state => "Chicago, IL",
    recovered      => 2,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-03T03:53:02",
    province_state => "San Benito, CA",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-03T00:43:02",
    province_state => "Santa Clara, CA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Belgium",
    deaths         => 0,
    last_update    => "2020-02-04T15:43:02",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Cambodia",
    deaths         => 0,
    last_update    => "2020-01-31T08:15:53",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Canada",
    deaths         => 0,
    last_update    => "2020-02-04T00:03:11",
    province_state => "London, ON",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Finland",
    deaths         => 0,
    last_update    => "2020-01-31T08:15:53",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2020-02-01T01:52:40",
    province_state => "Tibet",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Nepal",
    deaths         => 0,
    last_update    => "2020-01-31T08:15:53",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Sri Lanka",
    deaths         => 0,
    last_update    => "2020-02-08T03:43:03",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "Sweden",
    deaths         => 0,
    last_update    => "2020-02-01T02:13:26",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:43:03",
    province_state => "Boston, MA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:53:03",
    province_state => "Los Angeles, CA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-05T21:53:02",
    province_state => "Madison, WI",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:53:03",
    province_state => "Orange, CA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-11T01:23:05",
    province_state => "San Diego County, CA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-09T07:03:04",
    province_state => "Seattle, WA",
    recovered      => 1,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2020-02-01T19:43:03",
    province_state => "Tempe, AZ",
    recovered      => 0,
  },
]