[
  {
    confirmed      => 7153,
    country_region => "Mainland China",
    deaths         => 249,
    last_update    => "2/1/2020 11:53",
    province_state => "Hubei",
    recovered      => 168,
  },
  {
    confirmed      => 599,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2/1/2020 10:53",
    province_state => "Zhejiang",
    recovered      => 21,
  },
  {
    confirmed      => 535,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2/1/2020 14:23",
    province_state => "Guangdong",
    recovered      => 14,
  },
  {
    confirmed      => 422,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2/1/2020 1:52",
    province_state => "Henan",
    recovered      => 3,
  },
  {
    confirmed      => 389,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2/1/2020 11:03",
    province_state => "Hunan",
    recovered      => 8,
  },
  {
    confirmed      => 297,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2/1/2020 13:33",
    province_state => "Anhui",
    recovered      => 5,
  },
  {
    confirmed      => 286,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2/1/2020 1:52",
    province_state => "Jiangxi",
    recovered      => 9,
  },
  {
    confirmed      => 247,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2/1/2020 8:43",
    province_state => "Chongqing",
    recovered      => 3,
  },
  {
    confirmed      => 207,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2/1/2020 1:52",
    province_state => "Sichuan",
    recovered      => 3,
  },
  {
    confirmed      => 206,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2/1/2020 7:51",
    province_state => "Shandong",
    recovered      => 3,
  },
  {
    confirmed      => 202,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2/1/2020 14:03",
    province_state => "Jiangsu",
    recovered      => 6,
  },
  {
    confirmed      => 169,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2/1/2020 6:05",
    province_state => "Shanghai",
    recovered      => 10,
  },
  {
    confirmed      => 168,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2/1/2020 9:17",
    province_state => "Beijing",
    recovered      => 9,
  },
  {
    confirmed      => 144,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2/1/2020 5:37",
    province_state => "Fujian",
    recovered      => 0,
  },
  {
    confirmed      => 101,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2/1/2020 5:37",
    province_state => "Shaanxi",
    recovered      => 0,
  },
  {
    confirmed      => 100,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2/1/2020 1:52",
    province_state => "Guangxi",
    recovered      => 2,
  },
  {
    confirmed      => 96,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2/1/2020 1:52",
    province_state => "Hebei",
    recovered      => 0,
  },
  {
    confirmed      => 93,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2/1/2020 15:53",
    province_state => "Yunnan",
    recovered      => 2,
  },
  {
    confirmed      => 80,
    country_region => "Mainland China",
    deaths         => 2,
    last_update    => "2/1/2020 10:33",
    province_state => "Heilongjiang",
    recovered      => 2,
  },
  {
    confirmed      => 64,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2/1/2020 15:23",
    province_state => "Liaoning",
    recovered      => 1,
  },
  {
    confirmed      => 62,
    country_region => "Mainland China",
    deaths         => 1,
    last_update    => "2/1/2020 8:43",
    province_state => "Hainan",
    recovered      => 1,
  },
  {
    confirmed      => 47,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2/1/2020 1:52",
    province_state => "Shanxi",
    recovered      => 1,
  },
  {
    confirmed      => 41,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2/1/2020 15:43",
    province_state => "Tianjin",
    recovered      => 0,
  },
  {
    confirmed      => 40,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2/1/2020 15:43",
    province_state => "Gansu",
    recovered      => 0,
  },
  {
    confirmed      => 29,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "1/31/2020 15:20",
    province_state => "Guizhou",
    recovered      => 2,
  },
  {
    confirmed      => 26,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2/1/2020 2:13",
    province_state => "Ningxia",
    recovered      => 0,
  },
  {
    confirmed      => 23,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2/1/2020 5:37",
    province_state => "Inner Mongolia",
    recovered      => 1,
  },
  {
    confirmed      => 20,
    country_region => "Japan",
    deaths         => 0,
    last_update    => "2/1/2020 18:53",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 19,
    country_region => "Thailand",
    deaths         => 0,
    last_update    => "1/31/2020 10:37",
    province_state => "",
    recovered      => 5,
  },
  {
    confirmed      => 18,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2/1/2020 5:37",
    province_state => "Xinjiang",
    recovered      => 0,
  },
  {
    confirmed      => 17,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2/1/2020 1:52",
    province_state => "Jilin",
    recovered      => 1,
  },
  {
    confirmed      => 16,
    country_region => "Singapore",
    deaths         => 0,
    last_update    => "2/1/2020 5:37",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 13,
    country_region => "Hong Kong",
    deaths         => 0,
    last_update    => "2/1/2020 5:37",
    province_state => "Hong Kong",
    recovered      => 0,
  },
  {
    confirmed      => 12,
    country_region => "South Korea",
    deaths         => 0,
    last_update    => "2/1/2020 10:43",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 10,
    country_region => "Taiwan",
    deaths         => 0,
    last_update    => "1/31/2020 15:20",
    province_state => "Taiwan",
    recovered      => 0,
  },
  {
    confirmed      => 9,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2/1/2020 5:37",
    province_state => "Qinghai",
    recovered      => 0,
  },
  {
    confirmed      => 8,
    country_region => "Malaysia",
    deaths         => 0,
    last_update    => "1/31/2020 8:15",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 8,
    country_region => "Germany",
    deaths         => 0,
    last_update    => "2/1/2020 18:33",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 7,
    country_region => "Macau",
    deaths         => 0,
    last_update    => "1/31/2020 8:15",
    province_state => "Macau",
    recovered      => 0,
  },
  {
    confirmed      => 6,
    country_region => "France",
    deaths         => 0,
    last_update    => "2/1/2020 1:52",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 6,
    country_region => "Vietnam",
    deaths         => 0,
    last_update    => "2/1/2020 7:38",
    province_state => "",
    recovered      => 1,
  },
  {
    confirmed      => 4,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2/1/2020 18:12",
    province_state => "New South Wales",
    recovered      => 2,
  },
  {
    confirmed      => 4,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2/1/2020 18:12",
    province_state => "Victoria",
    recovered      => 0,
  },
  {
    confirmed      => 4,
    country_region => "United Arab Emirates",
    deaths         => 0,
    last_update    => "1/31/2020 8:15",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 3,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2/1/2020 18:12",
    province_state => "Queensland",
    recovered      => 0,
  },
  {
    confirmed      => 3,
    country_region => "Canada",
    deaths         => 0,
    last_update    => "2/1/2020 18:12",
    province_state => "Ontario",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "Italy",
    deaths         => 0,
    last_update    => "1/31/2020 8:15",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "Russia",
    deaths         => 0,
    last_update    => "1/31/2020 16:13",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "UK",
    deaths         => 0,
    last_update    => "2/1/2020 1:52",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 2,
    country_region => "US",
    deaths         => 0,
    last_update    => "2/1/2020 19:43",
    province_state => "Chicago, IL",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Australia",
    deaths         => 0,
    last_update    => "2/1/2020 18:12",
    province_state => "South Australia",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Cambodia",
    deaths         => 0,
    last_update    => "1/31/2020 8:15",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Canada",
    deaths         => 0,
    last_update    => "2/1/2020 18:12",
    province_state => "British Columbia",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Finland",
    deaths         => 0,
    last_update    => "1/31/2020 8:15",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "India",
    deaths         => 0,
    last_update    => "1/31/2020 8:15",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Mainland China",
    deaths         => 0,
    last_update    => "2/1/2020 1:52",
    province_state => "Tibet",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Nepal",
    deaths         => 0,
    last_update    => "1/31/2020 8:15",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Philippines",
    deaths         => 0,
    last_update    => "2/1/2020 17:43",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Spain",
    deaths         => 0,
    last_update    => "2/1/2020 2:13",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Sri Lanka",
    deaths         => 0,
    last_update    => "1/31/2020 8:15",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "Sweden",
    deaths         => 0,
    last_update    => "2/1/2020 2:13",
    province_state => "",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2/1/2020 19:43",
    province_state => "Boston, MA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2/1/2020 19:53",
    province_state => "Los Angeles, CA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2/1/2020 19:53",
    province_state => "Orange, CA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2/1/2020 19:53",
    province_state => "Santa Clara, CA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2/1/2020 19:43",
    province_state => "Seattle, WA",
    recovered      => 0,
  },
  {
    confirmed      => 1,
    country_region => "US",
    deaths         => 0,
    last_update    => "2/1/2020 19:43",
    province_state => "Tempe, AZ",
    recovered      => 0,
  },
]